// Auto-generated by scripts/generate_simd_smoke_test.py
// Exercises every modelled SIMD builtin once so the library models are
// type-checked, linked and symex'd. See doc/neon-intrinsic-models.md.

typedef char __gcc_v16qi __attribute__((__vector_size__(16)));
typedef signed char __gcc_v16qi_s __attribute__((__vector_size__(16)));
typedef unsigned char __gcc_v16qi_u __attribute__((__vector_size__(16)));
typedef long long __gcc_v1di_s __attribute__((__vector_size__(8)));
typedef unsigned long long __gcc_v1di_u __attribute__((__vector_size__(8)));
typedef long long __gcc_v2di_s __attribute__((__vector_size__(16)));
typedef unsigned long long __gcc_v2di_u __attribute__((__vector_size__(16)));
typedef int __gcc_v2si_s __attribute__((__vector_size__(8)));
typedef unsigned int __gcc_v2si_u __attribute__((__vector_size__(8)));
typedef short __gcc_v4hi_s __attribute__((__vector_size__(8)));
typedef unsigned short __gcc_v4hi_u __attribute__((__vector_size__(8)));
typedef int __gcc_v4si_s __attribute__((__vector_size__(16)));
typedef unsigned int __gcc_v4si_u __attribute__((__vector_size__(16)));
typedef short __gcc_v8hi_s __attribute__((__vector_size__(16)));
typedef unsigned short __gcc_v8hi_u __attribute__((__vector_size__(16)));
typedef char __gcc_v8qi __attribute__((__vector_size__(8)));
typedef signed char __gcc_v8qi_s __attribute__((__vector_size__(8)));
typedef unsigned char __gcc_v8qi_u __attribute__((__vector_size__(8)));

int main(void)
{
  {
    __gcc_v8qi a0 = {0};
    __gcc_v8qi a1 = {0};
    volatile __gcc_v8qi r = __builtin_neon_vabd_v(a0, a1, 0);
    (void)r;
  }
  {
    __gcc_v8qi a0 = {0};
    __gcc_v8qi a1 = {0};
    __gcc_v8qi a2 = {0};
    volatile __gcc_v8qi r = __builtin_neon_vbsl_v(a0, a1, a2, 1);
    (void)r;
  }
  {
    __gcc_v8qi a0 = {0};
    __gcc_v8qi a1 = {0};
    volatile __gcc_v8qi r = __builtin_neon_vhadd_v(a0, a1, 0);
    (void)r;
  }
  {
    __gcc_v8qi a0 = {0};
    __gcc_v8qi a1 = {0};
    volatile __gcc_v8qi r = __builtin_neon_vhsub_v(a0, a1, 0);
    (void)r;
  }
  {
    __gcc_v16qi a0 = {0};
    __gcc_v16qi a1 = {0};
    volatile __gcc_v16qi r = __builtin_neon_vhsubq_v(a0, a1, 32);
    (void)r;
  }
  {
    __gcc_v8qi a0 = {0};
    __gcc_v8qi a1 = {0};
    volatile __gcc_v8qi r = __builtin_neon_vmax_v(a0, a1, 0);
    (void)r;
  }
  {
    __gcc_v8qi a0 = {0};
    __gcc_v8qi a1 = {0};
    volatile __gcc_v8qi r = __builtin_neon_vmin_v(a0, a1, 0);
    (void)r;
  }
  {
    __gcc_v16qi a0 = {0};
    __gcc_v16qi a1 = {0};
    volatile __gcc_v16qi r = __builtin_neon_vminq_v(a0, a1, 32);
    (void)r;
  }
  {
    __gcc_v8qi a0 = {0};
    __gcc_v8qi a1 = {0};
    volatile __gcc_v8qi r = __builtin_neon_vpadd_v(a0, a1, 0);
    (void)r;
  }
  {
    __gcc_v16qi a0 = {0};
    __gcc_v16qi a1 = {0};
    volatile __gcc_v16qi r = __builtin_neon_vpaddq_v(a0, a1, 32);
    (void)r;
  }
  {
    __gcc_v8qi a0 = {0};
    __gcc_v8qi a1 = {0};
    volatile __gcc_v8qi r = __builtin_neon_vpmax_v(a0, a1, 0);
    (void)r;
  }
  {
    __gcc_v8qi a0 = {0};
    __gcc_v8qi a1 = {0};
    volatile __gcc_v8qi r = __builtin_neon_vpmin_v(a0, a1, 0);
    (void)r;
  }
  {
    __gcc_v16qi a0 = {0};
    __gcc_v16qi a1 = {0};
    volatile __gcc_v16qi r = __builtin_neon_vpminq_v(a0, a1, 32);
    (void)r;
  }
  {
    __gcc_v8qi a0 = {0};
    __gcc_v8qi a1 = {0};
    volatile __gcc_v8qi r = __builtin_neon_vqadd_v(a0, a1, 0);
    (void)r;
  }
  {
    __gcc_v8qi a0 = {0};
    __gcc_v8qi a1 = {0};
    volatile __gcc_v8qi r = __builtin_neon_vqsub_v(a0, a1, 0);
    (void)r;
  }
  {
    __gcc_v16qi a0 = {0};
    __gcc_v16qi a1 = {0};
    volatile __gcc_v16qi r = __builtin_neon_vqsubq_v(a0, a1, 32);
    (void)r;
  }
  {
    __gcc_v8qi a0 = {0};
    __gcc_v8qi a1 = {0};
    volatile __gcc_v8qi r = __builtin_neon_vrhadd_v(a0, a1, 0);
    (void)r;
  }
  {
    __gcc_v16qi a0 = {0};
    __gcc_v16qi a1 = {0};
    volatile __gcc_v16qi r = __builtin_neon_vrhaddq_v(a0, a1, 32);
    (void)r;
  }
  {
    __gcc_v8qi a0 = {0};
    __gcc_v8qi a1 = {0};
    volatile __gcc_v8qi r = __builtin_neon_vtst_v(a0, a1, 0);
    (void)r;
  }
  __CPROVER_assert(1, "SIMD model smoke test");
  return 0;
}
