FROM ubuntu:16.04

RUN apt-get update && apt-get --no-install-recommends -y install \
        build-essential gcc git make flex bison \
        software-properties-common libwww-perl python \
        bin86 gdb bcc liblzma-dev python-dev gettext iasl \
        uuid-dev libncurses5-dev libncursesw5-dev pkg-config bc \
        libgtk2.0-dev libyajl-dev sudo time libelf-dev openssl libssl-dev
