version: 0.2

env:
  variables:
    # CodeBuild console doesn't display color codes correctly
    TESTPL_COLOR_OUTPUT: 0

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - sed -i 's#/archive.ubuntu.com#/us-east-1.ec2.archive.ubuntu.com#g' /etc/apt/sources.list
      - apt-get update -y
      - apt-get install -y flex bison make git libwww-perl patch ccache libc6-dev-i386 jq cmake python3 python3-pip
      - pip3 install lxml
  build:
    commands:
      - echo Build started on `date`
      - cmake -S . -Bbuild '-DCMAKE_BUILD_TYPE=Release'  '-DCMAKE_CXX_COMPILER=/usr/bin/g++'
      - git submodule update --init --recursive
      - cmake --build build -- -j2
  post_build:
    commands:
      - cd build; ctest -V -L CORE -j2
      - cd build; ctest -V -R unit-xfail -j2
      - echo Build completed on `date`
cache:
  paths:
    - '/var/cache/apt/**/*'
    - '/var/lib/apt/lists/**/*'
    - '/root/.ccache/**/*'
