version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - sed -i 's#/archive.ubuntu.com#/us-east-1.ec2.archive.ubuntu.com#g' /etc/apt/sources.list
      - apt-get update -y
      - apt-get install -y clang-7 flex bison make git libwww-perl patch ccache libc6-dev-i386 jq
  build:
    commands:
      - echo Build started on `date`
      - git submodule update --init --recursive
      - make -C src CXX='ccache /usr/bin/clang++-7' CXX_FLAGS='-Qunused-arguments'
      - make -C jbmc/src CXX='ccache /usr/bin/clang++-7' CXX_FLAGS='-Qunused-arguments'
  post_build:
    commands:
      - make -C unit test CXX='ccache /usr/bin/clang++-7' CXX_FLAGS='-Qunused-arguments'
      - make -C regression test
      - env PATH=$PATH:`pwd`/src/solvers make -C regression/cbmc test-cprover-smt2
      - make -C jbmc/unit test CXX='ccache /usr/bin/clang++-7' CXX_FLAGS='-Qunused-arguments'
      - make -C jbmc/regression test
      - echo Build completed on `date`
cache:
  paths:
    - '/var/cache/apt/**/*'
    - '/var/lib/apt/lists/**/*'
    - '/root/.ccache/**/*'
