version: 0.2

env:
  variables:
    # CodeBuild console doesn't display color codes correctly
    TESTPL_COLOR_OUTPUT: 0

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - sed -i 's#/archive.ubuntu.com#/us-east-1.ec2.archive.ubuntu.com#g' /etc/apt/sources.list
      - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
      - add-apt-repository 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-8 main'
      - apt-get update -y
      - apt-get install -y clang-8 flex bison make git libwww-perl patch ccache libc6-dev-i386 jq gdb
  build:
    commands:
      - echo Build started on `date`
      - make -C src minisat2-download
      - make -C jbmc/src setup-submodules
      - make -C src CXX='ccache /usr/bin/clang++-8' CXX_FLAGS='-Qunused-arguments' -j2
      - make -C unit CXX='ccache /usr/bin/clang++-8' CXX_FLAGS='-Qunused-arguments' -j2
      - make -C jbmc/src CXX='ccache /usr/bin/clang++-8' CXX_FLAGS='-Qunused-arguments' -j2
      - make -C jbmc/unit CXX='ccache /usr/bin/clang++-8' CXX_FLAGS='-Qunused-arguments' -j2
  post_build:
    commands:
      - make -C unit test
      - make -C regression test CXX='ccache /usr/bin/clang++-8' CXX_FLAGS='-Qunused-arguments'
      - make -C regression/cbmc test-paths-lifo
      - env PATH=$PATH:`pwd`/src/solvers make -C regression/cbmc test-cprover-smt2
      - make -C jbmc/unit test
      - make -C jbmc/regression test
      - echo Build completed on `date`
cache:
  paths:
    - '/var/cache/apt/**/*'
    - '/var/lib/apt/lists/**/*'
    - '/root/.ccache/**/*'
