version: 0.2

env:
  variables:
    # CodeBuild console doesn't display color codes correctly
    TESTPL_COLOR_OUTPUT: 0
    CP_EXTRA_CXXFLAGS: -D_GLIBCXX_DEBUG

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
      - sed -i 's#/archive.ubuntu.com#/us-east-1.ec2.archive.ubuntu.com#g' /etc/apt/sources.list
      - apt-get update -y
      - apt-get install -y flex bison make git libwww-perl patch ccache libc6-dev-i386 jq gdb libxml2-utils python3 python3-pip
      - pip3 install lxml
  build:
    commands:
      - echo Build started on `date`
      - make -C src minisat2-download
      - make -C jbmc/src setup-submodules
      - make -C src CXX="ccache g++" -j2
      - make -C unit CXX="ccache g++" -j2
      - make -C jbmc/src CXX="ccache g++" -j2
      - make -C jbmc/unit CXX="ccache g++" -j2
  post_build:
    commands:
      - make -C unit test
      - echo "Running expected failure tests"
      - make TAGS="[!shouldfail]" -C unit test
      - make -C regression test
      - make -C regression/cbmc test-paths-lifo
      - env PATH=$PATH:`pwd`/src/solvers make -C regression/cbmc test-cprover-smt2
      - make -C jbmc/unit test
      - echo "Running expected failure tests"
      - make TAGS="[!shouldfail]" -C jbmc/unit test
      - make -C jbmc/regression test
      - echo Build completed on `date`
cache:
  paths:
    - '/var/cache/apt/**/*'
    - '/var/lib/apt/lists/**/*'
    - '/root/.ccache/**/*'
