SRC = miniz.cpp \
      # Empty last line
INCLUDES= -I ..

include ../config.inc
include ../common

CLEANFILES = miniz$(OBJEXT)

all: miniz$(OBJEXT)

###############################################################################
