SRC = miniz.cpp

INCLUDES= -I ..

include ../config.inc
include ../common

CLEANFILES = miniz$(OBJEXT)

all: miniz$(OBJEXT)

###############################################################################
