// Auto-generated by scripts/generate_simd_smoke_test.py
// Exercises every modelled SIMD builtin once so the library models are
// type-checked, linked and symex'd. See doc/neon-intrinsic-models.md.

typedef short __gcc_v16hi __attribute__((__vector_size__(32)));
typedef unsigned short __gcc_v16hi_u __attribute__((__vector_size__(32)));
typedef char __gcc_v16qi __attribute__((__vector_size__(16)));
typedef signed char __gcc_v16qi_s __attribute__((__vector_size__(16)));
typedef unsigned char __gcc_v16qi_u __attribute__((__vector_size__(16)));
typedef int __gcc_v16si __attribute__((__vector_size__(64)));
typedef unsigned int __gcc_v16si_u __attribute__((__vector_size__(64)));
typedef long long __gcc_v2di __attribute__((__vector_size__(16)));
typedef unsigned long long __gcc_v2di_u __attribute__((__vector_size__(16)));
typedef short __gcc_v32hi __attribute__((__vector_size__(64)));
typedef unsigned short __gcc_v32hi_u __attribute__((__vector_size__(64)));
typedef char __gcc_v32qi __attribute__((__vector_size__(32)));
typedef signed char __gcc_v32qi_s __attribute__((__vector_size__(32)));
typedef unsigned char __gcc_v32qi_u __attribute__((__vector_size__(32)));
typedef long long __gcc_v4di __attribute__((__vector_size__(32)));
typedef unsigned long long __gcc_v4di_u __attribute__((__vector_size__(32)));
typedef int __gcc_v4si __attribute__((__vector_size__(16)));
typedef unsigned int __gcc_v4si_u __attribute__((__vector_size__(16)));
typedef char __gcc_v64qi __attribute__((__vector_size__(64)));
typedef signed char __gcc_v64qi_s __attribute__((__vector_size__(64)));
typedef unsigned char __gcc_v64qi_u __attribute__((__vector_size__(64)));
typedef long long __gcc_v8di __attribute__((__vector_size__(64)));
typedef unsigned long long __gcc_v8di_u __attribute__((__vector_size__(64)));
typedef short __gcc_v8hi __attribute__((__vector_size__(16)));
typedef unsigned short __gcc_v8hi_u __attribute__((__vector_size__(16)));
typedef int __gcc_v8si __attribute__((__vector_size__(32)));
typedef unsigned int __gcc_v8si_u __attribute__((__vector_size__(32)));

int main(void)
{
  {
    __gcc_v32qi a0 = {0};
    volatile __gcc_v32qi r = __builtin_ia32_pabsb256(a0);
    (void)r;
  }
  {
    __gcc_v16hi a0 = {0};
    volatile __gcc_v16hi r = __builtin_ia32_pabsw256(a0);
    (void)r;
  }
  {
    __gcc_v16qi a0 = {0};
    __gcc_v16qi a1 = {0};
    __gcc_v16qi a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16qi r = __builtin_ia32_paddb128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v32qi a0 = {0};
    __gcc_v32qi a1 = {0};
    __gcc_v32qi a2 = {0};
    unsigned int a3 = {0};
    volatile __gcc_v32qi r = __builtin_ia32_paddb256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v64qi a0 = {0};
    __gcc_v64qi a1 = {0};
    __gcc_v64qi a2 = {0};
    unsigned long long a3 = {0};
    volatile __gcc_v64qi r = __builtin_ia32_paddb512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v8si a0 = {0};
    __gcc_v8si a1 = {0};
    __gcc_v8si a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v8si r = __builtin_ia32_paddd256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v2di a0 = {0};
    __gcc_v2di a1 = {0};
    __gcc_v2di a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v2di r = __builtin_ia32_paddq128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v4di a0 = {0};
    __gcc_v4di a1 = {0};
    __gcc_v4di a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v4di r = __builtin_ia32_paddq256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v8di a0 = {0};
    __gcc_v8di a1 = {0};
    __gcc_v8di a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v8di r = __builtin_ia32_paddq512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v16qi a0 = {0};
    __gcc_v16qi a1 = {0};
    __gcc_v16qi a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16qi r = __builtin_ia32_paddsb128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v32qi a0 = {0};
    __gcc_v32qi a1 = {0};
    volatile __gcc_v32qi r = __builtin_ia32_paddsb256(a0, a1);
    (void)r;
  }
  {
    __gcc_v32qi a0 = {0};
    __gcc_v32qi a1 = {0};
    __gcc_v32qi a2 = {0};
    unsigned int a3 = {0};
    volatile __gcc_v32qi r = __builtin_ia32_paddsb256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v64qi a0 = {0};
    __gcc_v64qi a1 = {0};
    __gcc_v64qi a2 = {0};
    unsigned long long a3 = {0};
    volatile __gcc_v64qi r = __builtin_ia32_paddsb512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v8hi a0 = {0};
    __gcc_v8hi a1 = {0};
    __gcc_v8hi a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v8hi r = __builtin_ia32_paddsw128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v16hi a0 = {0};
    __gcc_v16hi a1 = {0};
    volatile __gcc_v16hi r = __builtin_ia32_paddsw256(a0, a1);
    (void)r;
  }
  {
    __gcc_v16hi a0 = {0};
    __gcc_v16hi a1 = {0};
    __gcc_v16hi a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16hi r = __builtin_ia32_paddsw256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v32hi a0 = {0};
    __gcc_v32hi a1 = {0};
    __gcc_v32hi a2 = {0};
    unsigned int a3 = {0};
    volatile __gcc_v32hi r = __builtin_ia32_paddsw512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v16qi a0 = {0};
    __gcc_v16qi a1 = {0};
    __gcc_v16qi a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16qi r = __builtin_ia32_paddusb128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v32qi a0 = {0};
    __gcc_v32qi a1 = {0};
    volatile __gcc_v32qi r = __builtin_ia32_paddusb256(a0, a1);
    (void)r;
  }
  {
    __gcc_v32qi a0 = {0};
    __gcc_v32qi a1 = {0};
    __gcc_v32qi a2 = {0};
    unsigned int a3 = {0};
    volatile __gcc_v32qi r = __builtin_ia32_paddusb256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v64qi a0 = {0};
    __gcc_v64qi a1 = {0};
    __gcc_v64qi a2 = {0};
    unsigned long long a3 = {0};
    volatile __gcc_v64qi r = __builtin_ia32_paddusb512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v8hi a0 = {0};
    __gcc_v8hi a1 = {0};
    volatile __gcc_v8hi r = __builtin_ia32_paddusw128(a0, a1);
    (void)r;
  }
  {
    __gcc_v8hi a0 = {0};
    __gcc_v8hi a1 = {0};
    __gcc_v8hi a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v8hi r = __builtin_ia32_paddusw128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v16hi a0 = {0};
    __gcc_v16hi a1 = {0};
    volatile __gcc_v16hi r = __builtin_ia32_paddusw256(a0, a1);
    (void)r;
  }
  {
    __gcc_v16hi a0 = {0};
    __gcc_v16hi a1 = {0};
    __gcc_v16hi a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16hi r = __builtin_ia32_paddusw256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v32hi a0 = {0};
    __gcc_v32hi a1 = {0};
    __gcc_v32hi a2 = {0};
    unsigned int a3 = {0};
    volatile __gcc_v32hi r = __builtin_ia32_paddusw512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v8hi a0 = {0};
    __gcc_v8hi a1 = {0};
    __gcc_v8hi a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v8hi r = __builtin_ia32_paddw128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v16hi a0 = {0};
    __gcc_v16hi a1 = {0};
    __gcc_v16hi a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16hi r = __builtin_ia32_paddw256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v32hi a0 = {0};
    __gcc_v32hi a1 = {0};
    __gcc_v32hi a2 = {0};
    unsigned int a3 = {0};
    volatile __gcc_v32hi r = __builtin_ia32_paddw512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v16qi a0 = {0};
    __gcc_v16qi a1 = {0};
    __gcc_v16qi a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16qi r = __builtin_ia32_pavgb128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v32qi a0 = {0};
    __gcc_v32qi a1 = {0};
    volatile __gcc_v32qi r = __builtin_ia32_pavgb256(a0, a1);
    (void)r;
  }
  {
    __gcc_v32qi a0 = {0};
    __gcc_v32qi a1 = {0};
    __gcc_v32qi a2 = {0};
    unsigned int a3 = {0};
    volatile __gcc_v32qi r = __builtin_ia32_pavgb256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v64qi a0 = {0};
    __gcc_v64qi a1 = {0};
    __gcc_v64qi a2 = {0};
    unsigned long long a3 = {0};
    volatile __gcc_v64qi r = __builtin_ia32_pavgb512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v8hi a0 = {0};
    __gcc_v8hi a1 = {0};
    __gcc_v8hi a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v8hi r = __builtin_ia32_pavgw128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v16hi a0 = {0};
    __gcc_v16hi a1 = {0};
    volatile __gcc_v16hi r = __builtin_ia32_pavgw256(a0, a1);
    (void)r;
  }
  {
    __gcc_v16hi a0 = {0};
    __gcc_v16hi a1 = {0};
    __gcc_v16hi a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16hi r = __builtin_ia32_pavgw256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v32hi a0 = {0};
    __gcc_v32hi a1 = {0};
    __gcc_v32hi a2 = {0};
    unsigned int a3 = {0};
    volatile __gcc_v32hi r = __builtin_ia32_pavgw512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v16qi a0 = {0};
    __gcc_v16qi a1 = {0};
    __gcc_v16qi a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16qi r = __builtin_ia32_pmaxsb128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v32qi a0 = {0};
    __gcc_v32qi a1 = {0};
    volatile __gcc_v32qi r = __builtin_ia32_pmaxsb256(a0, a1);
    (void)r;
  }
  {
    __gcc_v32qi a0 = {0};
    __gcc_v32qi a1 = {0};
    __gcc_v32qi a2 = {0};
    unsigned int a3 = {0};
    volatile __gcc_v32qi r = __builtin_ia32_pmaxsb256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v64qi a0 = {0};
    __gcc_v64qi a1 = {0};
    __gcc_v64qi a2 = {0};
    unsigned long long a3 = {0};
    volatile __gcc_v64qi r = __builtin_ia32_pmaxsb512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v4si a0 = {0};
    __gcc_v4si a1 = {0};
    __gcc_v4si a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v4si r = __builtin_ia32_pmaxsd128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v8si a0 = {0};
    __gcc_v8si a1 = {0};
    volatile __gcc_v8si r = __builtin_ia32_pmaxsd256(a0, a1);
    (void)r;
  }
  {
    __gcc_v8si a0 = {0};
    __gcc_v8si a1 = {0};
    __gcc_v8si a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v8si r = __builtin_ia32_pmaxsd256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v16si a0 = {0};
    __gcc_v16si a1 = {0};
    __gcc_v16si a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16si r = __builtin_ia32_pmaxsd512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v8hi a0 = {0};
    __gcc_v8hi a1 = {0};
    __gcc_v8hi a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v8hi r = __builtin_ia32_pmaxsw128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v16hi a0 = {0};
    __gcc_v16hi a1 = {0};
    volatile __gcc_v16hi r = __builtin_ia32_pmaxsw256(a0, a1);
    (void)r;
  }
  {
    __gcc_v16hi a0 = {0};
    __gcc_v16hi a1 = {0};
    __gcc_v16hi a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16hi r = __builtin_ia32_pmaxsw256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v32hi a0 = {0};
    __gcc_v32hi a1 = {0};
    __gcc_v32hi a2 = {0};
    unsigned int a3 = {0};
    volatile __gcc_v32hi r = __builtin_ia32_pmaxsw512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v16qi a0 = {0};
    __gcc_v16qi a1 = {0};
    __gcc_v16qi a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16qi r = __builtin_ia32_pmaxub128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v32qi a0 = {0};
    __gcc_v32qi a1 = {0};
    volatile __gcc_v32qi r = __builtin_ia32_pmaxub256(a0, a1);
    (void)r;
  }
  {
    __gcc_v32qi a0 = {0};
    __gcc_v32qi a1 = {0};
    __gcc_v32qi a2 = {0};
    unsigned int a3 = {0};
    volatile __gcc_v32qi r = __builtin_ia32_pmaxub256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v64qi a0 = {0};
    __gcc_v64qi a1 = {0};
    __gcc_v64qi a2 = {0};
    unsigned long long a3 = {0};
    volatile __gcc_v64qi r = __builtin_ia32_pmaxub512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v4si a0 = {0};
    __gcc_v4si a1 = {0};
    __gcc_v4si a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v4si r = __builtin_ia32_pmaxud128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v8si a0 = {0};
    __gcc_v8si a1 = {0};
    __gcc_v8si a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v8si r = __builtin_ia32_pmaxud256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v16si a0 = {0};
    __gcc_v16si a1 = {0};
    __gcc_v16si a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16si r = __builtin_ia32_pmaxud512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v8hi a0 = {0};
    __gcc_v8hi a1 = {0};
    __gcc_v8hi a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v8hi r = __builtin_ia32_pmaxuw128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v16hi a0 = {0};
    __gcc_v16hi a1 = {0};
    volatile __gcc_v16hi r = __builtin_ia32_pmaxuw256(a0, a1);
    (void)r;
  }
  {
    __gcc_v16hi a0 = {0};
    __gcc_v16hi a1 = {0};
    __gcc_v16hi a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16hi r = __builtin_ia32_pmaxuw256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v32hi a0 = {0};
    __gcc_v32hi a1 = {0};
    __gcc_v32hi a2 = {0};
    unsigned int a3 = {0};
    volatile __gcc_v32hi r = __builtin_ia32_pmaxuw512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v16qi a0 = {0};
    __gcc_v16qi a1 = {0};
    __gcc_v16qi a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16qi r = __builtin_ia32_pminsb128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v32qi a0 = {0};
    __gcc_v32qi a1 = {0};
    volatile __gcc_v32qi r = __builtin_ia32_pminsb256(a0, a1);
    (void)r;
  }
  {
    __gcc_v32qi a0 = {0};
    __gcc_v32qi a1 = {0};
    __gcc_v32qi a2 = {0};
    unsigned int a3 = {0};
    volatile __gcc_v32qi r = __builtin_ia32_pminsb256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v64qi a0 = {0};
    __gcc_v64qi a1 = {0};
    __gcc_v64qi a2 = {0};
    unsigned long long a3 = {0};
    volatile __gcc_v64qi r = __builtin_ia32_pminsb512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v4si a0 = {0};
    __gcc_v4si a1 = {0};
    __gcc_v4si a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v4si r = __builtin_ia32_pminsd128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v8si a0 = {0};
    __gcc_v8si a1 = {0};
    volatile __gcc_v8si r = __builtin_ia32_pminsd256(a0, a1);
    (void)r;
  }
  {
    __gcc_v8si a0 = {0};
    __gcc_v8si a1 = {0};
    __gcc_v8si a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v8si r = __builtin_ia32_pminsd256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v16si a0 = {0};
    __gcc_v16si a1 = {0};
    __gcc_v16si a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16si r = __builtin_ia32_pminsd512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v8hi a0 = {0};
    __gcc_v8hi a1 = {0};
    __gcc_v8hi a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v8hi r = __builtin_ia32_pminsw128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v16hi a0 = {0};
    __gcc_v16hi a1 = {0};
    volatile __gcc_v16hi r = __builtin_ia32_pminsw256(a0, a1);
    (void)r;
  }
  {
    __gcc_v16hi a0 = {0};
    __gcc_v16hi a1 = {0};
    __gcc_v16hi a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16hi r = __builtin_ia32_pminsw256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v32hi a0 = {0};
    __gcc_v32hi a1 = {0};
    __gcc_v32hi a2 = {0};
    unsigned int a3 = {0};
    volatile __gcc_v32hi r = __builtin_ia32_pminsw512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v16qi a0 = {0};
    __gcc_v16qi a1 = {0};
    __gcc_v16qi a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16qi r = __builtin_ia32_pminub128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v32qi a0 = {0};
    __gcc_v32qi a1 = {0};
    volatile __gcc_v32qi r = __builtin_ia32_pminub256(a0, a1);
    (void)r;
  }
  {
    __gcc_v32qi a0 = {0};
    __gcc_v32qi a1 = {0};
    __gcc_v32qi a2 = {0};
    unsigned int a3 = {0};
    volatile __gcc_v32qi r = __builtin_ia32_pminub256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v64qi a0 = {0};
    __gcc_v64qi a1 = {0};
    __gcc_v64qi a2 = {0};
    unsigned long long a3 = {0};
    volatile __gcc_v64qi r = __builtin_ia32_pminub512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v4si a0 = {0};
    __gcc_v4si a1 = {0};
    __gcc_v4si a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v4si r = __builtin_ia32_pminud128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v8si a0 = {0};
    __gcc_v8si a1 = {0};
    volatile __gcc_v8si r = __builtin_ia32_pminud256(a0, a1);
    (void)r;
  }
  {
    __gcc_v8si a0 = {0};
    __gcc_v8si a1 = {0};
    __gcc_v8si a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v8si r = __builtin_ia32_pminud256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v16si a0 = {0};
    __gcc_v16si a1 = {0};
    __gcc_v16si a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16si r = __builtin_ia32_pminud512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v8hi a0 = {0};
    __gcc_v8hi a1 = {0};
    __gcc_v8hi a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v8hi r = __builtin_ia32_pminuw128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v16hi a0 = {0};
    __gcc_v16hi a1 = {0};
    volatile __gcc_v16hi r = __builtin_ia32_pminuw256(a0, a1);
    (void)r;
  }
  {
    __gcc_v16hi a0 = {0};
    __gcc_v16hi a1 = {0};
    __gcc_v16hi a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16hi r = __builtin_ia32_pminuw256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v32hi a0 = {0};
    __gcc_v32hi a1 = {0};
    __gcc_v32hi a2 = {0};
    unsigned int a3 = {0};
    volatile __gcc_v32hi r = __builtin_ia32_pminuw512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v4si a0 = {0};
    __gcc_v4si a1 = {0};
    __gcc_v4si a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v4si r = __builtin_ia32_pmulld128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v8si a0 = {0};
    __gcc_v8si a1 = {0};
    volatile __gcc_v8si r = __builtin_ia32_pmulld256(a0, a1);
    (void)r;
  }
  {
    __gcc_v8si a0 = {0};
    __gcc_v8si a1 = {0};
    __gcc_v8si a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v8si r = __builtin_ia32_pmulld256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v16si a0 = {0};
    __gcc_v16si a1 = {0};
    __gcc_v16si a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16si r = __builtin_ia32_pmulld512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v8hi a0 = {0};
    __gcc_v8hi a1 = {0};
    __gcc_v8hi a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v8hi r = __builtin_ia32_pmullw128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v16hi a0 = {0};
    __gcc_v16hi a1 = {0};
    volatile __gcc_v16hi r = __builtin_ia32_pmullw256(a0, a1);
    (void)r;
  }
  {
    __gcc_v16hi a0 = {0};
    __gcc_v16hi a1 = {0};
    __gcc_v16hi a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16hi r = __builtin_ia32_pmullw256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v32hi a0 = {0};
    __gcc_v32hi a1 = {0};
    __gcc_v32hi a2 = {0};
    unsigned int a3 = {0};
    volatile __gcc_v32hi r = __builtin_ia32_pmullw512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v4si a0 = {0};
    volatile __gcc_v4si r = __builtin_ia32_pslldi128(a0, 1);
    (void)r;
  }
  {
    __gcc_v8si a0 = {0};
    volatile __gcc_v8si r = __builtin_ia32_pslldi256(a0, 1);
    (void)r;
  }
  {
    __gcc_v2di a0 = {0};
    volatile __gcc_v2di r = __builtin_ia32_psllqi128(a0, 1);
    (void)r;
  }
  {
    __gcc_v4di a0 = {0};
    volatile __gcc_v4di r = __builtin_ia32_psllqi256(a0, 1);
    (void)r;
  }
  {
    __gcc_v16hi a0 = {0};
    volatile __gcc_v16hi r = __builtin_ia32_psllwi256(a0, 1);
    (void)r;
  }
  {
    __gcc_v8si a0 = {0};
    volatile __gcc_v8si r = __builtin_ia32_psradi256(a0, 1);
    (void)r;
  }
  {
    __gcc_v8hi a0 = {0};
    volatile __gcc_v8hi r = __builtin_ia32_psrawi128(a0, 1);
    (void)r;
  }
  {
    __gcc_v16hi a0 = {0};
    volatile __gcc_v16hi r = __builtin_ia32_psrawi256(a0, 1);
    (void)r;
  }
  {
    __gcc_v4si a0 = {0};
    volatile __gcc_v4si r = __builtin_ia32_psrldi128(a0, 1);
    (void)r;
  }
  {
    __gcc_v8si a0 = {0};
    volatile __gcc_v8si r = __builtin_ia32_psrldi256(a0, 1);
    (void)r;
  }
  {
    __gcc_v2di a0 = {0};
    volatile __gcc_v2di r = __builtin_ia32_psrlqi128(a0, 1);
    (void)r;
  }
  {
    __gcc_v4di a0 = {0};
    volatile __gcc_v4di r = __builtin_ia32_psrlqi256(a0, 1);
    (void)r;
  }
  {
    __gcc_v16hi a0 = {0};
    volatile __gcc_v16hi r = __builtin_ia32_psrlwi256(a0, 1);
    (void)r;
  }
  {
    __gcc_v16qi a0 = {0};
    __gcc_v16qi a1 = {0};
    __gcc_v16qi a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16qi r = __builtin_ia32_psubb128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v32qi a0 = {0};
    __gcc_v32qi a1 = {0};
    __gcc_v32qi a2 = {0};
    unsigned int a3 = {0};
    volatile __gcc_v32qi r = __builtin_ia32_psubb256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v64qi a0 = {0};
    __gcc_v64qi a1 = {0};
    __gcc_v64qi a2 = {0};
    unsigned long long a3 = {0};
    volatile __gcc_v64qi r = __builtin_ia32_psubb512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v4si a0 = {0};
    __gcc_v4si a1 = {0};
    __gcc_v4si a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v4si r = __builtin_ia32_psubd128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v8si a0 = {0};
    __gcc_v8si a1 = {0};
    __gcc_v8si a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v8si r = __builtin_ia32_psubd256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v16si a0 = {0};
    __gcc_v16si a1 = {0};
    __gcc_v16si a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16si r = __builtin_ia32_psubd512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v2di a0 = {0};
    __gcc_v2di a1 = {0};
    __gcc_v2di a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v2di r = __builtin_ia32_psubq128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v4di a0 = {0};
    __gcc_v4di a1 = {0};
    __gcc_v4di a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v4di r = __builtin_ia32_psubq256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v8di a0 = {0};
    __gcc_v8di a1 = {0};
    __gcc_v8di a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v8di r = __builtin_ia32_psubq512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v16qi a0 = {0};
    __gcc_v16qi a1 = {0};
    volatile __gcc_v16qi r = __builtin_ia32_psubsb128(a0, a1);
    (void)r;
  }
  {
    __gcc_v16qi a0 = {0};
    __gcc_v16qi a1 = {0};
    __gcc_v16qi a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16qi r = __builtin_ia32_psubsb128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v32qi a0 = {0};
    __gcc_v32qi a1 = {0};
    volatile __gcc_v32qi r = __builtin_ia32_psubsb256(a0, a1);
    (void)r;
  }
  {
    __gcc_v32qi a0 = {0};
    __gcc_v32qi a1 = {0};
    __gcc_v32qi a2 = {0};
    unsigned int a3 = {0};
    volatile __gcc_v32qi r = __builtin_ia32_psubsb256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v64qi a0 = {0};
    __gcc_v64qi a1 = {0};
    __gcc_v64qi a2 = {0};
    unsigned long long a3 = {0};
    volatile __gcc_v64qi r = __builtin_ia32_psubsb512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v8hi a0 = {0};
    __gcc_v8hi a1 = {0};
    __gcc_v8hi a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v8hi r = __builtin_ia32_psubsw128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v16hi a0 = {0};
    __gcc_v16hi a1 = {0};
    volatile __gcc_v16hi r = __builtin_ia32_psubsw256(a0, a1);
    (void)r;
  }
  {
    __gcc_v16hi a0 = {0};
    __gcc_v16hi a1 = {0};
    __gcc_v16hi a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16hi r = __builtin_ia32_psubsw256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v32hi a0 = {0};
    __gcc_v32hi a1 = {0};
    __gcc_v32hi a2 = {0};
    unsigned int a3 = {0};
    volatile __gcc_v32hi r = __builtin_ia32_psubsw512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v16qi a0 = {0};
    __gcc_v16qi a1 = {0};
    __gcc_v16qi a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16qi r = __builtin_ia32_psubusb128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v32qi a0 = {0};
    __gcc_v32qi a1 = {0};
    volatile __gcc_v32qi r = __builtin_ia32_psubusb256(a0, a1);
    (void)r;
  }
  {
    __gcc_v32qi a0 = {0};
    __gcc_v32qi a1 = {0};
    __gcc_v32qi a2 = {0};
    unsigned int a3 = {0};
    volatile __gcc_v32qi r = __builtin_ia32_psubusb256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v64qi a0 = {0};
    __gcc_v64qi a1 = {0};
    __gcc_v64qi a2 = {0};
    unsigned long long a3 = {0};
    volatile __gcc_v64qi r = __builtin_ia32_psubusb512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v8hi a0 = {0};
    __gcc_v8hi a1 = {0};
    __gcc_v8hi a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v8hi r = __builtin_ia32_psubusw128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v16hi a0 = {0};
    __gcc_v16hi a1 = {0};
    volatile __gcc_v16hi r = __builtin_ia32_psubusw256(a0, a1);
    (void)r;
  }
  {
    __gcc_v16hi a0 = {0};
    __gcc_v16hi a1 = {0};
    __gcc_v16hi a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16hi r = __builtin_ia32_psubusw256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v32hi a0 = {0};
    __gcc_v32hi a1 = {0};
    __gcc_v32hi a2 = {0};
    unsigned int a3 = {0};
    volatile __gcc_v32hi r = __builtin_ia32_psubusw512_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v8hi a0 = {0};
    __gcc_v8hi a1 = {0};
    __gcc_v8hi a2 = {0};
    unsigned char a3 = {0};
    volatile __gcc_v8hi r = __builtin_ia32_psubw128_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v16hi a0 = {0};
    __gcc_v16hi a1 = {0};
    __gcc_v16hi a2 = {0};
    unsigned short a3 = {0};
    volatile __gcc_v16hi r = __builtin_ia32_psubw256_mask(a0, a1, a2, a3);
    (void)r;
  }
  {
    __gcc_v32hi a0 = {0};
    __gcc_v32hi a1 = {0};
    __gcc_v32hi a2 = {0};
    unsigned int a3 = {0};
    volatile __gcc_v32hi r = __builtin_ia32_psubw512_mask(a0, a1, a2, a3);
    (void)r;
  }
  __CPROVER_assert(1, "SIMD model smoke test");
  return 0;
}
