// clang-format off
int __builtin_abs(int);
double __builtin_acos(double);
float __builtin_acosf(float);
double __builtin_acosh(double);
float __builtin_acoshf(float);
long double __builtin_acoshl(long double);
long double __builtin_acosl(long double);
_Bool __builtin_add_overflow();
_Bool __builtin_add_overflow_p();
double __builtin_asin(double);
float __builtin_asinf(float);
double __builtin_asinh(double);
float __builtin_asinhf(float);
long double __builtin_asinhl(long double);
long double __builtin_asinl(long double);
double __builtin_atan(double);
double __builtin_atan2(double, double);
float __builtin_atan2f(float, float);
long double __builtin_atan2l(long double, long double);
float __builtin_atanf(float);
double __builtin_atanh(double);
float __builtin_atanhf(float);
long double __builtin_atanhl(long double);
long double __builtin_atanl(long double);
double __builtin_cabs(double _Complex);
float __builtin_cabsf(float _Complex);
long double __builtin_cabsl(long double _Complex);
double _Complex __builtin_cacos(double _Complex);
float _Complex __builtin_cacosf(float _Complex);
double _Complex __builtin_cacosh(double _Complex);
float _Complex __builtin_cacoshf(float _Complex);
long double _Complex __builtin_cacoshl(long double _Complex);
long double _Complex __builtin_cacosl(long double _Complex);
double __builtin_carg(double _Complex);
float __builtin_cargf(float _Complex);
long double __builtin_cargl(long double _Complex);
double _Complex __builtin_casin(double _Complex);
float _Complex __builtin_casinf(float _Complex);
double _Complex __builtin_casinh(double _Complex);
float _Complex __builtin_casinhf(float _Complex);
long double _Complex __builtin_casinhl(long double _Complex);
long double _Complex __builtin_casinl(long double _Complex);
double _Complex __builtin_catan(double _Complex);
float _Complex __builtin_catanf(float _Complex);
double _Complex __builtin_catanh(double _Complex);
float _Complex __builtin_catanhf(float _Complex);
long double _Complex __builtin_catanhl(long double _Complex);
long double _Complex __builtin_catanl(long double _Complex);
double __builtin_cbrt(double);
float __builtin_cbrtf(float);
long double __builtin_cbrtl(long double);
double _Complex __builtin_ccos(double _Complex);
float _Complex __builtin_ccosf(float _Complex);
double _Complex __builtin_ccosh(double _Complex);
float _Complex __builtin_ccoshf(float _Complex);
long double _Complex __builtin_ccoshl(long double _Complex);
long double _Complex __builtin_ccosl(long double _Complex);
double __builtin_ceil(double);
float __builtin_ceilf(float);
long double __builtin_ceill(long double);
double _Complex __builtin_cexp(double _Complex);
float _Complex __builtin_cexpf(float _Complex);
double _Complex __builtin_cexpi(double);
float _Complex __builtin_cexpif(float);
long double _Complex __builtin_cexpil(long double);
long double _Complex __builtin_cexpl(long double _Complex);
double __builtin_cimag(double _Complex);
float __builtin_cimagf(float _Complex);
long double __builtin_cimagl(long double _Complex);
double _Complex __builtin_clog(double _Complex);
double _Complex __builtin_clog10(double _Complex);
float _Complex __builtin_clog10f(float _Complex);
long double _Complex __builtin_clog10l(long double _Complex);
float _Complex __builtin_clogf(float _Complex);
long double _Complex __builtin_clogl(long double _Complex);
double _Complex __builtin_conj(double _Complex);
float _Complex __builtin_conjf(float _Complex);
long double _Complex __builtin_conjl(long double _Complex);
double __builtin_copysign(double, double);
float __builtin_copysignf(float, float);
long double __builtin_copysignl(long double, long double);
double __builtin_cos(double);
float __builtin_cosf(float);
double __builtin_cosh(double);
float __builtin_coshf(float);
long double __builtin_coshl(long double);
long double __builtin_cosl(long double);
double _Complex __builtin_cpow(double _Complex, double _Complex);
float _Complex __builtin_cpowf(float _Complex, float _Complex);
long double _Complex __builtin_cpowl(long double _Complex, long double _Complex);
double _Complex __builtin_cproj(double _Complex);
float _Complex __builtin_cprojf(float _Complex);
long double _Complex __builtin_cprojl(long double _Complex);
double __builtin_creal(double _Complex);
float __builtin_crealf(float _Complex);
long double __builtin_creall(long double _Complex);
double _Complex __builtin_csin(double _Complex);
float _Complex __builtin_csinf(float _Complex);
double _Complex __builtin_csinh(double _Complex);
float _Complex __builtin_csinhf(float _Complex);
long double _Complex __builtin_csinhl(long double _Complex);
long double _Complex __builtin_csinl(long double _Complex);
double _Complex __builtin_csqrt(double _Complex);
float _Complex __builtin_csqrtf(float _Complex);
long double _Complex __builtin_csqrtl(long double _Complex);
double _Complex __builtin_ctan(double _Complex);
float _Complex __builtin_ctanf(float _Complex);
double _Complex __builtin_ctanh(double _Complex);
float _Complex __builtin_ctanhf(float _Complex);
long double _Complex __builtin_ctanhl(long double _Complex);
long double _Complex __builtin_ctanl(long double _Complex);
int __builtin_ctz(unsigned);
int __builtin_ctzl(unsigned long);
int __builtin_ctzll(unsigned long long);
double __builtin_drem(double, double);
float __builtin_dremf(float, float);
long double __builtin_dreml(long double, long double);
double __builtin_erf(double);
double __builtin_erfc(double);
float __builtin_erfcf(float);
long double __builtin_erfcl(long double);
float __builtin_erff(float);
long double __builtin_erfl(long double);
double __builtin_exp(double);
double __builtin_exp10(double);
float __builtin_exp10f(float);
long double __builtin_exp10l(long double);
double __builtin_exp2(double);
float __builtin_exp2f(float);
long double __builtin_exp2l(long double);
float __builtin_expf(float);
long double __builtin_expl(long double);
double __builtin_expm1(double);
float __builtin_expm1f(float);
long double __builtin_expm1l(long double);
double __builtin_fabs(double);
float __builtin_fabsf(float);
long double __builtin_fabsl(long double);
double __builtin_fdim(double, double);
float __builtin_fdimf(float, float);
long double __builtin_fdiml(long double, long double);
int __builtin_finite(double);
int __builtin_finitef(float);
int __builtin_finitel(long double);
double __builtin_floor(double);
float __builtin_floorf(float);
long double __builtin_floorl(long double);
double __builtin_fma(double, double, double);
float __builtin_fmaf(float, float, float);
long double __builtin_fmal(long double, long double, long double);
double __builtin_fmax(double, double);
float __builtin_fmaxf(float, float);
long double __builtin_fmaxl(long double, long double);
double __builtin_fmin(double, double);
float __builtin_fminf(float, float);
long double __builtin_fminl(long double, long double);
double __builtin_fmod(double, double);
float __builtin_fmodf(float, float);
long double __builtin_fmodl(long double, long double);
int __builtin_fpclassify(int, int, int, int, int, ...);
double __builtin_frexp(double, int*);
float __builtin_frexpf(float, int*);
long double __builtin_frexpl(long double, int*);
double __builtin_gamma(double);
double __builtin_gamma_r(double, int*);
float __builtin_gammaf(float);
float __builtin_gammaf_r(float, int*);
long double __builtin_gammal(long double);
long double __builtin_gammal_r(long double, int*);
double __builtin_huge_val(void);
float __builtin_huge_valf(void);
long double __builtin_huge_vall(void);
double __builtin_hypot(double, double);
float __builtin_hypotf(float, float);
long double __builtin_hypotl(long double, long double);
int __builtin_iceil(double);
int __builtin_iceilf(float);
int __builtin_iceill(long double);
int __builtin_ifloor(double);
int __builtin_ifloorf(float);
int __builtin_ifloorl(long double);
int __builtin_ilogb(double);
int __builtin_ilogbf(float);
int __builtin_ilogbl(long double);
double __builtin_inf(void);
float __builtin_inff(void);
long double __builtin_infl(void);
int __builtin_irint(double);
int __builtin_irintf(float);
int __builtin_irintl(long double);
int __builtin_iround(double);
int __builtin_iroundf(float);
int __builtin_iroundl(long double);
int __builtin_isfinite();
int __builtin_isgreater();
int __builtin_isgreaterequal();
int __builtin_isinf(double);
int __builtin_isinf_sign();
int __builtin_isinff(float);
int __builtin_isinfl(long double);
int __builtin_isless();
int __builtin_islessequal();
int __builtin_islessgreater();
int __builtin_isnan(double);
int __builtin_isnanf(float);
int __builtin_isnanl(long double);
int __builtin_isnormal();
int __builtin_isunordered();
double __builtin_j0(double);
float __builtin_j0f(float);
long double __builtin_j0l(long double);
double __builtin_j1(double);
float __builtin_j1f(float);
long double __builtin_j1l(long double);
double __builtin_jn(int, double);
float __builtin_jnf(int, float);
long double __builtin_jnl(int, long double);
long __builtin_labs(long);
long __builtin_lceil(double);
long __builtin_lceilf(float);
long __builtin_lceill(long double);
double __builtin_ldexp(double, int);
float __builtin_ldexpf(float, int);
long double __builtin_ldexpl(long double, int);
long __builtin_lfloor(double);
long __builtin_lfloorf(float);
long __builtin_lfloorl(long double);
double __builtin_lgamma(double);
double __builtin_lgamma_r(double, int*);
float __builtin_lgammaf(float);
float __builtin_lgammaf_r(float, int*);
long double __builtin_lgammal(long double);
long double __builtin_lgammal_r(long double, int*);
long long __builtin_llabs(long long);
long long __builtin_llceil(double);
long long __builtin_llceilf(float);
long long __builtin_llceill(long double);
long long __builtin_llfloor(double);
long long __builtin_llfloorf(float);
long long __builtin_llfloorl(long double);
long long __builtin_llrint(double);
long long __builtin_llrintf(float);
long long __builtin_llrintl(long double);
long long __builtin_llround(double);
long long __builtin_llroundf(float);
long long __builtin_llroundl(long double);
double __builtin_log(double);
double __builtin_log10(double);
float __builtin_log10f(float);
long double __builtin_log10l(long double);
double __builtin_log1p(double);
float __builtin_log1pf(float);
long double __builtin_log1pl(long double);
double __builtin_log2(double);
float __builtin_log2f(float);
long double __builtin_log2l(long double);
double __builtin_logb(double);
float __builtin_logbf(float);
long double __builtin_logbl(long double);
float __builtin_logf(float);
long double __builtin_logl(long double);
long __builtin_lrint(double);
long __builtin_lrintf(float);
long __builtin_lrintl(long double);
long __builtin_lround(double);
long __builtin_lroundf(float);
long __builtin_lroundl(long double);
double __builtin_modf(double, double*);
float __builtin_modff(float, float*);
long double __builtin_modfl(long double, long double*);
_Bool __builtin_mul_overflow();
_Bool __builtin_mul_overflow_p();
double __builtin_nan(const char*);
float __builtin_nanf(const char*);
long double __builtin_nanl(const char*);
double __builtin_nans(const char*);
float __builtin_nansf(const char*);
long double __builtin_nansl(const char*);
double __builtin_nearbyint(double);
float __builtin_nearbyintf(float);
long double __builtin_nearbyintl(long double);
double __builtin_nextafter(double, double);
float __builtin_nextafterf(float, float);
long double __builtin_nextafterl(long double, long double);
double __builtin_nexttoward(double, long double);
float __builtin_nexttowardf(float, long double);
long double __builtin_nexttowardl(long double, long double);
int __builtin_parity(unsigned);
int __builtin_parityl(unsigned long);
int __builtin_parityll(unsigned long long);
double __builtin_pow(double, double);
double __builtin_pow10(double);
float __builtin_pow10f(float);
long double __builtin_pow10l(long double);
float __builtin_powf(float, float);
double __builtin_powi(double, int);
float __builtin_powif(float, int);
long double __builtin_powil(long double, int);
long double __builtin_powl(long double, long double);
double __builtin_remainder(double, double);
float __builtin_remainderf(float, float);
long double __builtin_remainderl(long double, long double);
double __builtin_remquo(double, double, int*);
float __builtin_remquof(float, float, int*);
long double __builtin_remquol(long double, long double, int*);
double __builtin_rint(double);
float __builtin_rintf(float);
long double __builtin_rintl(long double);
double __builtin_round(double);
float __builtin_roundf(float);
long double __builtin_roundl(long double);
_Bool __builtin_sadd_overflow(int, int, int*);
_Bool __builtin_saddl_overflow(long, long, long*);
_Bool __builtin_saddll_overflow(long long, long long, long long*);
double __builtin_scalb(double, double);
float __builtin_scalbf(float, float);
long double __builtin_scalbl(long double, long double);
double __builtin_scalbln(double, long);
float __builtin_scalblnf(float, long);
long double __builtin_scalblnl(long double, long);
double __builtin_scalbn(double, int);
float __builtin_scalbnf(float, int);
long double __builtin_scalbnl(long double, int);
int __builtin_signbit(double);
int __builtin_signbitf(float);
int __builtin_signbitl(long double);
double __builtin_significand(double);
float __builtin_significandf(float);
long double __builtin_significandl(long double);
double __builtin_sin(double);
void __builtin_sincos(double, double*, double*);
void __builtin_sincosf(float, float*, float*);
void __builtin_sincosl(long double, long double*, long double*);
float __builtin_sinf(float);
double __builtin_sinh(double);
float __builtin_sinhf(float);
long double __builtin_sinhl(long double);
long double __builtin_sinl(long double);
_Bool __builtin_smul_overflow(int, int, int*);
_Bool __builtin_smull_overflow(long, long, long*);
_Bool __builtin_smulll_overflow(long long, long long, long long*);
double __builtin_sqrt(double);
float __builtin_sqrtf(float);
long double __builtin_sqrtl(long double);
_Bool __builtin_ssub_overflow(int, int, int*);
_Bool __builtin_ssubl_overflow(long, long, long*);
_Bool __builtin_ssubll_overflow(long long, long long, long long*);
_Bool __builtin_sub_overflow();
_Bool __builtin_sub_overflow_p();
double __builtin_tan(double);
float __builtin_tanf(float);
double __builtin_tanh(double);
float __builtin_tanhf(float);
long double __builtin_tanhl(long double);
long double __builtin_tanl(long double);
double __builtin_tgamma(double);
float __builtin_tgammaf(float);
long double __builtin_tgammal(long double);
double __builtin_trunc(double);
float __builtin_truncf(float);
long double __builtin_truncl(long double);
_Bool __builtin_uadd_overflow(unsigned, unsigned, unsigned*);
_Bool __builtin_uaddl_overflow(unsigned long, unsigned long, unsigned long*);
_Bool __builtin_uaddll_overflow(unsigned long long, unsigned long long, unsigned long long*);
_Bool __builtin_umul_overflow(unsigned, unsigned, unsigned*);
_Bool __builtin_umull_overflow(unsigned long, unsigned long, unsigned long*);
_Bool __builtin_umulll_overflow(unsigned long long, unsigned long long, unsigned long long*);
_Bool __builtin_usub_overflow(unsigned, unsigned, unsigned*);
_Bool __builtin_usubl_overflow(unsigned long, unsigned long, unsigned long*);
_Bool __builtin_usubll_overflow(unsigned long long, unsigned long long, unsigned long long*);
double __builtin_y0(double);
float __builtin_y0f(float);
long double __builtin_y0l(long double);
double __builtin_y1(double);
float __builtin_y1f(float);
long double __builtin_y1l(long double);
double __builtin_yn(int, double);
float __builtin_ynf(int, float);
long double __builtin_ynl(int, long double);
// clang-format on
