// clang-format off
int __builtin_omp_get_thread_num();
int __builtin_omp_get_num_threads();
int __builtin_omp_get_team_num();
int __builtin_omp_get_num_teams();
void __builtin_GOMP_atomic_start();
void __builtin_GOMP_atomic_end();
void __builtin_GOMP_barrier();
_Bool __builtin_GOMP_barrier_cancel();
void __builtin_GOMP_taskwait();
void __builtin_GOMP_taskyield();
void __builtin_GOMP_taskgroup_start();
void __builtin_GOMP_taskgroup_end();
_Bool __builtin_GOMP_cancel(int, _Bool);
_Bool __builtin_GOMP_cancellation_point(int);
void __builtin_GOMP_critical_start();
void __builtin_GOMP_critical_end();
void __builtin_GOMP_critical_name_start(void**);
void __builtin_GOMP_critical_name_end(void**);
_Bool __builtin_GOMP_loop_static_start(long, long, long, long, long*, long*);
_Bool __builtin_GOMP_loop_dynamic_start(long, long, long, long, long*, long*);
_Bool __builtin_GOMP_loop_guided_start(long, long, long, long, long*, long*);
_Bool __builtin_GOMP_loop_runtime_start(long, long, long, long*, long*);
_Bool __builtin_GOMP_loop_nonmonotonic_dynamic_start(long, long, long, long, long*, long*);
_Bool __builtin_GOMP_loop_nonmonotonic_guided_start(long, long, long, long, long*, long*);
_Bool __builtin_GOMP_loop_ordered_static_start(long, long, long, long, long*, long*);
_Bool __builtin_GOMP_loop_ordered_dynamic_start(long, long, long, long, long*, long*);
_Bool __builtin_GOMP_loop_ordered_guided_start(long, long, long, long, long*, long*);
_Bool __builtin_GOMP_loop_ordered_runtime_start(long, long, long, long*, long*);
_Bool __builtin_GOMP_loop_doacross_static_start(unsigned, long*, long, long*, long*);
_Bool __builtin_GOMP_loop_doacross_dynamic_start(unsigned, long*, long, long*, long*);
_Bool __builtin_GOMP_loop_doacross_guided_start(unsigned, long*, long, long*, long*);
_Bool __builtin_GOMP_loop_doacross_runtime_start(unsigned, long*, long*, long*);
_Bool __builtin_GOMP_loop_static_next(long*, long*);
_Bool __builtin_GOMP_loop_dynamic_next(long*, long*);
_Bool __builtin_GOMP_loop_guided_next(long*, long*);
_Bool __builtin_GOMP_loop_runtime_next(long*, long*);
_Bool __builtin_GOMP_loop_nonmonotonic_dynamic_next(long*, long*);
_Bool __builtin_GOMP_loop_nonmonotonic_guided_next(long*, long*);
_Bool __builtin_GOMP_loop_ordered_static_next(long*, long*);
_Bool __builtin_GOMP_loop_ordered_dynamic_next(long*, long*);
_Bool __builtin_GOMP_loop_ordered_guided_next(long*, long*);
_Bool __builtin_GOMP_loop_ordered_runtime_next(long*, long*);
_Bool __builtin_GOMP_loop_ull_static_start(_Bool, unsigned long long, unsigned long long, unsigned long long, unsigned long long, unsigned long long*, unsigned long long*);
_Bool __builtin_GOMP_loop_ull_dynamic_start(_Bool, unsigned long long, unsigned long long, unsigned long long, unsigned long long, unsigned long long*, unsigned long long*);
_Bool __builtin_GOMP_loop_ull_guided_start(_Bool, unsigned long long, unsigned long long, unsigned long long, unsigned long long, unsigned long long*, unsigned long long*);
_Bool __builtin_GOMP_loop_ull_runtime_start(_Bool, unsigned long long, unsigned long long, unsigned long long, unsigned long long*, unsigned long long*);
_Bool __builtin_GOMP_loop_ull_nonmonotonic_dynamic_start(_Bool, unsigned long long, unsigned long long, unsigned long long, unsigned long long, unsigned long long*, unsigned long long*);
_Bool __builtin_GOMP_loop_ull_nonmonotonic_guided_start(_Bool, unsigned long long, unsigned long long, unsigned long long, unsigned long long, unsigned long long*, unsigned long long*);
_Bool __builtin_GOMP_loop_ull_ordered_static_start(_Bool, unsigned long long, unsigned long long, unsigned long long, unsigned long long, unsigned long long*, unsigned long long*);
_Bool __builtin_GOMP_loop_ull_ordered_dynamic_start(_Bool, unsigned long long, unsigned long long, unsigned long long, unsigned long long, unsigned long long*, unsigned long long*);
_Bool __builtin_GOMP_loop_ull_ordered_guided_start(_Bool, unsigned long long, unsigned long long, unsigned long long, unsigned long long, unsigned long long*, unsigned long long*);
_Bool __builtin_GOMP_loop_ull_ordered_runtime_start(_Bool, unsigned long long, unsigned long long, unsigned long long, unsigned long long*, unsigned long long*);
_Bool __builtin_GOMP_loop_ull_doacross_static_start(unsigned, unsigned long long*, unsigned long long, unsigned long long*, unsigned long long*);
_Bool __builtin_GOMP_loop_ull_doacross_dynamic_start(unsigned, unsigned long long*, unsigned long long, unsigned long long*, unsigned long long*);
_Bool __builtin_GOMP_loop_ull_doacross_guided_start(unsigned, unsigned long long*, unsigned long long, unsigned long long*, unsigned long long*);
_Bool __builtin_GOMP_loop_ull_doacross_runtime_start(unsigned, unsigned long long*, unsigned long long*, unsigned long long*);
_Bool __builtin_GOMP_loop_ull_static_next(unsigned long long*, unsigned long long*);
_Bool __builtin_GOMP_loop_ull_dynamic_next(unsigned long long*, unsigned long long*);
_Bool __builtin_GOMP_loop_ull_guided_next(unsigned long long*, unsigned long long*);
_Bool __builtin_GOMP_loop_ull_runtime_next(unsigned long long*, unsigned long long*);
_Bool __builtin_GOMP_loop_ull_nonmonotonic_dynamic_next(unsigned long long*, unsigned long long*);
_Bool __builtin_GOMP_loop_ull_nonmonotonic_guided_next(unsigned long long*, unsigned long long*);
_Bool __builtin_GOMP_loop_ull_ordered_static_next(unsigned long long*, unsigned long long*);
_Bool __builtin_GOMP_loop_ull_ordered_dynamic_next(unsigned long long*, unsigned long long*);
_Bool __builtin_GOMP_loop_ull_ordered_guided_next(unsigned long long*, unsigned long long*);
_Bool __builtin_GOMP_loop_ull_ordered_runtime_next(unsigned long long*, unsigned long long*);
void __builtin_GOMP_loop_end();
_Bool __builtin_GOMP_loop_end_cancel();
void __builtin_GOMP_loop_end_nowait();
void __builtin_GOMP_ordered_start();
void __builtin_GOMP_ordered_end();
void __builtin_GOMP_doacross_post(void*);
void __builtin_GOMP_doacross_wait(long, ...);
void __builtin_GOMP_doacross_ull_post(void*);
void __builtin_GOMP_doacross_ull_wait(unsigned long long, ...);
unsigned __builtin_GOMP_sections_start(unsigned);
unsigned __builtin_GOMP_sections_next();
void __builtin_GOMP_sections_end();
_Bool __builtin_GOMP_sections_end_cancel();
void __builtin_GOMP_sections_end_nowait();
_Bool __builtin_GOMP_single_start();
void* __builtin_GOMP_single_copy_start();
void __builtin_GOMP_single_copy_end(void*);
void __builtin_GOMP_offload_register_ver(int, void*, int, void*);
void __builtin_GOMP_offload_unregister_ver(int, void*, int, void*);
void __builtin_GOMP_target_data_ext(int, __CPROVER_size_t, void*, void*, void*);
void __builtin_GOMP_target_end_data();
void __builtin_GOMP_target_update_ext(int, __CPROVER_size_t, void*, void*, void*, unsigned, void*);
void __builtin_GOMP_target_enter_exit_data(int, __CPROVER_size_t, void*, void*, void*, unsigned, void*);
void __builtin_GOMP_teams(unsigned, unsigned);
// clang-format on
