// clang-format off
unsigned __builtin__ITM_beginTransaction(unsigned, ...);
void __builtin__ITM_commitTransaction();
void __builtin__ITM_commitTransactionEH(void*);
void __builtin__ITM_abortTransaction(int);
void __builtin__ITM_changeTransactionMode(int);
void __builtin__ITM_memcpyRtWt(void*, const void*, __CPROVER_size_t);
void __builtin__ITM_memcpyRnWt(void*, const void*, __CPROVER_size_t);
void __builtin__ITM_memcpyRtWn(void*, const void*, __CPROVER_size_t);
void __builtin__ITM_memmoveRtWt(void*, const void*, __CPROVER_size_t);
void __builtin__ITM_memsetW(void*, int, __CPROVER_size_t);
void* __builtin__ITM_malloc(__CPROVER_size_t);
void* __builtin__ITM_calloc(__CPROVER_size_t, __CPROVER_size_t);
void __builtin__ITM_LB(volatile void*, __CPROVER_size_t);
void* __builtin__ITM_getTMCloneOrIrrevocable(void*);
void* __builtin__ITM_getTMCloneSafe(void*);
void __builtin__ITM_free(void*);
void __builtin__ITM_LU1(volatile void*);
void __builtin__ITM_LU2(volatile void*);
void __builtin__ITM_LU4(volatile void*);
void __builtin__ITM_LU8(volatile void*);
void __builtin__ITM_LF(volatile void*);
void __builtin__ITM_LD(volatile void*);
void __builtin__ITM_LE(volatile void*);
void __builtin__ITM_WF(volatile void*, float);
void __builtin__ITM_WaRF(volatile void*, float);
void __builtin__ITM_WaWF(volatile void*, float);
void __builtin__ITM_WD(volatile void*, double);
void __builtin__ITM_WaRD(volatile void*, double);
void __builtin__ITM_WaWD(volatile void*, double);
void __builtin__ITM_WE(volatile void*, long double);
void __builtin__ITM_WaRE(volatile void*, long double);
void __builtin__ITM_WaWE(volatile void*, long double);
float __builtin__ITM_RF(volatile void*);
float __builtin__ITM_RaRF(volatile void*);
float __builtin__ITM_RaWF(volatile void*);
float __builtin__ITM_RfWF(volatile void*);
double __builtin__ITM_RD(double*);
double __builtin__ITM_RaRD(double*);
double __builtin__ITM_RaWD(double*);
double __builtin__ITM_RfWD(double*);
long double __builtin__ITM_RE(volatile void*);
long double __builtin__ITM_RaRE(volatile void*);
long double __builtin__ITM_RaWE(volatile void*);
long double __builtin__ITM_RfWE(volatile void*);
// clang-format on
