// clang-format off
void __builtin___bnd_chk_ptr_bounds(const void*, __CPROVER_size_t);
void __builtin___bnd_chk_ptr_lbounds(const void*);
void __builtin___bnd_chk_ptr_ubounds(const void*);
void* __builtin___bnd_copy_ptr_bounds(const void*, const void*);
const void* __builtin___bnd_get_ptr_lbound(const void*);
const void* __builtin___bnd_get_ptr_ubound(const void*);
void* __builtin___bnd_init_ptr_bounds(const void*);
void* __builtin___bnd_narrow_ptr_bounds(const void*, const void*, __CPROVER_size_t);
void* __builtin___bnd_null_ptr_bounds(const void*);
void* __builtin___bnd_set_ptr_bounds(const void*, __CPROVER_size_t);
void __builtin___bnd_store_ptr_bounds(void**, const void*);
const void* __builtin___chkp_bndldx(const void*, const void*);
void __builtin___clear_cache(void*, void*);
int __builtin___fprintf_chk(void*, int, const char*, ...);
void* __builtin___memcpy_chk(void*, const void*, __CPROVER_size_t, __CPROVER_size_t);
void* __builtin___memmove_chk(void*, const void*, __CPROVER_size_t, __CPROVER_size_t);
void* __builtin___mempcpy_chk(void*, const void*, __CPROVER_size_t, __CPROVER_size_t);
void* __builtin___memset_chk(void*, int, __CPROVER_size_t, __CPROVER_size_t);
int __builtin___printf_chk(int, const char*, ...);
int __builtin___snprintf_chk(char*, __CPROVER_size_t, int, __CPROVER_size_t, const char*, ...);
int __builtin___sprintf_chk(char*, int, __CPROVER_size_t, const char*, ...);
char* __builtin___stpcpy(char *s1, const char *s2);
char* __builtin___stpcpy_chk(char*, const char*, __CPROVER_size_t);
char* __builtin___stpncpy_chk(char*, const char*, __CPROVER_size_t, __CPROVER_size_t);
char* __builtin___strcat_chk(char*, const char*, __CPROVER_size_t);
char* __builtin___strcpy_chk(char*, const char*, __CPROVER_size_t);
char* __builtin___strncat_chk(char*, const char*, __CPROVER_size_t, __CPROVER_size_t);
char* __builtin___strncpy_chk(char*, const char*, __CPROVER_size_t, __CPROVER_size_t);
int __builtin___vfprintf_chk(void*, int, const char*, __builtin_va_list);
int __builtin___vprintf_chk(int, const char*, __builtin_va_list);
int __builtin___vsnprintf_chk (char *s, __CPROVER_size_t maxlen, int flag, __CPROVER_size_t os, const char *fmt, __builtin_va_list ap);
int __builtin___vsprintf_chk(char*, int, __CPROVER_size_t, const char*, __builtin_va_list);
void* __builtin_aggregate_incoming_address();
void* __builtin_aligned_alloc(__CPROVER_size_t, __CPROVER_size_t);
void* __builtin_alloca(__CPROVER_size_t);
void* __builtin_assume_aligned(const void*, __CPROVER_size_t, ...);
int __builtin_bcmp(const void*, const void*, __CPROVER_size_t);
void __builtin_bcopy(const void*, void*, __CPROVER_size_t);
short unsigned int __builtin_bswap16(short unsigned int);
unsigned int __builtin_bswap32(unsigned int);
long long unsigned int __builtin_bswap64(long long unsigned int);
void __builtin_bzero(void*, __CPROVER_size_t);
void* __builtin_calloc(__CPROVER_size_t, __CPROVER_size_t);
void* __builtin_chkp_memcpy_nobnd(void*, const void*, __CPROVER_size_t);
void* __builtin_chkp_memcpy_nobnd_nochk(void*, const void*, __CPROVER_size_t);
void* __builtin_chkp_memcpy_nochk(void*, const void*, __CPROVER_size_t);
void* __builtin_chkp_memmove_nobnd(void*, const void*, __CPROVER_size_t);
void* __builtin_chkp_memmove_nobnd_nochk(void*, const void*, __CPROVER_size_t);
void* __builtin_chkp_memmove_nochk(void*, const void*, __CPROVER_size_t);
void* __builtin_chkp_mempcpy_nobnd(void*, const void*, __CPROVER_size_t);
void* __builtin_chkp_mempcpy_nobnd_nochk(void*, const void*, __CPROVER_size_t);
void* __builtin_chkp_mempcpy_nochk(void*, const void*, __CPROVER_size_t);
void* __builtin_chkp_memset_nobnd(void*, int, __CPROVER_size_t);
void* __builtin_chkp_memset_nobnd_nochk(void*, int, __CPROVER_size_t);
void* __builtin_chkp_memset_nochk(void*, int, __CPROVER_size_t);
int __builtin_clrsb(int);
int __builtin_clrsbimax(intmax_t);
int __builtin_clrsbl(long);
int __builtin_clrsbll(long long);
int __builtin_clz(unsigned);
int __builtin_clzimax(uintmax_t);
int __builtin_clzl(unsigned long);
int __builtin_clzll(unsigned long long);
int __builtin_ctz(unsigned);
int __builtin_ctzimax(uintmax_t);
int __builtin_ctzl(unsigned long);
int __builtin_ctzll(unsigned long long);
char* __builtin_dcgettext(const char*, const char*, int);
char* __builtin_dgettext(const char*, const char*);
void* __builtin_extract_return_addr(void*);
int __builtin_ffs(int);
int __builtin_ffsl(long);
int __builtin_ffsll(long long);
int __builtin_fprintf(void *stream, const char *fmt, ...);
int __builtin_fprintf_unlocked(void*, const char*, ...);
int __builtin_fputc(int, void*);
int __builtin_fputc_unlocked(int, void*);
int __builtin_fputs(const char *s, void *stream);
int __builtin_fputs_unlocked(const char*, void*);
void* __builtin_frame_address(unsigned);
void __builtin_free(void*);
void* __builtin_frob_return_addr(void*);
int __builtin_fscanf(void *stream, const char *fmt, ...);
__CPROVER_size_t __builtin_fwrite(const void*, __CPROVER_size_t, __CPROVER_size_t, void*);
__CPROVER_size_t __builtin_fwrite_unlocked(const void*, __CPROVER_size_t, __CPROVER_size_t, void*);
char* __builtin_gettext(const char*);
char* __builtin_index(const char*, int);
int __builtin_isalnum(int);
int __builtin_isalpha(int);
int __builtin_isascii(int);
int __builtin_isblank(int);
int __builtin_iscntrl(int);
int __builtin_isdigit(int);
int __builtin_isgraph(int);
int __builtin_islower(int);
int __builtin_isprint(int);
int __builtin_ispunct(int);
int __builtin_isspace(int);
int __builtin_isupper(int);
int __builtin_iswalnum(wint_t);
int __builtin_iswalpha(wint_t);
int __builtin_iswblank(wint_t);
int __builtin_iswcntrl(wint_t);
int __builtin_iswdigit(wint_t);
int __builtin_iswgraph(wint_t);
int __builtin_iswlower(wint_t);
int __builtin_iswprint(wint_t);
int __builtin_iswpunct(wint_t);
int __builtin_iswspace(wint_t);
int __builtin_iswupper(wint_t);
int __builtin_iswxdigit(wint_t);
int __builtin_isxdigit(int);
void* __builtin_malloc(__CPROVER_size_t);
void* __builtin_memchr(const void*, int, __CPROVER_size_t);
int __builtin_memcmp(const void*, const void*, __CPROVER_size_t);
void* __builtin_memcpy(void*, const void*, __CPROVER_size_t);
void* __builtin_memmove(void*, const void*, __CPROVER_size_t);
void* __builtin_mempcpy(void*, const void*, __CPROVER_size_t);
void* __builtin_memset(void*, int, __CPROVER_size_t);
__CPROVER_size_t __builtin_object_size(const void*, int);
int __builtin_popcount(unsigned);
int __builtin_popcountimax(uintmax_t);
int __builtin_popcountll(unsigned long long int x);
int __builtin_posix_memalign(void**, __CPROVER_size_t, __CPROVER_size_t);
void __builtin_prefetch(const void*, ...);
int __builtin_printf(const char*, ...);
int __builtin_printf_unlocked(const char*, ...);
int __builtin_putc(int, void*);
int __builtin_putc_unlocked(int, void*);
int __builtin_putchar(int);
int __builtin_putchar_unlocked(int);
int __builtin_puts(const char*);
int __builtin_puts_unlocked(const char*);
void* __builtin_realloc(void*, __CPROVER_size_t);
void* __builtin_return_address(unsigned);
char* __builtin_rindex(const char*, int);
int __builtin_scanf(const char *str, const char *fmt, ...);
int __builtin_scanf(const char*, ...);
int __builtin_snprintf(char*, __CPROVER_size_t, const char*, ...);
int __builtin_sprintf(char*, const char*, ...);
int __builtin_sscanf(const char*, const char*, ...);
char* __builtin_stpcpy(char*, const char*);
char* __builtin_stpncpy(char*, const char*, __CPROVER_size_t);
int __builtin_strcasecmp(const char*, const char*);
char* __builtin_strcat(char*, const char*);
char* __builtin_strchr(const char*, int);
int __builtin_strcmp(const char*, const char*);
char* __builtin_strcpy(char*, const char*);
__CPROVER_size_t __builtin_strcspn(const char*, const char*);
char* __builtin_strdup(const char*);
ssize_t __builtin_strfmon(char*, __CPROVER_size_t, const char*, ...);
__CPROVER_size_t __builtin_strftime(char*, __CPROVER_size_t, const char*, const struct tm*);
__CPROVER_size_t __builtin_strlen(const char*);
int __builtin_strncasecmp(const char*, const char*, __CPROVER_size_t);
char* __builtin_strncat(char*, const char*, __CPROVER_size_t);
int __builtin_strncmp(const char*, const char*, __CPROVER_size_t);
char* __builtin_strncpy(char*, const char*, __CPROVER_size_t);
char* __builtin_strndup(const char*, __CPROVER_size_t);
__CPROVER_size_t __builtin_strnlen(const char*, __CPROVER_size_t);
char* __builtin_strpbrk(const char*, const char*);
char* __builtin_strrchr(const char*, int);
__CPROVER_size_t __builtin_strspn(const char*, const char*);
char* __builtin_strstr(const char*, const char*);
int __builtin_toascii(int);
int __builtin_tolower(int);
int __builtin_toupper(int);
wint_t __builtin_towlower(wint_t);
wint_t __builtin_towupper(wint_t);
int __builtin_vfprintf(void*, const char*, __builtin_va_list);
int __builtin_vfscanf(void*, const char*, __builtin_va_list);
int __builtin_vprintf(const char*, __builtin_va_list);
int __builtin_vscanf(const char*, __builtin_va_list);
int __builtin_vsnprintf(char*, __CPROVER_size_t, const char*, __builtin_va_list);
int __builtin_vsprintf(char*, const char*, __builtin_va_list);
int __builtin_vsscanf(const char*, const char*, __builtin_va_list);
// clang-format on
