// clang-format off
__gcc_v32hi __builtin_ia32_loaddquhi512_mask(const short*, __gcc_v32hi, unsigned);
__gcc_v64qi __builtin_ia32_loaddquqi512_mask(const char*, __gcc_v64qi, unsigned long long);
void __builtin_ia32_storedquhi512_mask(short*, __gcc_v32hi, unsigned);
void __builtin_ia32_storedquqi512_mask(char*, __gcc_v64qi, unsigned long long);
__gcc_v16hi __builtin_ia32_loaddquhi256_mask(const short*, __gcc_v16hi, unsigned short);
__gcc_v8hi __builtin_ia32_loaddquhi128_mask(const short*, __gcc_v8hi, unsigned char);
__gcc_v32qi __builtin_ia32_loaddquqi256_mask(const char*, __gcc_v32qi, unsigned);
__gcc_v16qi __builtin_ia32_loaddquqi128_mask(const char*, __gcc_v16qi, unsigned short);
__gcc_v4di __builtin_ia32_movdqa64load256_mask(const __gcc_v4di*, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_movdqa64load128_mask(const __gcc_v2di*, __gcc_v2di, unsigned char);
__gcc_v8si __builtin_ia32_movdqa32load256_mask(const __gcc_v8si*, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_movdqa32load128_mask(const __gcc_v4si*, __gcc_v4si, unsigned char);
void __builtin_ia32_movdqa64store256_mask(__gcc_v4di*, __gcc_v4di, unsigned char);
void __builtin_ia32_movdqa64store128_mask(__gcc_v2di*, __gcc_v2di, unsigned char);
void __builtin_ia32_movdqa32store256_mask(__gcc_v8si*, __gcc_v8si, unsigned char);
void __builtin_ia32_movdqa32store128_mask(__gcc_v4si*, __gcc_v4si, unsigned char);
__gcc_v4df __builtin_ia32_loadapd256_mask(const __gcc_v4df*, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_loadapd128_mask(const __gcc_v2df*, __gcc_v2df, unsigned char);
__gcc_v8sf __builtin_ia32_loadaps256_mask(const __gcc_v8sf*, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_loadaps128_mask(const __gcc_v4sf*, __gcc_v4sf, unsigned char);
void __builtin_ia32_storeapd256_mask(__gcc_v4df*, __gcc_v4df, unsigned char);
void __builtin_ia32_storeapd128_mask(__gcc_v2df*, __gcc_v2df, unsigned char);
void __builtin_ia32_storeaps256_mask(__gcc_v8sf*, __gcc_v8sf, unsigned char);
void __builtin_ia32_storeaps128_mask(__gcc_v4sf*, __gcc_v4sf, unsigned char);
__gcc_v4df __builtin_ia32_loadupd256_mask(const double*, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_loadupd128_mask(const double*, __gcc_v2df, unsigned char);
__gcc_v8sf __builtin_ia32_loadups256_mask(const float*, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_loadups128_mask(const float*, __gcc_v4sf, unsigned char);
void __builtin_ia32_storeupd256_mask(double*, __gcc_v4df, unsigned char);
void __builtin_ia32_storeupd128_mask(double*, __gcc_v2df, unsigned char);
void __builtin_ia32_storeups256_mask(float*, __gcc_v8sf, unsigned char);
void __builtin_ia32_storeups128_mask(float*, __gcc_v4sf, unsigned char);
__gcc_v4di __builtin_ia32_loaddqudi256_mask(const long long*, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_loaddqudi128_mask(const long long*, __gcc_v2di, unsigned char);
__gcc_v8si __builtin_ia32_loaddqusi256_mask(const int*, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_loaddqusi128_mask(const int*, __gcc_v4si, unsigned char);
void __builtin_ia32_storedqudi256_mask(long long*, __gcc_v4di, unsigned char);
void __builtin_ia32_storedqudi128_mask(long long*, __gcc_v2di, unsigned char);
void __builtin_ia32_storedqusi256_mask(int*, __gcc_v8si, unsigned char);
void __builtin_ia32_storedqusi128_mask(int*, __gcc_v4si, unsigned char);
void __builtin_ia32_storedquhi256_mask(short*, __gcc_v16hi, unsigned short);
void __builtin_ia32_storedquhi128_mask(short*, __gcc_v8hi, unsigned char);
void __builtin_ia32_storedquqi256_mask(char*, __gcc_v32qi, unsigned);
void __builtin_ia32_storedquqi128_mask(char*, __gcc_v16qi, unsigned short);
void __builtin_ia32_compressstoredf256_mask(__gcc_v4df*, __gcc_v4df, unsigned char);
void __builtin_ia32_compressstoredf128_mask(__gcc_v2df*, __gcc_v2df, unsigned char);
void __builtin_ia32_compressstoresf256_mask(__gcc_v8sf*, __gcc_v8sf, unsigned char);
void __builtin_ia32_compressstoresf128_mask(__gcc_v4sf*, __gcc_v4sf, unsigned char);
void __builtin_ia32_compressstoredi256_mask(__gcc_v4di*, __gcc_v4di, unsigned char);
void __builtin_ia32_compressstoredi128_mask(__gcc_v2di*, __gcc_v2di, unsigned char);
void __builtin_ia32_compressstoresi256_mask(__gcc_v8si*, __gcc_v8si, unsigned char);
void __builtin_ia32_compressstoresi128_mask(__gcc_v4si*, __gcc_v4si, unsigned char);
__gcc_v4df __builtin_ia32_expandloaddf256_mask(const __gcc_v4df*, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_expandloaddf128_mask(const __gcc_v2df*, __gcc_v2df, unsigned char);
__gcc_v8sf __builtin_ia32_expandloadsf256_mask(const __gcc_v8sf*, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_expandloadsf128_mask(const __gcc_v4sf*, __gcc_v4sf, unsigned char);
__gcc_v4di __builtin_ia32_expandloaddi256_mask(const __gcc_v4di*, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_expandloaddi128_mask(const __gcc_v2di*, __gcc_v2di, unsigned char);
__gcc_v8si __builtin_ia32_expandloadsi256_mask(const __gcc_v8si*, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_expandloadsi128_mask(const __gcc_v4si*, __gcc_v4si, unsigned char);
__gcc_v4df __builtin_ia32_expandloaddf256_maskz(const __gcc_v4df*, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_expandloaddf128_maskz(const __gcc_v2df*, __gcc_v2df, unsigned char);
__gcc_v8sf __builtin_ia32_expandloadsf256_maskz(const __gcc_v8sf*, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_expandloadsf128_maskz(const __gcc_v4sf*, __gcc_v4sf, unsigned char);
__gcc_v4di __builtin_ia32_expandloaddi256_maskz(const __gcc_v4di*, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_expandloaddi128_maskz(const __gcc_v2di*, __gcc_v2di, unsigned char);
__gcc_v8si __builtin_ia32_expandloadsi256_maskz(const __gcc_v8si*, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_expandloadsi128_maskz(const __gcc_v4si*, __gcc_v4si, unsigned char);
void __builtin_ia32_pmovqd256mem_mask(__gcc_v4si*, __gcc_v4di, unsigned char);
void __builtin_ia32_pmovqd128mem_mask(unsigned long long*, __gcc_v2di, unsigned char);
void __builtin_ia32_pmovsqd256mem_mask(__gcc_v4si*, __gcc_v4di, unsigned char);
void __builtin_ia32_pmovsqd128mem_mask(unsigned long long*, __gcc_v2di, unsigned char);
void __builtin_ia32_pmovusqd256mem_mask(__gcc_v4si*, __gcc_v4di, unsigned char);
void __builtin_ia32_pmovusqd128mem_mask(unsigned long long*, __gcc_v2di, unsigned char);
void __builtin_ia32_pmovqw256mem_mask(unsigned long long*, __gcc_v4di, unsigned char);
void __builtin_ia32_pmovqw128mem_mask(unsigned*, __gcc_v2di, unsigned char);
void __builtin_ia32_pmovsqw256mem_mask(unsigned long long*, __gcc_v4di, unsigned char);
void __builtin_ia32_pmovsqw128mem_mask(unsigned*, __gcc_v2di, unsigned char);
void __builtin_ia32_pmovusqw256mem_mask(unsigned long long*, __gcc_v4di, unsigned char);
void __builtin_ia32_pmovusqw128mem_mask(unsigned*, __gcc_v2di, unsigned char);
void __builtin_ia32_pmovqb256mem_mask(unsigned*, __gcc_v4di, unsigned char);
void __builtin_ia32_pmovqb128mem_mask(unsigned short*, __gcc_v2di, unsigned char);
void __builtin_ia32_pmovsqb256mem_mask(unsigned*, __gcc_v4di, unsigned char);
void __builtin_ia32_pmovsqb128mem_mask(unsigned short*, __gcc_v2di, unsigned char);
void __builtin_ia32_pmovusqb256mem_mask(unsigned*, __gcc_v4di, unsigned char);
void __builtin_ia32_pmovusqb128mem_mask(unsigned short*, __gcc_v2di, unsigned char);
void __builtin_ia32_pmovdb256mem_mask(unsigned long long*, __gcc_v8si, unsigned char);
void __builtin_ia32_pmovdb128mem_mask(unsigned*, __gcc_v4si, unsigned char);
void __builtin_ia32_pmovsdb256mem_mask(unsigned long long*, __gcc_v8si, unsigned char);
void __builtin_ia32_pmovsdb128mem_mask(unsigned*, __gcc_v4si, unsigned char);
void __builtin_ia32_pmovusdb256mem_mask(unsigned long long*, __gcc_v8si, unsigned char);
void __builtin_ia32_pmovusdb128mem_mask(unsigned*, __gcc_v4si, unsigned char);
void __builtin_ia32_pmovdw256mem_mask(__gcc_v8hi*, __gcc_v8si, unsigned char);
void __builtin_ia32_pmovdw128mem_mask(unsigned long long*, __gcc_v4si, unsigned char);
void __builtin_ia32_pmovsdw256mem_mask(__gcc_v8hi*, __gcc_v8si, unsigned char);
void __builtin_ia32_pmovsdw128mem_mask(unsigned long long*, __gcc_v4si, unsigned char);
void __builtin_ia32_pmovusdw256mem_mask(__gcc_v8hi*, __gcc_v8si, unsigned char);
void __builtin_ia32_pmovusdw128mem_mask(unsigned long long*, __gcc_v4si, unsigned char);
unsigned __builtin_ia32_rdpkru();
void __builtin_ia32_wrpkru(unsigned);
__gcc_v8si __builtin_ia32_vec_pack_sfix256 (__gcc_v4df, __gcc_v4df);
unsigned short __builtin_ia32_lzcnt_u16(unsigned short);
unsigned short __builtin_ia32_tzcnt_u16(unsigned short);
unsigned __builtin_ia32_tzcnt_u32(unsigned);
unsigned long long __builtin_ia32_tzcnt_u64(unsigned long long);
__gcc_v16si __builtin_ia32_si512_256si(__gcc_v8si);
__gcc_v16sf __builtin_ia32_ps512_256ps(__gcc_v8sf);
__gcc_v8df __builtin_ia32_pd512_256pd(__gcc_v4df);
__gcc_v16si __builtin_ia32_si512_si(__gcc_v4si);
__gcc_v16sf __builtin_ia32_ps512_ps(__gcc_v4sf);
__gcc_v8df __builtin_ia32_pd512_pd(__gcc_v2df);
__gcc_v16si __builtin_ia32_cvtps2dq512(__gcc_v16sf);
__gcc_v16si __builtin_ia32_vec_pack_sfix512(__gcc_v8df, __gcc_v8df);
__gcc_v16si __builtin_ia32_roundps_az_sfix512(__gcc_v16sf);
unsigned short __builtin_ia32_kshiftlihi(unsigned short, unsigned char);
unsigned __builtin_ia32_kshiftlisi(unsigned, unsigned char);
unsigned long long __builtin_ia32_kshiftlidi(unsigned long long, unsigned char);
unsigned short __builtin_ia32_kshiftrihi(unsigned short, unsigned char);
unsigned __builtin_ia32_kshiftrisi(unsigned, unsigned char);
unsigned long long __builtin_ia32_kshiftridi(unsigned long long, unsigned char);
unsigned char __builtin_ia32_kandqi(unsigned char, unsigned char);
unsigned __builtin_ia32_kandsi(unsigned, unsigned);
unsigned long long __builtin_ia32_kanddi(unsigned long long, unsigned long long);
unsigned char __builtin_ia32_kandnqi(unsigned char, unsigned char);
unsigned __builtin_ia32_kandnsi(unsigned, unsigned);
unsigned long long __builtin_ia32_kandndi(unsigned long long, unsigned long long);
unsigned char __builtin_ia32_knotqi(unsigned char);
unsigned __builtin_ia32_knotsi(unsigned);
unsigned long long __builtin_ia32_knotdi(unsigned long long);
unsigned char __builtin_ia32_korqi(unsigned char, unsigned char);
unsigned __builtin_ia32_korsi(unsigned, unsigned);
unsigned long long __builtin_ia32_kordi(unsigned long long, unsigned long long);
unsigned char __builtin_ia32_ktestcqi(unsigned char, unsigned char);
unsigned char __builtin_ia32_ktestzqi(unsigned char, unsigned char);
unsigned short __builtin_ia32_ktestchi(unsigned short, unsigned short);
unsigned short __builtin_ia32_ktestzhi(unsigned short, unsigned short);
unsigned __builtin_ia32_ktestcsi(unsigned, unsigned);
unsigned __builtin_ia32_ktestzsi(unsigned, unsigned);
unsigned long long __builtin_ia32_ktestcdi(unsigned long long, unsigned long long);
unsigned long long __builtin_ia32_ktestzdi(unsigned long long, unsigned long long);
unsigned char __builtin_ia32_kortestcqi(unsigned char, unsigned char);
unsigned char __builtin_ia32_kortestzqi(unsigned char, unsigned char);
unsigned __builtin_ia32_kortestcsi(unsigned, unsigned);
unsigned __builtin_ia32_kortestzsi(unsigned, unsigned);
unsigned long long __builtin_ia32_kortestcdi(unsigned long long, unsigned long long);
unsigned long long __builtin_ia32_kortestzdi(unsigned long long, unsigned long long);
unsigned char __builtin_ia32_kxnorqi(unsigned char, unsigned char);
unsigned __builtin_ia32_kxnorsi(unsigned, unsigned);
unsigned long long __builtin_ia32_kxnordi(unsigned long long, unsigned long long);
unsigned char __builtin_ia32_kxorqi(unsigned char, unsigned char);
unsigned __builtin_ia32_kxorsi(unsigned, unsigned);
unsigned long long __builtin_ia32_kxordi(unsigned long long, unsigned long long);
unsigned char __builtin_ia32_kmovb(unsigned char);
unsigned short __builtin_ia32_kmovw(unsigned short);
unsigned __builtin_ia32_kmovd(unsigned);
unsigned long long __builtin_ia32_kmovq(unsigned long long);
unsigned char __builtin_ia32_kaddqi(unsigned char, unsigned char);
unsigned short __builtin_ia32_kaddhi(unsigned short, unsigned short);
unsigned __builtin_ia32_kaddsi(unsigned, unsigned);
unsigned long long __builtin_ia32_kadddi(unsigned long long, unsigned long long);
__gcc_v4di __builtin_ia32_movdqa64_256_mask(__gcc_v4di, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_movdqa64_128_mask(__gcc_v2di, __gcc_v2di, unsigned char);
__gcc_v8si __builtin_ia32_movdqa32_256_mask(__gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_movdqa32_128_mask(__gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v4df __builtin_ia32_movapd256_mask(__gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_movapd128_mask(__gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v8sf __builtin_ia32_movaps256_mask(__gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_movaps128_mask(__gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v16hi __builtin_ia32_movdquhi256_mask(__gcc_v16hi, __gcc_v16hi, unsigned short);
__gcc_v8hi __builtin_ia32_movdquhi128_mask(__gcc_v8hi, __gcc_v8hi, unsigned char);
__gcc_v32qi __builtin_ia32_movdquqi256_mask(__gcc_v32qi, __gcc_v32qi, unsigned);
__gcc_v16qi __builtin_ia32_movdquqi128_mask(__gcc_v16qi, __gcc_v16qi, unsigned short);
__gcc_v4sf __builtin_ia32_minps_mask(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v4sf __builtin_ia32_maxps_mask(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v2df __builtin_ia32_minpd_mask(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v2df __builtin_ia32_maxpd_mask(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v4df __builtin_ia32_maxpd256_mask(__gcc_v4df, __gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v8sf __builtin_ia32_maxps256_mask(__gcc_v8sf, __gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v4df __builtin_ia32_minpd256_mask(__gcc_v4df, __gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v8sf __builtin_ia32_minps256_mask(__gcc_v8sf, __gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_mulps_mask(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v4sf __builtin_ia32_divps_mask(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v2df __builtin_ia32_mulpd_mask(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v2df __builtin_ia32_divpd_mask(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v4df __builtin_ia32_divpd256_mask(__gcc_v4df, __gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v8sf __builtin_ia32_divps256_mask(__gcc_v8sf, __gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v4df __builtin_ia32_mulpd256_mask(__gcc_v4df, __gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v8sf __builtin_ia32_mulps256_mask(__gcc_v8sf, __gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v2df __builtin_ia32_addpd128_mask(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v4df __builtin_ia32_addpd256_mask(__gcc_v4df, __gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v4sf __builtin_ia32_addps128_mask(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v8sf __builtin_ia32_addps256_mask(__gcc_v8sf, __gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v2df __builtin_ia32_subpd128_mask(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v4df __builtin_ia32_subpd256_mask(__gcc_v4df, __gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v4sf __builtin_ia32_subps128_mask(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v8sf __builtin_ia32_subps256_mask(__gcc_v8sf, __gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v4df __builtin_ia32_xorpd256_mask(__gcc_v4df, __gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_xorpd128_mask(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v8sf __builtin_ia32_xorps256_mask(__gcc_v8sf, __gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_xorps128_mask(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v4df __builtin_ia32_orpd256_mask(__gcc_v4df, __gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_orpd128_mask(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v8sf __builtin_ia32_orps256_mask(__gcc_v8sf, __gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_orps128_mask(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v8sf __builtin_ia32_broadcastf32x2_256_mask(__gcc_v4sf, __gcc_v8sf, unsigned char);
__gcc_v8si __builtin_ia32_broadcasti32x2_256_mask(__gcc_v4si, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_broadcasti32x2_128_mask(__gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v4df __builtin_ia32_broadcastf64x2_256_mask(__gcc_v2df, __gcc_v4df, unsigned char);
__gcc_v4di __builtin_ia32_broadcasti64x2_256_mask(__gcc_v2di, __gcc_v4di, unsigned char);
__gcc_v8sf __builtin_ia32_broadcastf32x4_256_mask(__gcc_v4sf, __gcc_v8sf, unsigned char);
__gcc_v8si __builtin_ia32_broadcasti32x4_256_mask(__gcc_v4si, __gcc_v8si, unsigned char);
__gcc_v4sf __builtin_ia32_extractf32x4_256_mask(__gcc_v8sf, int, __gcc_v4sf, unsigned char);
__gcc_v4si __builtin_ia32_extracti32x4_256_mask(__gcc_v8si, int, __gcc_v4si, unsigned char);
__gcc_v16hi __builtin_ia32_dbpsadbw256_mask(__gcc_v32qi, __gcc_v32qi, int, __gcc_v16hi, unsigned short);
__gcc_v8hi __builtin_ia32_dbpsadbw128_mask(__gcc_v16qi, __gcc_v16qi, int, __gcc_v8hi, unsigned char);
__gcc_v4di __builtin_ia32_cvttpd2qq256_mask(__gcc_v4df, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_cvttpd2qq128_mask(__gcc_v2df, __gcc_v2di, unsigned char);
__gcc_v4di __builtin_ia32_cvttpd2uqq256_mask(__gcc_v4df, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_cvttpd2uqq128_mask(__gcc_v2df, __gcc_v2di, unsigned char);
__gcc_v4di __builtin_ia32_cvtpd2qq256_mask(__gcc_v4df, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_cvtpd2qq128_mask(__gcc_v2df, __gcc_v2di, unsigned char);
__gcc_v4di __builtin_ia32_cvtpd2uqq256_mask(__gcc_v4df, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_cvtpd2uqq128_mask(__gcc_v2df, __gcc_v2di, unsigned char);
__gcc_v4si __builtin_ia32_cvtpd2udq256_mask(__gcc_v4df, __gcc_v4si, unsigned char);
__gcc_v4si __builtin_ia32_cvtpd2udq128_mask(__gcc_v2df, __gcc_v4si, unsigned char);
__gcc_v4di __builtin_ia32_cvttps2qq256_mask(__gcc_v4sf, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_cvttps2qq128_mask(__gcc_v4sf, __gcc_v2di, unsigned char);
__gcc_v4di __builtin_ia32_cvttps2uqq256_mask(__gcc_v4sf, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_cvttps2uqq128_mask(__gcc_v4sf, __gcc_v2di, unsigned char);
__gcc_v8si __builtin_ia32_cvttps2dq256_mask(__gcc_v8sf, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_cvttps2dq128_mask(__gcc_v4sf, __gcc_v4si, unsigned char);
__gcc_v8si __builtin_ia32_cvttps2udq256_mask(__gcc_v8sf, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_cvttps2udq128_mask(__gcc_v4sf, __gcc_v4si, unsigned char);
__gcc_v4si __builtin_ia32_cvttpd2dq256_mask(__gcc_v4df, __gcc_v4si, unsigned char);
__gcc_v4si __builtin_ia32_cvttpd2dq128_mask(__gcc_v2df, __gcc_v4si, unsigned char);
__gcc_v4si __builtin_ia32_cvttpd2udq256_mask(__gcc_v4df, __gcc_v4si, unsigned char);
__gcc_v4si __builtin_ia32_cvttpd2udq128_mask(__gcc_v2df, __gcc_v4si, unsigned char);
__gcc_v4si __builtin_ia32_cvtpd2dq256_mask(__gcc_v4df, __gcc_v4si, unsigned char);
__gcc_v4si __builtin_ia32_cvtpd2dq128_mask(__gcc_v2df, __gcc_v4si, unsigned char);
__gcc_v4df __builtin_ia32_cvtdq2pd256_mask(__gcc_v4si, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_cvtdq2pd128_mask(__gcc_v4si, __gcc_v2df, unsigned char);
__gcc_v4df __builtin_ia32_cvtudq2pd256_mask(__gcc_v4si, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_cvtudq2pd128_mask(__gcc_v4si, __gcc_v2df, unsigned char);
__gcc_v8sf __builtin_ia32_cvtdq2ps256_mask(__gcc_v8si, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_cvtdq2ps128_mask(__gcc_v4si, __gcc_v4sf, unsigned char);
__gcc_v8sf __builtin_ia32_cvtudq2ps256_mask(__gcc_v8si, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_cvtudq2ps128_mask(__gcc_v4si, __gcc_v4sf, unsigned char);
__gcc_v4df __builtin_ia32_cvtps2pd256_mask(__gcc_v4sf, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_cvtps2pd128_mask(__gcc_v4sf, __gcc_v2df, unsigned char);
__gcc_v32qi __builtin_ia32_pbroadcastb256_mask(__gcc_v16qi, __gcc_v32qi, unsigned);
__gcc_v32qi __builtin_ia32_pbroadcastb256_gpr_mask(char, __gcc_v32qi, unsigned);
__gcc_v16qi __builtin_ia32_pbroadcastb128_mask(__gcc_v16qi, __gcc_v16qi, unsigned short);
__gcc_v16qi __builtin_ia32_pbroadcastb128_gpr_mask(char, __gcc_v16qi, unsigned short);
__gcc_v16hi __builtin_ia32_pbroadcastw256_mask(__gcc_v8hi, __gcc_v16hi, unsigned short);
__gcc_v16hi __builtin_ia32_pbroadcastw256_gpr_mask(short, __gcc_v16hi, unsigned short);
__gcc_v8hi __builtin_ia32_pbroadcastw128_mask(__gcc_v8hi, __gcc_v8hi, unsigned char);
__gcc_v8hi __builtin_ia32_pbroadcastw128_gpr_mask(short, __gcc_v8hi, unsigned char);
__gcc_v8si __builtin_ia32_pbroadcastd256_mask(__gcc_v4si, __gcc_v8si, unsigned char);
__gcc_v8si __builtin_ia32_pbroadcastd256_gpr_mask(int, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_pbroadcastd128_mask(__gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v4si __builtin_ia32_pbroadcastd128_gpr_mask(int, __gcc_v4si, unsigned char);
__gcc_v4di __builtin_ia32_pbroadcastq256_mask(__gcc_v2di, __gcc_v4di, unsigned char);
__gcc_v4di __builtin_ia32_pbroadcastq256_gpr_mask(long long, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_pbroadcastq128_mask(__gcc_v2di, __gcc_v2di, unsigned char);
__gcc_v2di __builtin_ia32_pbroadcastq128_gpr_mask(long long, __gcc_v2di, unsigned char);
__gcc_v8sf __builtin_ia32_broadcastss256_mask(__gcc_v4sf, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_broadcastss128_mask(__gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v4df __builtin_ia32_broadcastsd256_mask(__gcc_v2df, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_extractf64x2_256_mask(__gcc_v4df, int, __gcc_v2df, unsigned char);
__gcc_v2di __builtin_ia32_extracti64x2_256_mask(__gcc_v4di, int, __gcc_v2di, unsigned char);
__gcc_v8sf __builtin_ia32_insertf32x4_256_mask(__gcc_v8sf, __gcc_v4sf, int, __gcc_v8sf, unsigned char);
__gcc_v8si __builtin_ia32_inserti32x4_256_mask(__gcc_v8si, __gcc_v4si, int, __gcc_v8si, unsigned char);
__gcc_v16hi __builtin_ia32_pmovsxbw256_mask(__gcc_v16qi, __gcc_v16hi, unsigned short);
__gcc_v8hi __builtin_ia32_pmovsxbw128_mask(__gcc_v16qi, __gcc_v8hi, unsigned char);
__gcc_v8si __builtin_ia32_pmovsxbd256_mask(__gcc_v16qi, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_pmovsxbd128_mask(__gcc_v16qi, __gcc_v4si, unsigned char);
__gcc_v4di __builtin_ia32_pmovsxbq256_mask(__gcc_v16qi, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_pmovsxbq128_mask(__gcc_v16qi, __gcc_v2di, unsigned char);
__gcc_v8si __builtin_ia32_pmovsxwd256_mask(__gcc_v8hi, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_pmovsxwd128_mask(__gcc_v8hi, __gcc_v4si, unsigned char);
__gcc_v4di __builtin_ia32_pmovsxwq256_mask(__gcc_v8hi, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_pmovsxwq128_mask(__gcc_v8hi, __gcc_v2di, unsigned char);
__gcc_v4di __builtin_ia32_pmovsxdq256_mask(__gcc_v4si, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_pmovsxdq128_mask(__gcc_v4si, __gcc_v2di, unsigned char);
__gcc_v16hi __builtin_ia32_pmovzxbw256_mask(__gcc_v16qi, __gcc_v16hi, unsigned short);
__gcc_v8hi __builtin_ia32_pmovzxbw128_mask(__gcc_v16qi, __gcc_v8hi, unsigned char);
__gcc_v8si __builtin_ia32_pmovzxbd256_mask(__gcc_v16qi, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_pmovzxbd128_mask(__gcc_v16qi, __gcc_v4si, unsigned char);
__gcc_v4di __builtin_ia32_pmovzxbq256_mask(__gcc_v16qi, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_pmovzxbq128_mask(__gcc_v16qi, __gcc_v2di, unsigned char);
__gcc_v8si __builtin_ia32_pmovzxwd256_mask(__gcc_v8hi, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_pmovzxwd128_mask(__gcc_v8hi, __gcc_v4si, unsigned char);
__gcc_v4di __builtin_ia32_pmovzxwq256_mask(__gcc_v8hi, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_pmovzxwq128_mask(__gcc_v8hi, __gcc_v2di, unsigned char);
__gcc_v4di __builtin_ia32_pmovzxdq256_mask(__gcc_v4si, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_pmovzxdq128_mask(__gcc_v4si, __gcc_v2di, unsigned char);
__gcc_v4df __builtin_ia32_reducepd256_mask(__gcc_v4df, int, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_reducepd128_mask(__gcc_v2df, int, __gcc_v2df, unsigned char);
__gcc_v8sf __builtin_ia32_reduceps256_mask(__gcc_v8sf, int, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_reduceps128_mask(__gcc_v4sf, int, __gcc_v4sf, unsigned char);
__gcc_v2df __builtin_ia32_reducesd(__gcc_v2df, __gcc_v2df, int);
__gcc_v4sf __builtin_ia32_reducess(__gcc_v4sf, __gcc_v4sf, int);
__gcc_v16hi __builtin_ia32_permvarhi256_mask(__gcc_v16hi, __gcc_v16hi, __gcc_v16hi, unsigned short);
__gcc_v8hi __builtin_ia32_permvarhi128_mask(__gcc_v8hi, __gcc_v8hi, __gcc_v8hi, unsigned char);
__gcc_v16hi __builtin_ia32_vpermt2varhi256_mask(__gcc_v16hi, __gcc_v16hi, __gcc_v16hi, unsigned short);
__gcc_v16hi __builtin_ia32_vpermt2varhi256_maskz(__gcc_v16hi, __gcc_v16hi, __gcc_v16hi, unsigned short);
__gcc_v8hi __builtin_ia32_vpermt2varhi128_mask(__gcc_v8hi, __gcc_v8hi, __gcc_v8hi, unsigned char);
__gcc_v8hi __builtin_ia32_vpermt2varhi128_maskz(__gcc_v8hi, __gcc_v8hi, __gcc_v8hi, unsigned char);
__gcc_v16hi __builtin_ia32_vpermi2varhi256_mask(__gcc_v16hi, __gcc_v16hi, __gcc_v16hi, unsigned short);
__gcc_v8hi __builtin_ia32_vpermi2varhi128_mask(__gcc_v8hi, __gcc_v8hi, __gcc_v8hi, unsigned char);
__gcc_v4df __builtin_ia32_rcp14pd256_mask(__gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_rcp14pd128_mask(__gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v8sf __builtin_ia32_rcp14ps256_mask(__gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_rcp14ps128_mask(__gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v4df __builtin_ia32_rsqrt14pd256_mask(__gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_rsqrt14pd128_mask(__gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v8sf __builtin_ia32_rsqrt14ps256_mask(__gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_rsqrt14ps128_mask(__gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v4df __builtin_ia32_sqrtpd256_mask(__gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_sqrtpd128_mask(__gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v8sf __builtin_ia32_sqrtps256_mask(__gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_sqrtps128_mask(__gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v16qi __builtin_ia32_paddb128_mask(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, unsigned short);
__gcc_v8hi __builtin_ia32_paddw128_mask(__gcc_v8hi, __gcc_v8hi, __gcc_v8hi, unsigned char);
__gcc_v4si __builtin_ia32_paddd128_mask(__gcc_v4si, __gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v2di __builtin_ia32_paddq128_mask(__gcc_v2di, __gcc_v2di, __gcc_v2di, unsigned char);
__gcc_v16qi __builtin_ia32_psubb128_mask(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, unsigned short);
__gcc_v8hi __builtin_ia32_psubw128_mask(__gcc_v8hi, __gcc_v8hi, __gcc_v8hi, unsigned char);
__gcc_v4si __builtin_ia32_psubd128_mask(__gcc_v4si, __gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v2di __builtin_ia32_psubq128_mask(__gcc_v2di, __gcc_v2di, __gcc_v2di, unsigned char);
__gcc_v16qi __builtin_ia32_paddsb128_mask(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, unsigned short);
__gcc_v8hi __builtin_ia32_paddsw128_mask(__gcc_v8hi, __gcc_v8hi, __gcc_v8hi, unsigned char);
__gcc_v16qi __builtin_ia32_psubsb128_mask(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, unsigned short);
__gcc_v8hi __builtin_ia32_psubsw128_mask(__gcc_v8hi, __gcc_v8hi, __gcc_v8hi, unsigned char);
__gcc_v16qi __builtin_ia32_paddusb128_mask(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, unsigned short);
__gcc_v8hi __builtin_ia32_paddusw128_mask(__gcc_v8hi, __gcc_v8hi, __gcc_v8hi, unsigned char);
__gcc_v16qi __builtin_ia32_psubusb128_mask(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, unsigned short);
__gcc_v8hi __builtin_ia32_psubusw128_mask(__gcc_v8hi, __gcc_v8hi, __gcc_v8hi, unsigned char);
__gcc_v32qi __builtin_ia32_paddb256_mask(__gcc_v32qi, __gcc_v32qi, __gcc_v32qi, unsigned);
__gcc_v16hi __builtin_ia32_paddw256_mask(__gcc_v16hi, __gcc_v16hi, __gcc_v16hi, unsigned short);
__gcc_v8si __builtin_ia32_paddd256_mask(__gcc_v8si, __gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v4di __builtin_ia32_paddq256_mask(__gcc_v4di, __gcc_v4di, __gcc_v4di, unsigned char);
__gcc_v32qi __builtin_ia32_paddsb256_mask(__gcc_v32qi, __gcc_v32qi, __gcc_v32qi, unsigned);
__gcc_v16hi __builtin_ia32_paddsw256_mask(__gcc_v16hi, __gcc_v16hi, __gcc_v16hi, unsigned short);
__gcc_v32qi __builtin_ia32_paddusb256_mask(__gcc_v32qi, __gcc_v32qi, __gcc_v32qi, unsigned);
__gcc_v16hi __builtin_ia32_paddusw256_mask(__gcc_v16hi, __gcc_v16hi, __gcc_v16hi, unsigned short);
__gcc_v32qi __builtin_ia32_psubb256_mask(__gcc_v32qi, __gcc_v32qi, __gcc_v32qi, unsigned);
__gcc_v16hi __builtin_ia32_psubw256_mask(__gcc_v16hi, __gcc_v16hi, __gcc_v16hi, unsigned short);
__gcc_v8si __builtin_ia32_psubd256_mask(__gcc_v8si, __gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v4di __builtin_ia32_psubq256_mask(__gcc_v4di, __gcc_v4di, __gcc_v4di, unsigned char);
__gcc_v32qi __builtin_ia32_psubsb256_mask(__gcc_v32qi, __gcc_v32qi, __gcc_v32qi, unsigned);
__gcc_v16hi __builtin_ia32_psubsw256_mask(__gcc_v16hi, __gcc_v16hi, __gcc_v16hi, unsigned short);
__gcc_v32qi __builtin_ia32_psubusb256_mask(__gcc_v32qi, __gcc_v32qi, __gcc_v32qi, unsigned);
__gcc_v16hi __builtin_ia32_psubusw256_mask(__gcc_v16hi, __gcc_v16hi, __gcc_v16hi, unsigned short);
__gcc_v4df __builtin_ia32_shuf_f64x2_256_mask(__gcc_v4df, __gcc_v4df, int, __gcc_v4df, unsigned char);
__gcc_v4di __builtin_ia32_shuf_i64x2_256_mask(__gcc_v4di, __gcc_v4di, int, __gcc_v4di, unsigned char);
__gcc_v8si __builtin_ia32_shuf_i32x4_256_mask(__gcc_v8si, __gcc_v8si, int, __gcc_v8si, unsigned char);
__gcc_v8sf __builtin_ia32_shuf_f32x4_256_mask(__gcc_v8sf, __gcc_v8sf, int, __gcc_v8sf, unsigned char);
__gcc_v16qi __builtin_ia32_pmovwb128_mask(__gcc_v8hi, __gcc_v16qi, unsigned char);
__gcc_v16qi __builtin_ia32_pmovwb256_mask(__gcc_v16hi, __gcc_v16qi, unsigned short);
__gcc_v16qi __builtin_ia32_pmovswb128_mask(__gcc_v8hi, __gcc_v16qi, unsigned char);
__gcc_v16qi __builtin_ia32_pmovswb256_mask(__gcc_v16hi, __gcc_v16qi, unsigned short);
__gcc_v16qi __builtin_ia32_pmovuswb128_mask(__gcc_v8hi, __gcc_v16qi, unsigned char);
__gcc_v16qi __builtin_ia32_pmovuswb256_mask(__gcc_v16hi, __gcc_v16qi, unsigned short);
__gcc_v16qi __builtin_ia32_pmovdb128_mask(__gcc_v4si, __gcc_v16qi, unsigned char);
__gcc_v16qi __builtin_ia32_pmovdb256_mask(__gcc_v8si, __gcc_v16qi, unsigned char);
__gcc_v16qi __builtin_ia32_pmovsdb128_mask(__gcc_v4si, __gcc_v16qi, unsigned char);
__gcc_v16qi __builtin_ia32_pmovsdb256_mask(__gcc_v8si, __gcc_v16qi, unsigned char);
__gcc_v16qi __builtin_ia32_pmovusdb128_mask(__gcc_v4si, __gcc_v16qi, unsigned char);
__gcc_v16qi __builtin_ia32_pmovusdb256_mask(__gcc_v8si, __gcc_v16qi, unsigned char);
__gcc_v8hi __builtin_ia32_pmovdw128_mask(__gcc_v4si, __gcc_v8hi, unsigned char);
__gcc_v8hi __builtin_ia32_pmovdw256_mask(__gcc_v8si, __gcc_v8hi, unsigned char);
__gcc_v8hi __builtin_ia32_pmovsdw128_mask(__gcc_v4si, __gcc_v8hi, unsigned char);
__gcc_v8hi __builtin_ia32_pmovsdw256_mask(__gcc_v8si, __gcc_v8hi, unsigned char);
__gcc_v8hi __builtin_ia32_pmovusdw128_mask(__gcc_v4si, __gcc_v8hi, unsigned char);
__gcc_v8hi __builtin_ia32_pmovusdw256_mask(__gcc_v8si, __gcc_v8hi, unsigned char);
__gcc_v16qi __builtin_ia32_pmovqb128_mask(__gcc_v2di, __gcc_v16qi, unsigned char);
__gcc_v16qi __builtin_ia32_pmovqb256_mask(__gcc_v4di, __gcc_v16qi, unsigned char);
__gcc_v16qi __builtin_ia32_pmovsqb128_mask(__gcc_v2di, __gcc_v16qi, unsigned char);
__gcc_v16qi __builtin_ia32_pmovsqb256_mask(__gcc_v4di, __gcc_v16qi, unsigned char);
__gcc_v16qi __builtin_ia32_pmovusqb128_mask(__gcc_v2di, __gcc_v16qi, unsigned char);
__gcc_v16qi __builtin_ia32_pmovusqb256_mask(__gcc_v4di, __gcc_v16qi, unsigned char);
__gcc_v8hi __builtin_ia32_pmovqw128_mask(__gcc_v2di, __gcc_v8hi, unsigned char);
__gcc_v8hi __builtin_ia32_pmovqw256_mask(__gcc_v4di, __gcc_v8hi, unsigned char);
__gcc_v8hi __builtin_ia32_pmovsqw128_mask(__gcc_v2di, __gcc_v8hi, unsigned char);
__gcc_v8hi __builtin_ia32_pmovsqw256_mask(__gcc_v4di, __gcc_v8hi, unsigned char);
__gcc_v8hi __builtin_ia32_pmovusqw128_mask(__gcc_v2di, __gcc_v8hi, unsigned char);
__gcc_v8hi __builtin_ia32_pmovusqw256_mask(__gcc_v4di, __gcc_v8hi, unsigned char);
__gcc_v4si __builtin_ia32_pmovqd128_mask(__gcc_v2di, __gcc_v4si, unsigned char);
__gcc_v4si __builtin_ia32_pmovqd256_mask(__gcc_v4di, __gcc_v4si, unsigned char);
__gcc_v4si __builtin_ia32_pmovsqd128_mask(__gcc_v2di, __gcc_v4si, unsigned char);
__gcc_v4si __builtin_ia32_pmovsqd256_mask(__gcc_v4di, __gcc_v4si, unsigned char);
__gcc_v4si __builtin_ia32_pmovusqd128_mask(__gcc_v2di, __gcc_v4si, unsigned char);
__gcc_v4si __builtin_ia32_pmovusqd256_mask(__gcc_v4di, __gcc_v4si, unsigned char);
__gcc_v4df __builtin_ia32_rangepd256_mask(__gcc_v4df, __gcc_v4df, int, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_rangepd128_mask(__gcc_v2df, __gcc_v2df, int, __gcc_v2df, unsigned char);
__gcc_v8sf __builtin_ia32_rangeps256_mask(__gcc_v8sf, __gcc_v8sf, int, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_rangeps128_mask(__gcc_v4sf, __gcc_v4sf, int, __gcc_v4sf, unsigned char);
__gcc_v8sf __builtin_ia32_getexpps256_mask(__gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v4df __builtin_ia32_getexppd256_mask(__gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v4sf __builtin_ia32_getexpps128_mask(__gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v2df __builtin_ia32_getexppd128_mask(__gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v4df __builtin_ia32_fixupimmpd256_mask(__gcc_v4df, __gcc_v4df, __gcc_v4di, int, unsigned char);
__gcc_v4df __builtin_ia32_fixupimmpd256_maskz(__gcc_v4df, __gcc_v4df, __gcc_v4di, int, unsigned char);
__gcc_v8sf __builtin_ia32_fixupimmps256_mask(__gcc_v8sf, __gcc_v8sf, __gcc_v8si, int, unsigned char);
__gcc_v8sf __builtin_ia32_fixupimmps256_maskz(__gcc_v8sf, __gcc_v8sf, __gcc_v8si, int, unsigned char);
__gcc_v2df __builtin_ia32_fixupimmpd128_mask(__gcc_v2df, __gcc_v2df, __gcc_v2di, int, unsigned char);
__gcc_v2df __builtin_ia32_fixupimmpd128_maskz(__gcc_v2df, __gcc_v2df, __gcc_v2di, int, unsigned char);
__gcc_v4sf __builtin_ia32_fixupimmps128_mask(__gcc_v4sf, __gcc_v4sf, __gcc_v4si, int, unsigned char);
__gcc_v4sf __builtin_ia32_fixupimmps128_maskz(__gcc_v4sf, __gcc_v4sf, __gcc_v4si, int, unsigned char);
__gcc_v4di __builtin_ia32_pabsq256_mask(__gcc_v4di, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_pabsq128_mask(__gcc_v2di, __gcc_v2di, unsigned char);
__gcc_v8si __builtin_ia32_pabsd256_mask(__gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_pabsd128_mask(__gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v16hi __builtin_ia32_pmulhrsw256_mask(__gcc_v16hi, __gcc_v16hi, __gcc_v16hi, unsigned short);
__gcc_v8hi __builtin_ia32_pmulhrsw128_mask(__gcc_v8hi, __gcc_v8hi, __gcc_v8hi, unsigned char);
__gcc_v8hi __builtin_ia32_pmulhuw128_mask(__gcc_v8hi, __gcc_v8hi, __gcc_v8hi, unsigned char);
__gcc_v16hi __builtin_ia32_pmulhuw256_mask(__gcc_v16hi, __gcc_v16hi, __gcc_v16hi, unsigned short);
__gcc_v16hi __builtin_ia32_pmulhw256_mask(__gcc_v16hi, __gcc_v16hi, __gcc_v16hi, unsigned short);
__gcc_v8hi __builtin_ia32_pmulhw128_mask(__gcc_v8hi, __gcc_v8hi, __gcc_v8hi, unsigned char);
__gcc_v16hi __builtin_ia32_pmullw256_mask(__gcc_v16hi, __gcc_v16hi, __gcc_v16hi, unsigned short);
__gcc_v8hi __builtin_ia32_pmullw128_mask(__gcc_v8hi, __gcc_v8hi, __gcc_v8hi, unsigned char);
__gcc_v4di __builtin_ia32_pmullq256_mask(__gcc_v4di, __gcc_v4di, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_pmullq128_mask(__gcc_v2di, __gcc_v2di, __gcc_v2di, unsigned char);
__gcc_v4df __builtin_ia32_andpd256_mask(__gcc_v4df, __gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_andpd128_mask(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v8sf __builtin_ia32_andps256_mask(__gcc_v8sf, __gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_andps128_mask(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v4df __builtin_ia32_andnpd256_mask(__gcc_v4df, __gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_andnpd128_mask(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v8sf __builtin_ia32_andnps256_mask(__gcc_v8sf, __gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_andnps128_mask(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v8si __builtin_ia32_pandd256_mask(__gcc_v8si, __gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_pandd128_mask(__gcc_v4si, __gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v4di __builtin_ia32_pandq256_mask(__gcc_v4di, __gcc_v4di, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_pandq128_mask(__gcc_v2di, __gcc_v2di, __gcc_v2di, unsigned char);
__gcc_v8si __builtin_ia32_pandnd256_mask(__gcc_v8si, __gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_pandnd128_mask(__gcc_v4si, __gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v4di __builtin_ia32_pandnq256_mask(__gcc_v4di, __gcc_v4di, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_pandnq128_mask(__gcc_v2di, __gcc_v2di, __gcc_v2di, unsigned char);
__gcc_v8si __builtin_ia32_pord256_mask(__gcc_v8si, __gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_pord128_mask(__gcc_v4si, __gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v4di __builtin_ia32_porq256_mask(__gcc_v4di, __gcc_v4di, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_porq128_mask(__gcc_v2di, __gcc_v2di, __gcc_v2di, unsigned char);
__gcc_v8si __builtin_ia32_pxord256_mask(__gcc_v8si, __gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_pxord128_mask(__gcc_v4si, __gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v4di __builtin_ia32_pxorq256_mask(__gcc_v4di, __gcc_v4di, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_pxorq128_mask(__gcc_v2di, __gcc_v2di, __gcc_v2di, unsigned char);
__gcc_v32qi __builtin_ia32_packsswb256_mask(__gcc_v16hi, __gcc_v16hi, __gcc_v32qi, unsigned);
__gcc_v16qi __builtin_ia32_packsswb128_mask(__gcc_v8hi, __gcc_v8hi, __gcc_v16qi, unsigned short);
__gcc_v32qi __builtin_ia32_packuswb256_mask(__gcc_v16hi, __gcc_v16hi, __gcc_v32qi, unsigned);
__gcc_v16qi __builtin_ia32_packuswb128_mask(__gcc_v8hi, __gcc_v8hi, __gcc_v16qi, unsigned short);
__gcc_v8sf __builtin_ia32_rndscaleps_256_mask(__gcc_v8sf, int, __gcc_v8sf, unsigned char);
__gcc_v4df __builtin_ia32_rndscalepd_256_mask(__gcc_v4df, int, __gcc_v4df, unsigned char);
__gcc_v4sf __builtin_ia32_rndscaleps_128_mask(__gcc_v4sf, int, __gcc_v4sf, unsigned char);
__gcc_v2df __builtin_ia32_rndscalepd_128_mask(__gcc_v2df, int, __gcc_v2df, unsigned char);
__gcc_v4di __builtin_ia32_pternlogq256_mask(__gcc_v4di, __gcc_v4di, __gcc_v4di, int, unsigned char);
__gcc_v4di __builtin_ia32_pternlogq256_maskz(__gcc_v4di, __gcc_v4di, __gcc_v4di, int, unsigned char);
__gcc_v8si __builtin_ia32_pternlogd256_mask(__gcc_v8si, __gcc_v8si, __gcc_v8si, int, unsigned char);
__gcc_v8si __builtin_ia32_pternlogd256_maskz(__gcc_v8si, __gcc_v8si, __gcc_v8si, int, unsigned char);
__gcc_v2di __builtin_ia32_pternlogq128_mask(__gcc_v2di, __gcc_v2di, __gcc_v2di, int, unsigned char);
__gcc_v2di __builtin_ia32_pternlogq128_maskz(__gcc_v2di, __gcc_v2di, __gcc_v2di, int, unsigned char);
__gcc_v4si __builtin_ia32_pternlogd128_mask(__gcc_v4si, __gcc_v4si, __gcc_v4si, int, unsigned char);
__gcc_v4si __builtin_ia32_pternlogd128_maskz(__gcc_v4si, __gcc_v4si, __gcc_v4si, int, unsigned char);
__gcc_v4df __builtin_ia32_scalefpd256_mask(__gcc_v4df, __gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v8sf __builtin_ia32_scalefps256_mask(__gcc_v8sf, __gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v2df __builtin_ia32_scalefpd128_mask(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v4sf __builtin_ia32_scalefps128_mask(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v4df __builtin_ia32_vfmaddpd256_mask(__gcc_v4df, __gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v4df __builtin_ia32_vfmaddpd256_mask3(__gcc_v4df, __gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v4df __builtin_ia32_vfmaddpd256_maskz(__gcc_v4df, __gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_vfmaddpd128_mask(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v2df __builtin_ia32_vfmaddpd128_mask3(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v2df __builtin_ia32_vfmaddpd128_maskz(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v8sf __builtin_ia32_vfmaddps256_mask(__gcc_v8sf, __gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v8sf __builtin_ia32_vfmaddps256_mask3(__gcc_v8sf, __gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v8sf __builtin_ia32_vfmaddps256_maskz(__gcc_v8sf, __gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_vfmaddps128_mask(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v4sf __builtin_ia32_vfmaddps128_mask3(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v4sf __builtin_ia32_vfmaddps128_maskz(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v4df __builtin_ia32_vfmsubpd256_mask3(__gcc_v4df, __gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_vfmsubpd128_mask3(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v8sf __builtin_ia32_vfmsubps256_mask3(__gcc_v8sf, __gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_vfmsubps128_mask3(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v4df __builtin_ia32_vfnmaddpd256_mask(__gcc_v4df, __gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_vfnmaddpd128_mask(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v8sf __builtin_ia32_vfnmaddps256_mask(__gcc_v8sf, __gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_vfnmaddps128_mask(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v4df __builtin_ia32_vfnmsubpd256_mask(__gcc_v4df, __gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v4df __builtin_ia32_vfnmsubpd256_mask3(__gcc_v4df, __gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_vfnmsubpd128_mask(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v2df __builtin_ia32_vfnmsubpd128_mask3(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v8sf __builtin_ia32_vfnmsubps256_mask(__gcc_v8sf, __gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v8sf __builtin_ia32_vfnmsubps256_mask3(__gcc_v8sf, __gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_vfnmsubps128_mask(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v4sf __builtin_ia32_vfnmsubps128_mask3(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v4df __builtin_ia32_vfmaddsubpd256_mask(__gcc_v4df, __gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v4df __builtin_ia32_vfmaddsubpd256_mask3(__gcc_v4df, __gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v4df __builtin_ia32_vfmaddsubpd256_maskz(__gcc_v4df, __gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_vfmaddsubpd128_mask(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v2df __builtin_ia32_vfmaddsubpd128_mask3(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v2df __builtin_ia32_vfmaddsubpd128_maskz(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v8sf __builtin_ia32_vfmaddsubps256_mask(__gcc_v8sf, __gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v8sf __builtin_ia32_vfmaddsubps256_mask3(__gcc_v8sf, __gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v8sf __builtin_ia32_vfmaddsubps256_maskz(__gcc_v8sf, __gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_vfmaddsubps128_mask(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v4sf __builtin_ia32_vfmaddsubps128_mask3(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v4sf __builtin_ia32_vfmaddsubps128_maskz(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v4df __builtin_ia32_vfmsubaddpd256_mask3(__gcc_v4df, __gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_vfmsubaddpd128_mask3(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v8sf __builtin_ia32_vfmsubaddps256_mask3(__gcc_v8sf, __gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_vfmsubaddps128_mask3(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v4df __builtin_ia32_insertf64x2_256_mask(__gcc_v4df, __gcc_v2df, int, __gcc_v4df, unsigned char);
__gcc_v4di __builtin_ia32_inserti64x2_256_mask(__gcc_v4di, __gcc_v2di, int, __gcc_v4di, unsigned char);
__gcc_v16hi __builtin_ia32_psrav16hi_mask(__gcc_v16hi, __gcc_v16hi, __gcc_v16hi, unsigned short);
__gcc_v8hi __builtin_ia32_psrav8hi_mask(__gcc_v8hi, __gcc_v8hi, __gcc_v8hi, unsigned char);
__gcc_v16hi __builtin_ia32_pmaddubsw256_mask(__gcc_v32qi, __gcc_v32qi, __gcc_v16hi, unsigned short);
__gcc_v8hi __builtin_ia32_pmaddubsw128_mask(__gcc_v16qi, __gcc_v16qi, __gcc_v8hi, unsigned char);
__gcc_v8si __builtin_ia32_pmaddwd256_mask(__gcc_v16hi, __gcc_v16hi, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_pmaddwd128_mask(__gcc_v8hi, __gcc_v8hi, __gcc_v4si, unsigned char);
__gcc_v16hi __builtin_ia32_psrlv16hi_mask(__gcc_v16hi, __gcc_v16hi, __gcc_v16hi, unsigned short);
__gcc_v8hi __builtin_ia32_psrlv8hi_mask(__gcc_v8hi, __gcc_v8hi, __gcc_v8hi, unsigned char);
__gcc_v8si __builtin_ia32_cvtps2dq256_mask(__gcc_v8sf, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_cvtps2dq128_mask(__gcc_v4sf, __gcc_v4si, unsigned char);
__gcc_v8si __builtin_ia32_cvtps2udq256_mask(__gcc_v8sf, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_cvtps2udq128_mask(__gcc_v4sf, __gcc_v4si, unsigned char);
__gcc_v4di __builtin_ia32_cvtps2qq256_mask(__gcc_v4sf, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_cvtps2qq128_mask(__gcc_v4sf, __gcc_v2di, unsigned char);
__gcc_v4di __builtin_ia32_cvtps2uqq256_mask(__gcc_v4sf, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_cvtps2uqq128_mask(__gcc_v4sf, __gcc_v2di, unsigned char);
__gcc_v8sf __builtin_ia32_getmantps256_mask(__gcc_v8sf, int, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_getmantps128_mask(__gcc_v4sf, int, __gcc_v4sf, unsigned char);
__gcc_v4df __builtin_ia32_getmantpd256_mask(__gcc_v4df, int, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_getmantpd128_mask(__gcc_v2df, int, __gcc_v2df, unsigned char);
__gcc_v4df __builtin_ia32_movddup256_mask(__gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_movddup128_mask(__gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v8sf __builtin_ia32_movshdup256_mask(__gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_movshdup128_mask(__gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v8sf __builtin_ia32_movsldup256_mask(__gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_movsldup128_mask(__gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v4sf __builtin_ia32_cvtqq2ps256_mask(__gcc_v4di, __gcc_v4sf, unsigned char);
__gcc_v4sf __builtin_ia32_cvtqq2ps128_mask(__gcc_v2di, __gcc_v4sf, unsigned char);
__gcc_v4sf __builtin_ia32_cvtuqq2ps256_mask(__gcc_v4di, __gcc_v4sf, unsigned char);
__gcc_v4sf __builtin_ia32_cvtuqq2ps128_mask(__gcc_v2di, __gcc_v4sf, unsigned char);
__gcc_v4df __builtin_ia32_cvtqq2pd256_mask(__gcc_v4di, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_cvtqq2pd128_mask(__gcc_v2di, __gcc_v2df, unsigned char);
__gcc_v4df __builtin_ia32_cvtuqq2pd256_mask(__gcc_v4di, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_cvtuqq2pd128_mask(__gcc_v2di, __gcc_v2df, unsigned char);
__gcc_v4di __builtin_ia32_vpermt2varq256_mask(__gcc_v4di, __gcc_v4di, __gcc_v4di, unsigned char);
__gcc_v4di __builtin_ia32_vpermt2varq256_maskz(__gcc_v4di, __gcc_v4di, __gcc_v4di, unsigned char);
__gcc_v8si __builtin_ia32_vpermt2vard256_mask(__gcc_v8si, __gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v8si __builtin_ia32_vpermt2vard256_maskz(__gcc_v8si, __gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v4di __builtin_ia32_vpermi2varq256_mask(__gcc_v4di, __gcc_v4di, __gcc_v4di, unsigned char);
__gcc_v8si __builtin_ia32_vpermi2vard256_mask(__gcc_v8si, __gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v4df __builtin_ia32_vpermt2varpd256_mask(__gcc_v4di, __gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v4df __builtin_ia32_vpermt2varpd256_maskz(__gcc_v4di, __gcc_v4df, __gcc_v4df, unsigned char);
__gcc_v8sf __builtin_ia32_vpermt2varps256_mask(__gcc_v8si, __gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v8sf __builtin_ia32_vpermt2varps256_maskz(__gcc_v8si, __gcc_v8sf, __gcc_v8sf, unsigned char);
__gcc_v4df __builtin_ia32_vpermi2varpd256_mask(__gcc_v4df, __gcc_v4di, __gcc_v4df, unsigned char);
__gcc_v8sf __builtin_ia32_vpermi2varps256_mask(__gcc_v8sf, __gcc_v8si, __gcc_v8sf, unsigned char);
__gcc_v2di __builtin_ia32_vpermt2varq128_mask(__gcc_v2di, __gcc_v2di, __gcc_v2di, unsigned char);
__gcc_v2di __builtin_ia32_vpermt2varq128_maskz(__gcc_v2di, __gcc_v2di, __gcc_v2di, unsigned char);
__gcc_v4si __builtin_ia32_vpermt2vard128_mask(__gcc_v4si, __gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v4si __builtin_ia32_vpermt2vard128_maskz(__gcc_v4si, __gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v2di __builtin_ia32_vpermi2varq128_mask(__gcc_v2di, __gcc_v2di, __gcc_v2di, unsigned char);
__gcc_v4si __builtin_ia32_vpermi2vard128_mask(__gcc_v4si, __gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v2df __builtin_ia32_vpermt2varpd128_mask(__gcc_v2di, __gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v2df __builtin_ia32_vpermt2varpd128_maskz(__gcc_v2di, __gcc_v2df, __gcc_v2df, unsigned char);
__gcc_v4sf __builtin_ia32_vpermt2varps128_mask(__gcc_v4si, __gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v4sf __builtin_ia32_vpermt2varps128_maskz(__gcc_v4si, __gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v2df __builtin_ia32_vpermi2varpd128_mask(__gcc_v2df, __gcc_v2di, __gcc_v2df, unsigned char);
__gcc_v4sf __builtin_ia32_vpermi2varps128_mask(__gcc_v4sf, __gcc_v4si, __gcc_v4sf, unsigned char);
__gcc_v32qi __builtin_ia32_pshufb256_mask(__gcc_v32qi, __gcc_v32qi, __gcc_v32qi, unsigned);
__gcc_v16qi __builtin_ia32_pshufb128_mask(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, unsigned short);
__gcc_v16hi __builtin_ia32_pshufhw256_mask(__gcc_v16hi, int, __gcc_v16hi, unsigned short);
__gcc_v8hi __builtin_ia32_pshufhw128_mask(__gcc_v8hi, int, __gcc_v8hi, unsigned char);
__gcc_v16hi __builtin_ia32_pshuflw256_mask(__gcc_v16hi, int, __gcc_v16hi, unsigned short);
__gcc_v8hi __builtin_ia32_pshuflw128_mask(__gcc_v8hi, int, __gcc_v8hi, unsigned char);
__gcc_v8si __builtin_ia32_pshufd256_mask(__gcc_v8si, int, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_pshufd128_mask(__gcc_v4si, int, __gcc_v4si, unsigned char);
__gcc_v4df __builtin_ia32_shufpd256_mask(__gcc_v4df, __gcc_v4df, int, __gcc_v4df, unsigned char);
__gcc_v2df __builtin_ia32_shufpd128_mask(__gcc_v2df, __gcc_v2df, int, __gcc_v2df, unsigned char);
__gcc_v8sf __builtin_ia32_shufps256_mask(__gcc_v8sf, __gcc_v8sf, int, __gcc_v8sf, unsigned char);
__gcc_v4sf __builtin_ia32_shufps128_mask(__gcc_v4sf, __gcc_v4sf, int, __gcc_v4sf, unsigned char);
__gcc_v4di __builtin_ia32_prolvq256_mask(__gcc_v4di, __gcc_v4di, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_prolvq128_mask(__gcc_v2di, __gcc_v2di, __gcc_v2di, unsigned char);
__gcc_v4di __builtin_ia32_prolq256_mask(__gcc_v4di, int, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_prolq128_mask(__gcc_v2di, int, __gcc_v2di, unsigned char);
__gcc_v4di __builtin_ia32_prorvq256_mask(__gcc_v4di, __gcc_v4di, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_prorvq128_mask(__gcc_v2di, __gcc_v2di, __gcc_v2di, unsigned char);
__gcc_v4di __builtin_ia32_prorq256_mask(__gcc_v4di, int, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_prorq128_mask(__gcc_v2di, int, __gcc_v2di, unsigned char);
__gcc_v2di __builtin_ia32_psravq128_mask(__gcc_v2di, __gcc_v2di, __gcc_v2di, unsigned char);
__gcc_v4di __builtin_ia32_psravq256_mask(__gcc_v4di, __gcc_v4di, __gcc_v4di, unsigned char);
__gcc_v4di __builtin_ia32_psllv4di_mask(__gcc_v4di, __gcc_v4di, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_psllv2di_mask(__gcc_v2di, __gcc_v2di, __gcc_v2di, unsigned char);
__gcc_v8si __builtin_ia32_psllv8si_mask(__gcc_v8si, __gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_psllv4si_mask(__gcc_v4si, __gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v8si __builtin_ia32_psrav8si_mask(__gcc_v8si, __gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_psrav4si_mask(__gcc_v4si, __gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v4di __builtin_ia32_psrlv4di_mask(__gcc_v4di, __gcc_v4di, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_psrlv2di_mask(__gcc_v2di, __gcc_v2di, __gcc_v2di, unsigned char);
__gcc_v8si __builtin_ia32_psrlv8si_mask(__gcc_v8si, __gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_psrlv4si_mask(__gcc_v4si, __gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v8si __builtin_ia32_prorvd256_mask(__gcc_v8si, __gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v8si __builtin_ia32_prolvd256_mask(__gcc_v8si, __gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v8si __builtin_ia32_prord256_mask(__gcc_v8si, int, __gcc_v8si, unsigned char);
__gcc_v8si __builtin_ia32_prold256_mask(__gcc_v8si, int, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_prorvd128_mask(__gcc_v4si, __gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v4si __builtin_ia32_prolvd128_mask(__gcc_v4si, __gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v4si __builtin_ia32_prord128_mask(__gcc_v4si, int, __gcc_v4si, unsigned char);
__gcc_v4si __builtin_ia32_prold128_mask(__gcc_v4si, int, __gcc_v4si, unsigned char);
char __builtin_ia32_fpclasspd256_mask(__gcc_v4df, int, unsigned char);
char __builtin_ia32_fpclasspd128_mask(__gcc_v2df, int, unsigned char);
char __builtin_ia32_fpclasssd(__gcc_v2df, int);
char __builtin_ia32_fpclassps256_mask(__gcc_v8sf, int, unsigned char);
char __builtin_ia32_fpclassps128_mask(__gcc_v4sf, int, unsigned char);
char __builtin_ia32_fpclassss(__gcc_v4sf, int);
unsigned short __builtin_ia32_cvtb2mask128(__gcc_v16qi);
unsigned __builtin_ia32_cvtb2mask256(__gcc_v32qi);
unsigned char __builtin_ia32_cvtw2mask128(__gcc_v8hi);
unsigned short __builtin_ia32_cvtw2mask256(__gcc_v16hi);
unsigned char __builtin_ia32_cvtd2mask128(__gcc_v4si);
unsigned char __builtin_ia32_cvtd2mask256(__gcc_v8si);
unsigned char __builtin_ia32_cvtq2mask128(__gcc_v2di);
unsigned char __builtin_ia32_cvtq2mask256(__gcc_v4di);
__gcc_v16qi __builtin_ia32_cvtmask2b128(unsigned short);
__gcc_v32qi __builtin_ia32_cvtmask2b256(unsigned);
__gcc_v8hi __builtin_ia32_cvtmask2w128(unsigned char);
__gcc_v16hi __builtin_ia32_cvtmask2w256(unsigned short);
__gcc_v4si __builtin_ia32_cvtmask2d128(unsigned char);
__gcc_v8si __builtin_ia32_cvtmask2d256(unsigned char);
__gcc_v2di __builtin_ia32_cvtmask2q128(unsigned char);
__gcc_v4di __builtin_ia32_cvtmask2q256(unsigned char);
unsigned short __builtin_ia32_pcmpeqb128_mask(__gcc_v16qi, __gcc_v16qi, unsigned short);
unsigned __builtin_ia32_pcmpeqb256_mask(__gcc_v32qi, __gcc_v32qi, unsigned);
unsigned char __builtin_ia32_pcmpeqw128_mask(__gcc_v8hi, __gcc_v8hi, unsigned char);
unsigned short __builtin_ia32_pcmpeqw256_mask(__gcc_v16hi, __gcc_v16hi, unsigned short);
unsigned char __builtin_ia32_pcmpeqd128_mask(__gcc_v4si, __gcc_v4si, unsigned char);
unsigned char __builtin_ia32_pcmpeqd256_mask(__gcc_v8si, __gcc_v8si, unsigned char);
unsigned char __builtin_ia32_pcmpeqq128_mask(__gcc_v2di, __gcc_v2di, unsigned char);
unsigned char __builtin_ia32_pcmpeqq256_mask(__gcc_v4di, __gcc_v4di, unsigned char);
unsigned short __builtin_ia32_pcmpgtb128_mask(__gcc_v16qi, __gcc_v16qi, unsigned short);
unsigned __builtin_ia32_pcmpgtb256_mask(__gcc_v32qi, __gcc_v32qi, unsigned);
unsigned char __builtin_ia32_pcmpgtw128_mask(__gcc_v8hi, __gcc_v8hi, unsigned char);
unsigned short __builtin_ia32_pcmpgtw256_mask(__gcc_v16hi, __gcc_v16hi, unsigned short);
unsigned char __builtin_ia32_pcmpgtd128_mask(__gcc_v4si, __gcc_v4si, unsigned char);
unsigned char __builtin_ia32_pcmpgtd256_mask(__gcc_v8si, __gcc_v8si, unsigned char);
unsigned char __builtin_ia32_pcmpgtq128_mask(__gcc_v2di, __gcc_v2di, unsigned char);
unsigned char __builtin_ia32_pcmpgtq256_mask(__gcc_v4di, __gcc_v4di, unsigned char);
unsigned short __builtin_ia32_ptestmb128(__gcc_v16qi, __gcc_v16qi, unsigned short);
unsigned __builtin_ia32_ptestmb256(__gcc_v32qi, __gcc_v32qi, unsigned);
unsigned char __builtin_ia32_ptestmw128(__gcc_v8hi, __gcc_v8hi, unsigned char);
unsigned short __builtin_ia32_ptestmw256(__gcc_v16hi, __gcc_v16hi, unsigned short);
unsigned char __builtin_ia32_ptestmd128(__gcc_v4si, __gcc_v4si, unsigned char);
unsigned char __builtin_ia32_ptestmd256(__gcc_v8si, __gcc_v8si, unsigned char);
unsigned char __builtin_ia32_ptestmq128(__gcc_v2di, __gcc_v2di, unsigned char);
unsigned char __builtin_ia32_ptestmq256(__gcc_v4di, __gcc_v4di, unsigned char);
unsigned short __builtin_ia32_ptestnmb128(__gcc_v16qi, __gcc_v16qi, unsigned short);
unsigned __builtin_ia32_ptestnmb256(__gcc_v32qi, __gcc_v32qi, unsigned);
unsigned char __builtin_ia32_ptestnmw128(__gcc_v8hi, __gcc_v8hi, unsigned char);
unsigned short __builtin_ia32_ptestnmw256(__gcc_v16hi, __gcc_v16hi, unsigned short);
unsigned char __builtin_ia32_ptestnmd128(__gcc_v4si, __gcc_v4si, unsigned char);
unsigned char __builtin_ia32_ptestnmd256(__gcc_v8si, __gcc_v8si, unsigned char);
unsigned char __builtin_ia32_ptestnmq128(__gcc_v2di, __gcc_v2di, unsigned char);
unsigned char __builtin_ia32_ptestnmq256(__gcc_v4di, __gcc_v4di, unsigned char);
// clang-format on
