typedef void* __builtin_va_list;
void __builtin_va_start(void *ap, ...);
void __builtin_va_end(void *ap);
void __builtin_va_copy(__builtin_va_list dest, __builtin_va_list src);
int __builtin_constant_p(int);
int __builtin_abs(int);
long int __builtin_labs(long);
double __builtin_cos(double);
float __builtin_cosf(float);
double __builtin_fabs(double);
float __builtin_fabsf(float);
int __builtin_memcmp(const void *s1, const void *s2, unsigned n);
void *__builtin_memcpy(void *dest, const void *src, unsigned n);
void *__builtin___memcpy_chk(void *dest, const void *src, unsigned n, __CPROVER_size_t size);
char *__builtin___memmove_chk(void *dest, const void *src, unsigned n, __CPROVER_size_t size);
double __builtin_sin(double);
float __builtin_sinf(float);
double __builtin_sqrt(double);
float __builtin_sqrtf(float);
int __builtin_strcmp(const char *s1, const char *s2);
unsigned __builtin_strlen(const char *s);
int __builtin_strncmp(const char *s1, const char *s2, unsigned n);
void __builtin_abort();
void __builtin_prefetch(void *, ...);
int __builtin_printf(const char *fmt, ...);
int __builtin_fprintf(void *stream, const char *fmt, ...);
int __builtin_fscanf(void *stream, const char *fmt, ...);
int __builtin_scanf(const char *str, const char *fmt, ...);
int __builtin_fputs(const char *s, void *stream);
int __builtin_vsnprintf(char * restrict str, __CPROVER_size_t size, const char * restrict format, __builtin_va_list ap);
long __builtin_expect(long, long);
void *__builtin_memset(void *s, int c, unsigned n);
void *__builtin___memset_chk(void *s, int c, unsigned n, __CPROVER_size_t size);
void *__builtin_memchr(const void *s, int c, __CPROVER_size_t n);
void *__builtin_memmove(void *s1, const void *s2, __CPROVER_size_t n);
char *__builtin_strcat(char *dest, const char *src);
char *__builtin___strcat_chk(char *dest, const char *src, __CPROVER_size_t size);
char *__builtin_strcpy(char *dest, const char *src);
char *__builtin___strcpy_chk(char *dest, const char *src, __CPROVER_size_t size);
char *__builtin_strncpy(char *dest, const char *src, unsigned n);
char *__builtin___strncpy_chk(char *dest, const char *src, unsigned n, __CPROVER_size_t size);
char *__builtin___stpcpy(char *s1, const char *s2);
char *__builtin___stpncpy_chk(char *s1, const char *s2, unsigned n, __CPROVER_size_t size);
void __builtin_exit(int status);
char *__builtin_strchr(const char *s, int c);
unsigned __builtin_strspn(const char *s, const char *accept);
unsigned __builtin_strcspn(const char *s, const char *reject);
char *__builtin_strstr(const char *a, const char *b);
char *__builtin_strpbrk(const char *s, const char *accept);
char *__builtin_strrchr(const char *s, int c);
char *__builtin_strncat(char *dest, const char *src, unsigned n);
char *__builtin___strncat_chk(char *dest, const char *src, unsigned n, __CPROVER_size_t size);
char *__builtin___stpcpy_chk(char *dest, const char *src, __CPROVER_size_t size);
void *__builtin_alloca(unsigned s);
int __builtin_ffs(int i);
char *__builtin_index(const char *s, int c);
char *__builtin_rindex(const char *s, int c);
int __builtin_bcmp(const void *s1, const void *s2, unsigned n);
void __builtin_bzero(void *s, unsigned n);
long double __builtin_sinl(long double x);
long double __builtin_cosl(long double x);
long double __builtin_sqrtl(long double x);
long double __builtin_fabsl(long double x);
int __builtin_popcount(unsigned int x);
int __builtin_popcountll(unsigned long long int x);
float __builtin_huge_valf();
double __builtin_huge_val();
float __builtin_inff();
double __builtin_inf();
float __builtin_nanf(const char *);
double __builtin_nan(const char *);
float __builtin_nansf(const char *);
double __builtin_nans(const char *);
long double __builtin_infl();
unsigned __builtin_object_size();
void *__builtin_return_address(unsigned level);
void *__builtin_extract_return_addr(void *);
int __builtin_choose_expr(_Bool, ...);
int __sync_fetch_and_add(volatile void *, int, ...);
int __sync_fetch_and_sub(volatile void *, int, ...);
int __sync_fetch_and_or(volatile void *, int, ...);
int __sync_fetch_and_and(volatile void *, int, ...);
int __sync_fetch_and_xor(volatile void *, int, ...);
int __sync_fetch_and_nand(volatile void *, int, ...);
int __sync_add_and_fetch(volatile void *, int, ...);
int __sync_sub_and_fetch(volatile void *, int, ...);
int __sync_or_and_fetch(volatile void *, int, ...);
int __sync_and_and_fetch(volatile void *, int, ...);
int __sync_xor_and_fetch(volatile void *, int, ...);
int __sync_nand_and_fetch(volatile void *, int, ...);
_Bool __sync_bool_compare_and_swap(volatile void *, int oldval, int newval, ...);
int __sync_val_compare_and_swap(volatile void *, int oldval, int newval, ...);
void __sync_synchronize();
int __sync_lock_test_and_set(volatile void *, ...);
void __sync_lock_release(volatile void *, ...);
float __builtin_acosf(float);
long double __builtin_acosl(long double);
float __builtin_asinf(float);
long double __builtin_asinl(long double);
float __builtin_atanf(float);
long double __builtin_atanl(long double);
float __builtin_atan2f(float, float);
long double __builtin_atan2l(long double, long double);
float __builtin_ceilf(float);
long double __builtin_ceill(long double);
float __builtin_coshf(float);
long double __builtin_coshl(long double);
float __builtin_expf(float);
long double __builtin_expl(long double);
float __builtin_floorf(float);
long double __builtin_floorl(long double);
float __builtin_fmodf(float, float);
long double __builtin_fmodl(long double, long double);
float __builtin_frexpf(float, int*);
long double __builtin_frexpl(long double, int*);
float __builtin_ldexpf(float , int exp);
long double __builtin_ldexpl(long double, int);
float __builtin_logf(float);
long double __builtin_logl(long double);
float __builtin_log10f(float);
long double __builtin_log10l(long double);
float __builtin_modff(float, float*);
long double __builtin_modfl(long double, long double*);
float __builtin_powf(float, float);
long double __builtin_powl(long double, long double);
double __builtin_powi(double, int);
float __builtin_powif(float, int);
long double __builtin_powil(long double, int);
float __builtin_sinhf(float);
long double __builtin_sinhl(long double);
float __builtin_tanf(float);
long double __builtin_tanl(long double);
float __builtin_tanhf(float);
long double __builtin_tanhl(long double);
int __builtin_parityl(unsigned long);
int __builtin_parityll(unsigned long long);
void __builtin_trap(void);
void __builtin___clear_cache(char *begin, char *end);
int __builtin_clz(unsigned int x);
int __builtin_ctz(unsigned int x);
int __builtin_parity(unsigned int x);
int __builtin_ffsl(unsigned long);
int __builtin_clzl(unsigned long);
int __builtin_ctzl(unsigned long);
long int __builtin_bswap32(long int x);
long long int __builtin_bswap64(long long int x);
typedef int   __gccxml_m64  __attribute__ ((__vector_size__ (8), __may_alias__));
typedef int   __gccxml_v2si __attribute__ ((__vector_size__ (8), __may_alias__));
typedef int   __gccxml_v4si __attribute__ ((__vector_size__ (16), __may_alias__));
typedef short __gccxml_v4hi __attribute__ ((__vector_size__ (8), __may_alias__));
typedef float __gccxml_v4sf __attribute__ ((__vector_size__ (16), __may_alias__));
typedef char  __gccxml_v8qi __attribute__ ((__vector_size__ (8), __may_alias__));
typedef long long __gccxml_v1di __attribute__ ((__vector_size (8), __may_alias__));
__gccxml_v8qi __builtin_ia32_paddb (__gccxml_v8qi, __gccxml_v8qi);
__gccxml_v4hi __builtin_ia32_paddw (__gccxml_v4hi, __gccxml_v4hi);
__gccxml_v2si __builtin_ia32_paddd (__gccxml_v2si, __gccxml_v2si);
__gccxml_v1di __builtin_ia32_paddq (__gccxml_v1di, __gccxml_v1di);
__gccxml_v8qi __builtin_ia32_psubb (__gccxml_v8qi, __gccxml_v8qi);
__gccxml_v4hi __builtin_ia32_psubw (__gccxml_v4hi, __gccxml_v4hi);
__gccxml_v2si __builtin_ia32_psubd (__gccxml_v2si, __gccxml_v2si);
__gccxml_v1di __builtin_ia32_psubq (__gccxml_v1di, __gccxml_v1di) ;
__gccxml_v8qi __builtin_ia32_paddsb (__gccxml_v8qi, __gccxml_v8qi);
__gccxml_v4hi __builtin_ia32_paddsw (__gccxml_v4hi, __gccxml_v4hi);
__gccxml_v8qi __builtin_ia32_psubsb (__gccxml_v8qi, __gccxml_v8qi);
__gccxml_v4hi __builtin_ia32_psubsw (__gccxml_v4hi, __gccxml_v4hi);
__gccxml_v8qi __builtin_ia32_paddusb (__gccxml_v8qi, __gccxml_v8qi);
__gccxml_v4hi __builtin_ia32_paddusw (__gccxml_v4hi, __gccxml_v4hi);
__gccxml_v8qi __builtin_ia32_psubusb (__gccxml_v8qi, __gccxml_v8qi);
__gccxml_v4hi __builtin_ia32_psubusw (__gccxml_v4hi, __gccxml_v4hi);
__gccxml_v4hi __builtin_ia32_pmullw (__gccxml_v4hi, __gccxml_v4hi);
__gccxml_v4hi __builtin_ia32_pmulhw (__gccxml_v4hi, __gccxml_v4hi);
__gccxml_v1di __builtin_ia32_pand (__gccxml_v1di, __gccxml_v1di);
__gccxml_v1di __builtin_ia32_pandn (__gccxml_v1di, __gccxml_v1di);
__gccxml_v1di __builtin_ia32_por (__gccxml_v1di, __gccxml_v1di);
__gccxml_v1di __builtin_ia32_pxor (__gccxml_v1di, __gccxml_v1di);
__gccxml_v8qi __builtin_ia32_pcmpeqb (__gccxml_v8qi, __gccxml_v8qi);
__gccxml_v4hi __builtin_ia32_pcmpeqw (__gccxml_v4hi, __gccxml_v4hi);
__gccxml_v2si __builtin_ia32_pcmpeqd (__gccxml_v2si, __gccxml_v2si);
__gccxml_v8qi __builtin_ia32_pcmpgtb (__gccxml_v8qi, __gccxml_v8qi);
__gccxml_v4hi __builtin_ia32_pcmpgtw (__gccxml_v4hi, __gccxml_v4hi);
__gccxml_v2si __builtin_ia32_pcmpgtd (__gccxml_v2si, __gccxml_v2si);
__gccxml_v8qi __builtin_ia32_punpckhbw (__gccxml_v8qi, __gccxml_v8qi);
__gccxml_v4hi __builtin_ia32_punpckhwd (__gccxml_v4hi, __gccxml_v4hi);
__gccxml_v2si __builtin_ia32_punpckhdq (__gccxml_v2si, __gccxml_v2si);
__gccxml_v8qi __builtin_ia32_punpcklbw (__gccxml_v8qi, __gccxml_v8qi);
__gccxml_v4hi __builtin_ia32_punpcklwd (__gccxml_v4hi, __gccxml_v4hi);
__gccxml_v2si __builtin_ia32_punpckldq (__gccxml_v2si, __gccxml_v2si);
__gccxml_v8qi __builtin_ia32_packsswb (__gccxml_v4hi, __gccxml_v4hi);
__gccxml_v4hi __builtin_ia32_packssdw (__gccxml_v2si, __gccxml_v2si);
__gccxml_v8qi __builtin_ia32_packuswb (__gccxml_v4hi, __gccxml_v4hi) ;
void __builtin_ia32_emms (void);
__gccxml_v4hi __builtin_ia32_psllw (__gccxml_v4hi, __gccxml_v1di);
__gccxml_v4hi __builtin_ia32_psllwi (__gccxml_v4hi, int);
__gccxml_v2si __builtin_ia32_pslld (__gccxml_v2si, __gccxml_v1di);
__gccxml_v2si __builtin_ia32_pslldi (__gccxml_v2si, int);
__gccxml_v1di __builtin_ia32_psllq (__gccxml_v1di, __gccxml_v1di) ;
__gccxml_v1di __builtin_ia32_psllqi (__gccxml_v1di, int);
__gccxml_v4hi __builtin_ia32_psrlw (__gccxml_v4hi, __gccxml_v1di);
__gccxml_v4hi __builtin_ia32_psrlwi (__gccxml_v4hi, int);
__gccxml_v2si __builtin_ia32_psrld (__gccxml_v2si, __gccxml_v1di);
__gccxml_v2si __builtin_ia32_psrldi (__gccxml_v2si, int);
__gccxml_v1di __builtin_ia32_psrlq (__gccxml_v1di, __gccxml_v1di);
__gccxml_v1di __builtin_ia32_psrlqi (__gccxml_v1di, int);
__gccxml_v4hi __builtin_ia32_psraw (__gccxml_v4hi, __gccxml_v1di);
__gccxml_v4hi __builtin_ia32_psrawi (__gccxml_v4hi, int);
__gccxml_v2si __builtin_ia32_psrad (__gccxml_v2si, __gccxml_v1di);
__gccxml_v2si __builtin_ia32_psradi (__gccxml_v2si, int);
__gccxml_v4hi __builtin_ia32_pshufw (__gccxml_v4hi, int);
__gccxml_v2si __builtin_ia32_pmaddwd (__gccxml_v4hi, __gccxml_v4hi);
__gccxml_v2si __builtin_ia32_vec_init_v2si (int, int);
__gccxml_v4hi __builtin_ia32_vec_init_v4hi (short, short, short, short);
__gccxml_v8qi __builtin_ia32_vec_init_v8qi (char, char, char, char, char, char, char, char);
int __builtin_ia32_vec_ext_v2si (__gccxml_v2si, int);
int __builtin_ia32_comieq (__gccxml_v4sf, __gccxml_v4sf);
int __builtin_ia32_comineq (__gccxml_v4sf, __gccxml_v4sf);
int __builtin_ia32_comilt (__gccxml_v4sf, __gccxml_v4sf);
int __builtin_ia32_comile (__gccxml_v4sf, __gccxml_v4sf);
int __builtin_ia32_comigt (__gccxml_v4sf, __gccxml_v4sf);
int __builtin_ia32_comige (__gccxml_v4sf, __gccxml_v4sf);
int __builtin_ia32_ucomieq (__gccxml_v4sf, __gccxml_v4sf);
int __builtin_ia32_ucomineq (__gccxml_v4sf, __gccxml_v4sf);
int __builtin_ia32_ucomilt (__gccxml_v4sf, __gccxml_v4sf);
int __builtin_ia32_ucomile (__gccxml_v4sf, __gccxml_v4sf);
int __builtin_ia32_ucomigt (__gccxml_v4sf, __gccxml_v4sf);
int __builtin_ia32_ucomige (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_addps (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_subps (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_mulps (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_divps (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_addss (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_subss (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_mulss (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_divss (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4si __builtin_ia32_cmpeqps (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4si __builtin_ia32_cmpltps (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4si __builtin_ia32_cmpleps (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4si __builtin_ia32_cmpgtps (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4si __builtin_ia32_cmpgeps (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4si __builtin_ia32_cmpunordps (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4si __builtin_ia32_cmpneqps (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4si __builtin_ia32_cmpnltps (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4si __builtin_ia32_cmpnleps (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4si __builtin_ia32_cmpngtps (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4si __builtin_ia32_cmpngeps (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4si __builtin_ia32_cmpordps (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4si __builtin_ia32_cmpeqss (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4si __builtin_ia32_cmpltss (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4si __builtin_ia32_cmpless (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4si __builtin_ia32_cmpgtss (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4si __builtin_ia32_cmpgess (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4si __builtin_ia32_cmpunordss (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4si __builtin_ia32_cmpneqss (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4si __builtin_ia32_cmpnlts (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4si __builtin_ia32_cmpnless (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4si __builtin_ia32_cmpngtss (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4si __builtin_ia32_cmpngess (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4si __builtin_ia32_cmpordss (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_maxps (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_maxss (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_minps (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_minss (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_andps (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_andnps (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_orps (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_xorps (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_movss (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_movhlps (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_movlhps (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_unpckhps (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_unpcklps (__gccxml_v4sf, __gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_cvtpi2ps (__gccxml_v4sf, __gccxml_v2si);
__gccxml_v4sf __builtin_ia32_cvtsi2ss (__gccxml_v4sf, int);
__gccxml_v2si __builtin_ia32_cvtps2pi (__gccxml_v4sf);
int __builtin_ia32_cvtss2si (__gccxml_v4sf);
__gccxml_v2si __builtin_ia32_cvttps2pi (__gccxml_v4sf);
int __builtin_ia32_cvttss2si (__gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_rcpps (__gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_rsqrtps (__gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_sqrtps (__gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_rcpss (__gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_rsqrtss (__gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_sqrtss (__gccxml_v4sf);
__gccxml_v4sf __builtin_ia32_shufps (__gccxml_v4sf, __gccxml_v4sf, int);
void __builtin_ia32_movntps (float *, __gccxml_v4sf);
int __builtin_ia32_movmskps (__gccxml_v4sf);

