#!/bin/bash

FIG="cbmc-flow.fig frontend.fig"

for a in ${FIG} ; do
  fig2dev -L pdftex $a > `echo $a | sed s/.fig/.pdf/`
done

for a in ${FIG} ; do
  fig2dev -L pdftex_t -p `echo $a | sed s/.fig/.pdf/` $a > `echo $a | sed s/.fig/.xfigtex/`
done

MP="bmc-loop unrolling-cfg unrolling sha-example unrolling-full"

for a in ${MP} ; do
  mptopdf --rawmp $a
done
