#!/usr/bin/python -u

from __future__ import print_function
import re
import sys

REGEXP = [
    (r'.*replacing function pointer by .* possible targets.*'),
    (r'^Unwinding loop .* iteration .* \(.* max\)'),
    (r'^Not unwinding loop .* iteration .* \(.* max\)'),
    r'^\[.*\] .*: SUCCESS',
    r'^\[.*\] .*: FAILURE',
    r'Covered block .* \(lines .*\)'
]

def match_string (string):
    for regexp in REGEXP:
        if re.match(regexp,string):
            return True
    return False

def quiet():
    in_results = False
    while True:
        line = sys.stdin.readline()

        if line == "":
            return

        line = line.strip()
        if line == '** Results:':
            # start of result section
            in_results = True
            print(line)
            continue
        if re.match(r'\*\* .* of .* failed \(.* iteration\)',line):
            # end of result section
            in_results = False
            print(line)
            continue
        if in_results:
            continue
        if match_string(line):
            continue
        print(line)

if __name__ == "__main__":
    quiet()


