#!/usr/bin/python -u

import re
import sys

REGEXP = [
    (r'replacing function pointer by .* possible targets.*'),
    (r'^Unwinding loop .* iteration .* \(.* max\)'),
    (r'^Not unwinding loop .* iteration .* \(.* max\)'),
    r'^\[.*\] .*: SUCCESS',
    r'^\[.*\] .*: FAILURE',
    r'Covered block .* \(lines .*\)'
]

def match_string (string):
    for regexp in REGEXP:
        if re.match(regexp,string):
            return True
    return False

def message_start(line):
    match = re.match(r'<message type="(.*)">',line)
    if match:
        return match.group(1)
    return False

def message_end(line):
    return line == '</message>'

def extract_text(line):
    match = re.match(r' *<text>(.*)</text>',line)
    if match:
        return match.group(1)
    return False

def quiet():
    in_results = False
    in_message = False
    while True:
        line = sys.stdin.readline()

        if line == "":
            return

        line = line.strip()

        if message_start(line):
            in_message = True
            continue

        if message_end(line):
            in_message = False
            continue

        if in_message:
            text = extract_text(line)
            if text:
                if match_string(text):
                    continue
                print text

if __name__ == "__main__":
    quiet()


