SRC = miniz.cpp \
      # Empty last line

INCLUDES= -I ..

include ../config.inc
include ../$(CPROVER_DIR)/src/config.inc
include ../$(CPROVER_DIR)/src/common

CLEANFILES = miniz$(OBJEXT)

all: miniz$(OBJEXT)

###############################################################################
