error_log /Users/kroening/cprover-web/error.log;
pid /Users/kroening/cprover-web/nginx.pid;

events {
}

http {
  server {
    client_body_temp_path /Users/kroening/cprover-web/client_body_temp;
    proxy_temp_path /Users/kroening/cprover-web/proxy_temp;
    fastcgi_temp_path /Users/kroening/cprover-web/fastcgi_temp;
    uwsgi_temp_path /Users/kroening/cprover-web/uwsgi_temp;
    scgi_temp_path /Users/kroening/cprover-web/scgi_temp;
    access_log /Users/kroening/cprover-web/access.log;
    listen 8080;
    location / {
        root /Users/kroening/cprover-web;
    }
  }
}

