.TH GOTO-INSPECT "1" "March 1, 2026" "goto-inspect-6.10.0" "User Commands"
.SH NAME
goto\-inspect \- Display information about goto binaries
.SH SYNOPSIS
.B goto\-inspect
.RI [ options ]
.I file.gb
.SH DESCRIPTION
\fBgoto\-inspect\fR reads a GOTO binary and displays information about its
contents, such as the GOTO program instructions, properties, and other
attributes.
.SH OPTIONS
.TP
\fB\-\-show\-goto\-functions\fR
Print the GOTO program instructions for all functions in the binary.
.SH ENVIRONMENT
.TP
.B TMPDIR
All CProver tools honor this variable when creating temporary files and
directories.
.SH BUGS
If you encounter a problem please create an issue at
.B https://github.com/diffblue/cbmc/issues
.SH SEE ALSO
.BR cbmc (1),
.BR goto-cc (1),
.BR goto-instrument (1)
.SH COPYRIGHT
2023, Diffblue Ltd.
