.TH SYMTAB2GB "1" "March 1, 2026" "symtab2gb-6.10.0" "User Commands"
.SH NAME
symtab2gb \- Compile JSON symbol tables to a GOTO binary
.SH SYNOPSIS
.TP
.B symtab2gb [\-?] [\-h] [\-\-help]
show help
.TP
.B symtab2gb \fIjson\-symtab\-file\fR+ [\fB\-\-out \fIoutfile\fR]
compile symbol tables in JSON format
to a single GOTO binary
.SH DESCRIPTION
\fBsymtab2gb\fR compiles one or more CProver symbol tables (in JSON format)
into a single GOTO binary.  This supports integration of external language
front-ends such as Ada (via GNAT2GOTO) or Rust (via Kani).
.SH OPTIONS
.TP
\fB\-\-out\fR \fIoutfile\fR
Specify the filename of the resulting binary (default: a.out)
.TP
\fB\-\-goto\-functions\fR \fIfile\fR
Specify a file containing JSON-encoded goto functions
.TP
\fB\-\-verbosity\fR #
verbosity level
.SH EXAMPLES
Compile a JSON symbol table to a GOTO binary:
.IP
.B symtab2gb symtab.json \-\-out program.gb
.SH ENVIRONMENT
.TP
.B TMPDIR
All CProver tools honor this variable when creating temporary files and
directories.
.SH BUGS
If you encounter a problem please create an issue at
.B https://github.com/diffblue/cbmc/issues
.SH SEE ALSO
.BR cbmc (1),
.BR goto\-cc (1),
.BR goto\-harness (1)
.SH COPYRIGHT
2019, Diffblue
