#!/bin/bash
umask u=rwx,g=rx,o=rx

VERSION=`./cbmc --version`

echo $VERSION_FILE

mkdir /tmp/cbmc-dist
cd /tmp/cbmc-dist
svn export http://www.cprover.org/svn/cbmc/releases/cbmc-${VERSION} cbmc-src
tar cfz cbmc-${VERSION}-src.tgz cbmc-src/

echo Copying.
scp cbmc-${VERSION}-src.tgz \
  kroening@dkr-srv.cs.ox.ac.uk:/srv/www/cprover.org/cbmc/download/

cd /tmp
rm -R /tmp/cbmc-dist
