/*******************************************************************\

 Module: Unit test utilities

 Author: DiffBlue Limited. All rights reserved.

\*******************************************************************/

/// \file
/// Utility for loading and parsing a specified java class file, returning
/// the symbol table generated by this.

#ifndef CPROVER_SRC_JAVA_BYTECODE_LOAD_JAVA_CLASS_H
#define CPROVER_SRC_JAVA_BYTECODE_LOAD_JAVA_CLASS_H

#include <util/symbol_table.h>

symbol_tablet load_java_class(
  const std::string &java_class_name,
  const std::string &class_path);

#endif // CPROVER_SRC_JAVA_BYTECODE_LOAD_JAVA_CLASS_H
