---
AWSTemplateFormatVersion: 2010-09-09

Parameters:
    Ami:
        Type: String

    AvailabilityZone:
        Type: String

    Subnet:
        Type: String

    SSHKeyName:
        Type: String

Conditions:
    UseKey: !Not [!Equals [!Ref SSHKeyName, ""]]

Resources:
    EC2Instance:
        Type: "AWS::EC2::Instance"
        Properties:
            InstanceType: c5.large
            KeyName:
                !If [UseKey, !Ref SSHKeyName, !Ref "AWS::NoValue"]
            ImageId: !Ref Ami
            SubnetId: !Ref Subnet
            Volumes:
                - Device: "/dev/sdf"
                  VolumeId: !Ref BaseVolume
            UserData: !Base64 |
                #!/bin/bash
                set -e
                # wait to make sure volume is available
                sleep 10
                if lsblk | grep ^nvme
                then
                  d=$(ls /dev/nvme* | tail -n 1)
                  mkfs.ext4 $d
                  mount $d /mnt
                else
                  mkfs.ext4 /dev/xvdf
                  mount /dev/xvdf /mnt
                fi
                apt-get -y update
                apt-get install git
                cd /mnt
                git clone --depth 1 --branch main \
                        https://gitlab.com/sosy-lab/benchmarking/sv-benchmarks.git
                git clone --depth 1 \
                        https://github.com/sosy-lab/benchexec.git
                git clone --depth 1 --branch trunk \
                        https://github.com/sosy-lab/cpachecker.git
                git clone --depth 1 \
                        https://github.com/diffblue/cprover-sv-comp.git
                git clone --depth 1 \
                        https://github.com/tautschnig/fshell-w2t.git
                poweroff

    BaseVolume:
        Type: "AWS::EC2::Volume"
        DeletionPolicy: Snapshot
        Properties:
            AvailabilityZone: !Ref AvailabilityZone
            Size: 20
            Tags:
                - Key: Name
                  Value: perf-test-base

Outputs:
    InstanceId:
       Value: !Ref EC2Instance
