// The model for __builtin_neon_vmaxq_v is generated by
// scripts/generate_neon_models.py from arm_neon.td. Type code 32 selects the
// int8x16 lane interpretation; verify the model agrees with a per-lane max.
typedef signed char v16 __attribute__((vector_size(16)));
typedef char v16qi __attribute__((vector_size(16)));

int main()
{
  v16 a, b;
  v16 r = (v16)__builtin_neon_vmaxq_v((v16qi)a, (v16qi)b, 32);
  for(int i = 0; i < 16; i++)
    __CPROVER_assert(r[i] == (a[i] > b[i] ? a[i] : b[i]), "vmaxq_s8 == max");
  return 0;
}
