
SMT2_INCREMENTAL_SRC = \
      smt2_incremental/convert_expr_to_smt.cpp \
      smt2_incremental/smt_bit_vector_theory.cpp \
      smt2_incremental/smt_commands.cpp \
      smt2_incremental/smt_core_theory.cpp \
      smt2_incremental/smt_logics.cpp \
      smt2_incremental/smt_options.cpp \
      smt2_incremental/smt_solver_process.cpp \
      smt2_incremental/smt_sorts.cpp \
      smt2_incremental/smt_terms.cpp \
      smt2_incremental/smt_to_smt2_string.cpp \
      smt2_incremental/smt2_incremental_decision_procedure.cpp \
      # Empty last line
