// clang-format off
void __breakpoint(int val);
void __cdp(unsigned int coproc, unsigned int ops, unsigned int regs);
void __clrex(void);
unsigned char __clz(unsigned int val);
unsigned int __current_pc(void);
unsigned int __current_sp(void);
int __disable_fiq(void);
int __disable_irq(void);
void __enable_fiq(void);
void __enable_irq(void);
double __fabs(double val);
float __fabs(float val);
void __force_stores(void);
unsigned int __ldrex(volatile void *ptr);
unsigned long long __ldrexd(volatile void *ptr);
unsigned int __ldrt(const volatile void *ptr);
void __memory_changed(void);
void __nop(void);
void __pld();
void __pldw();
void __pli();
void __promise(expr);
int __qadd(int val1, int val2);
int __qdbl(int val);
int __qsub(int val1, int val2);
unsigned int __rbit(unsigned int val);
unsigned int __rev(unsigned int val);
unsigned int __return_address(void);
unsigned int __ror(unsigned int val, unsigned int shift);
void __schedule_barrier(void);
int __semihost(int val, const void *ptr);
void __sev(void);
void __sev(void);
float __sqrtf(float);
int __ssat(int val, unsigned int sat);
int __strex(unsigned int val, volatile void *ptr);
int __strexd(unsigned long long val, volatile void *ptr);
void __strt(unsigned int val, volatile void *ptr);
unsigned int __swp(unsigned int val, volatile void *ptr);
int __usat(unsigned int val, unsigned int sat);
void __wfe(void);
void __wfi(void);
void __yield(void);
// clang-format on
