// clang-format off
__gcc_v32hi __builtin_ia32_vpshrd_v32hi(__gcc_v32hi, __gcc_v32hi, int);
__gcc_v32hi __builtin_ia32_vpshrd_v32hi_mask(__gcc_v32hi, __gcc_v32hi, int, __gcc_v32hi, int);
__gcc_v16hi __builtin_ia32_vpshrd_v16hi(__gcc_v16hi, __gcc_v16hi, int);
__gcc_v16hi __builtin_ia32_vpshrd_v16hi_mask(__gcc_v16hi, __gcc_v16hi, int, __gcc_v16hi, int);
__gcc_v8hi __builtin_ia32_vpshrd_v8hi(__gcc_v8hi, __gcc_v8hi, int);
__gcc_v8hi __builtin_ia32_vpshrd_v8hi_mask(__gcc_v8hi, __gcc_v8hi, int, __gcc_v8hi, int);
__gcc_v16si __builtin_ia32_vpshrd_v16si(__gcc_v16si, __gcc_v16si, int);
__gcc_v16si __builtin_ia32_vpshrd_v16si_mask(__gcc_v16si, __gcc_v16si, int, __gcc_v16si, int);
__gcc_v8si __builtin_ia32_vpshrd_v8si(__gcc_v8si, __gcc_v8si, int);
__gcc_v8si __builtin_ia32_vpshrd_v8si_mask(__gcc_v8si, __gcc_v8si, int, __gcc_v8si, int);
__gcc_v4si __builtin_ia32_vpshrd_v4si(__gcc_v4si, __gcc_v4si, int);
__gcc_v4si __builtin_ia32_vpshrd_v4si_mask(__gcc_v4si, __gcc_v4si, int, __gcc_v4si, int);
__gcc_v8di __builtin_ia32_vpshrd_v8di(__gcc_v8di, __gcc_v8di, int);
__gcc_v8di __builtin_ia32_vpshrd_v8di_mask(__gcc_v8di, __gcc_v8di, int, __gcc_v8di, int);
__gcc_v4di __builtin_ia32_vpshrd_v4di(__gcc_v4di, __gcc_v4di, int);
__gcc_v4di __builtin_ia32_vpshrd_v4di_mask(__gcc_v4di, __gcc_v4di, int, __gcc_v4di, int);
__gcc_v2di __builtin_ia32_vpshrd_v2di(__gcc_v2di, __gcc_v2di, int);
__gcc_v2di __builtin_ia32_vpshrd_v2di_mask(__gcc_v2di, __gcc_v2di, int, __gcc_v2di, int);
__gcc_v32hi __builtin_ia32_vpshld_v32hi(__gcc_v32hi, __gcc_v32hi, int);
__gcc_v32hi __builtin_ia32_vpshld_v32hi_mask(__gcc_v32hi, __gcc_v32hi, int, __gcc_v32hi, int);
__gcc_v16hi __builtin_ia32_vpshld_v16hi(__gcc_v16hi, __gcc_v16hi, int);
__gcc_v16hi __builtin_ia32_vpshld_v16hi_mask(__gcc_v16hi, __gcc_v16hi, int, __gcc_v16hi, int);
__gcc_v8hi __builtin_ia32_vpshld_v8hi(__gcc_v8hi, __gcc_v8hi, int);
__gcc_v8hi __builtin_ia32_vpshld_v8hi_mask(__gcc_v8hi, __gcc_v8hi, int, __gcc_v8hi, int);
__gcc_v16si __builtin_ia32_vpshld_v16si(__gcc_v16si, __gcc_v16si, int);
__gcc_v16si __builtin_ia32_vpshld_v16si_mask(__gcc_v16si, __gcc_v16si, int, __gcc_v16si, int);
__gcc_v8si __builtin_ia32_vpshld_v8si(__gcc_v8si, __gcc_v8si, int);
__gcc_v8si __builtin_ia32_vpshld_v8si_mask(__gcc_v8si, __gcc_v8si, int, __gcc_v8si, int);
__gcc_v4si __builtin_ia32_vpshld_v4si(__gcc_v4si, __gcc_v4si, int);
__gcc_v4si __builtin_ia32_vpshld_v4si_mask(__gcc_v4si, __gcc_v4si, int, __gcc_v4si, int);
__gcc_v8di __builtin_ia32_vpshld_v8di(__gcc_v8di, __gcc_v8di, int);
__gcc_v8di __builtin_ia32_vpshld_v8di_mask(__gcc_v8di, __gcc_v8di, int, __gcc_v8di, int);
__gcc_v4di __builtin_ia32_vpshld_v4di(__gcc_v4di, __gcc_v4di, int);
__gcc_v4di __builtin_ia32_vpshld_v4di_mask(__gcc_v4di, __gcc_v4di, int, __gcc_v4di, int);
__gcc_v2di __builtin_ia32_vpshld_v2di(__gcc_v2di, __gcc_v2di, int);
__gcc_v2di __builtin_ia32_vpshld_v2di_mask(__gcc_v2di, __gcc_v2di, int, __gcc_v2di, int);
__gcc_v32hi __builtin_ia32_vpshrdv_v32hi(__gcc_v32hi, __gcc_v32hi, __gcc_v32hi);
__gcc_v32hi __builtin_ia32_vpshrdv_v32hi_mask(__gcc_v32hi, __gcc_v32hi, __gcc_v32hi, unsigned);
__gcc_v32hi __builtin_ia32_vpshrdv_v32hi_maskz(__gcc_v32hi, __gcc_v32hi, __gcc_v32hi, unsigned);
__gcc_v16hi __builtin_ia32_vpshrdv_v16hi(__gcc_v16hi, __gcc_v16hi, __gcc_v16hi);
__gcc_v16hi __builtin_ia32_vpshrdv_v16hi_mask(__gcc_v16hi, __gcc_v16hi, __gcc_v16hi, unsigned short);
__gcc_v16hi __builtin_ia32_vpshrdv_v16hi_maskz(__gcc_v16hi, __gcc_v16hi, __gcc_v16hi, unsigned short);
__gcc_v8hi __builtin_ia32_vpshrdv_v8hi(__gcc_v8hi, __gcc_v8hi, __gcc_v8hi);
__gcc_v8hi __builtin_ia32_vpshrdv_v8hi_mask(__gcc_v8hi, __gcc_v8hi, __gcc_v8hi, unsigned char);
__gcc_v8hi __builtin_ia32_vpshrdv_v8hi_maskz(__gcc_v8hi, __gcc_v8hi, __gcc_v8hi, unsigned char);
__gcc_v16si __builtin_ia32_vpshrdv_v16si(__gcc_v16si, __gcc_v16si, __gcc_v16si);
__gcc_v16si __builtin_ia32_vpshrdv_v16si_mask(__gcc_v16si, __gcc_v16si, __gcc_v16si, unsigned short);
__gcc_v16si __builtin_ia32_vpshrdv_v16si_maskz(__gcc_v16si, __gcc_v16si, __gcc_v16si, unsigned short);
__gcc_v8si __builtin_ia32_vpshrdv_v8si(__gcc_v8si, __gcc_v8si, __gcc_v8si);
__gcc_v8si __builtin_ia32_vpshrdv_v8si_mask(__gcc_v8si, __gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v8si __builtin_ia32_vpshrdv_v8si_maskz(__gcc_v8si, __gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_vpshrdv_v4si(__gcc_v4si, __gcc_v4si, __gcc_v4si);
__gcc_v4si __builtin_ia32_vpshrdv_v4si_mask(__gcc_v4si, __gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v4si __builtin_ia32_vpshrdv_v4si_maskz(__gcc_v4si, __gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v8di __builtin_ia32_vpshrdv_v8di(__gcc_v8di, __gcc_v8di, __gcc_v8di);
__gcc_v8di __builtin_ia32_vpshrdv_v8di_mask(__gcc_v8di, __gcc_v8di, __gcc_v8di, unsigned char);
__gcc_v8di __builtin_ia32_vpshrdv_v8di_maskz(__gcc_v8di, __gcc_v8di, __gcc_v8di, unsigned char);
__gcc_v4di __builtin_ia32_vpshrdv_v4di(__gcc_v4di, __gcc_v4di, __gcc_v4di);
__gcc_v4di __builtin_ia32_vpshrdv_v4di_mask(__gcc_v4di, __gcc_v4di, __gcc_v4di, unsigned char);
__gcc_v4di __builtin_ia32_vpshrdv_v4di_maskz(__gcc_v4di, __gcc_v4di, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_vpshrdv_v2di(__gcc_v2di, __gcc_v2di, __gcc_v2di);
__gcc_v2di __builtin_ia32_vpshrdv_v2di_mask(__gcc_v2di, __gcc_v2di, __gcc_v2di, unsigned char);
__gcc_v2di __builtin_ia32_vpshrdv_v2di_maskz(__gcc_v2di, __gcc_v2di, __gcc_v2di, unsigned char);
__gcc_v32hi __builtin_ia32_vpshldv_v32hi(__gcc_v32hi, __gcc_v32hi, __gcc_v32hi);
__gcc_v32hi __builtin_ia32_vpshldv_v32hi_mask(__gcc_v32hi, __gcc_v32hi, __gcc_v32hi, unsigned);
__gcc_v32hi __builtin_ia32_vpshldv_v32hi_maskz(__gcc_v32hi, __gcc_v32hi, __gcc_v32hi, unsigned);
__gcc_v16hi __builtin_ia32_vpshldv_v16hi(__gcc_v16hi, __gcc_v16hi, __gcc_v16hi);
__gcc_v16hi __builtin_ia32_vpshldv_v16hi_mask(__gcc_v16hi, __gcc_v16hi, __gcc_v16hi, unsigned short);
__gcc_v16hi __builtin_ia32_vpshldv_v16hi_maskz(__gcc_v16hi, __gcc_v16hi, __gcc_v16hi, unsigned short);
__gcc_v8hi __builtin_ia32_vpshldv_v8hi(__gcc_v8hi, __gcc_v8hi, __gcc_v8hi);
__gcc_v8hi __builtin_ia32_vpshldv_v8hi_mask(__gcc_v8hi, __gcc_v8hi, __gcc_v8hi, unsigned char);
__gcc_v8hi __builtin_ia32_vpshldv_v8hi_maskz(__gcc_v8hi, __gcc_v8hi, __gcc_v8hi, unsigned char);
__gcc_v16si __builtin_ia32_vpshldv_v16si(__gcc_v16si, __gcc_v16si, __gcc_v16si);
__gcc_v16si __builtin_ia32_vpshldv_v16si_mask(__gcc_v16si, __gcc_v16si, __gcc_v16si, unsigned short);
__gcc_v16si __builtin_ia32_vpshldv_v16si_maskz(__gcc_v16si, __gcc_v16si, __gcc_v16si, unsigned short);
__gcc_v8si __builtin_ia32_vpshldv_v8si(__gcc_v8si, __gcc_v8si, __gcc_v8si);
__gcc_v8si __builtin_ia32_vpshldv_v8si_mask(__gcc_v8si, __gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v8si __builtin_ia32_vpshldv_v8si_maskz(__gcc_v8si, __gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_vpshldv_v4si(__gcc_v4si, __gcc_v4si, __gcc_v4si);
__gcc_v4si __builtin_ia32_vpshldv_v4si_mask(__gcc_v4si, __gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v4si __builtin_ia32_vpshldv_v4si_maskz(__gcc_v4si, __gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v8di __builtin_ia32_vpshldv_v8di(__gcc_v8di, __gcc_v8di, __gcc_v8di);
__gcc_v8di __builtin_ia32_vpshldv_v8di_mask(__gcc_v8di, __gcc_v8di, __gcc_v8di, unsigned char);
__gcc_v8di __builtin_ia32_vpshldv_v8di_maskz(__gcc_v8di, __gcc_v8di, __gcc_v8di, unsigned char);
__gcc_v4di __builtin_ia32_vpshldv_v4di(__gcc_v4di, __gcc_v4di, __gcc_v4di);
__gcc_v4di __builtin_ia32_vpshldv_v4di_mask(__gcc_v4di, __gcc_v4di, __gcc_v4di, unsigned char);
__gcc_v4di __builtin_ia32_vpshldv_v4di_maskz(__gcc_v4di, __gcc_v4di, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_vpshldv_v2di(__gcc_v2di, __gcc_v2di, __gcc_v2di);
__gcc_v2di __builtin_ia32_vpshldv_v2di_mask(__gcc_v2di, __gcc_v2di, __gcc_v2di, unsigned char);
__gcc_v2di __builtin_ia32_vpshldv_v2di_maskz(__gcc_v2di, __gcc_v2di, __gcc_v2di, unsigned char);
__gcc_v64qi __builtin_ia32_vgf2p8affineinvqb_v64qi(__gcc_v64qi, __gcc_v64qi, int);
__gcc_v64qi __builtin_ia32_vgf2p8affineinvqb_v64qi_mask(__gcc_v64qi, __gcc_v64qi, int, __gcc_v64qi, unsigned long long);
__gcc_v32qi __builtin_ia32_vgf2p8affineinvqb_v32qi(__gcc_v32qi, __gcc_v32qi, int);
__gcc_v32qi __builtin_ia32_vgf2p8affineinvqb_v32qi_mask(__gcc_v32qi, __gcc_v32qi, int, __gcc_v32qi, unsigned);
__gcc_v16qi __builtin_ia32_vgf2p8affineinvqb_v16qi(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_ia32_vgf2p8affineinvqb_v16qi_mask(__gcc_v16qi, __gcc_v16qi, int, __gcc_v16qi, unsigned short);
__gcc_v64qi __builtin_ia32_vgf2p8affineqb_v64qi(__gcc_v64qi, __gcc_v64qi, int);
__gcc_v64qi __builtin_ia32_vgf2p8affineqb_v64qi_mask(__gcc_v64qi, __gcc_v64qi, int, __gcc_v64qi, unsigned long long);
__gcc_v32qi __builtin_ia32_vgf2p8affineqb_v32qi(__gcc_v32qi, __gcc_v32qi, int);
__gcc_v32qi __builtin_ia32_vgf2p8affineqb_v32qi_mask(__gcc_v32qi, __gcc_v32qi, int, __gcc_v32qi, unsigned);
__gcc_v16qi __builtin_ia32_vgf2p8affineqb_v16qi(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_ia32_vgf2p8affineqb_v16qi_mask(__gcc_v16qi, __gcc_v16qi, int, __gcc_v16qi, unsigned short);
__gcc_v64qi __builtin_ia32_vgf2p8mulb_v64qi(__gcc_v64qi, __gcc_v64qi);
__gcc_v64qi __builtin_ia32_vgf2p8mulb_v64qi_mask(__gcc_v64qi, __gcc_v64qi, __gcc_v64qi, unsigned long long);
__gcc_v32qi __builtin_ia32_vgf2p8mulb_v32qi(__gcc_v32qi, __gcc_v32qi);
__gcc_v32qi __builtin_ia32_vgf2p8mulb_v32qi_mask(__gcc_v32qi, __gcc_v32qi, __gcc_v32qi, unsigned);
__gcc_v16qi __builtin_ia32_vgf2p8mulb_v16qi(__gcc_v16qi, __gcc_v16qi);
__gcc_v16qi __builtin_ia32_vgf2p8mulb_v16qi_mask(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, unsigned short);
__gcc_v16si __builtin_ia32_vpdpbusd_v16si(__gcc_v16si, __gcc_v16si, __gcc_v16si);
__gcc_v16si __builtin_ia32_vpdpbusd_v16si_mask(__gcc_v16si, __gcc_v16si, __gcc_v16si, unsigned short);
__gcc_v16si __builtin_ia32_vpdpbusd_v16si_maskz(__gcc_v16si, __gcc_v16si, __gcc_v16si, unsigned short);
__gcc_v8si __builtin_ia32_vpdpbusd_v8si(__gcc_v8si, __gcc_v8si, __gcc_v8si);
__gcc_v8si __builtin_ia32_vpdpbusd_v8si_mask(__gcc_v8si, __gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v8si __builtin_ia32_vpdpbusd_v8si_maskz(__gcc_v8si, __gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_vpdpbusd_v4si(__gcc_v4si, __gcc_v4si, __gcc_v4si);
__gcc_v4si __builtin_ia32_vpdpbusd_v4si_mask(__gcc_v4si, __gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v4si __builtin_ia32_vpdpbusd_v4si_maskz(__gcc_v4si, __gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v16si __builtin_ia32_vpdpbusds_v16si(__gcc_v16si, __gcc_v16si, __gcc_v16si);
__gcc_v16si __builtin_ia32_vpdpbusds_v16si_mask(__gcc_v16si, __gcc_v16si, __gcc_v16si, unsigned short);
__gcc_v16si __builtin_ia32_vpdpbusds_v16si_maskz(__gcc_v16si, __gcc_v16si, __gcc_v16si, unsigned short);
__gcc_v8si __builtin_ia32_vpdpbusds_v8si(__gcc_v8si, __gcc_v8si, __gcc_v8si);
__gcc_v8si __builtin_ia32_vpdpbusds_v8si_mask(__gcc_v8si, __gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v8si __builtin_ia32_vpdpbusds_v8si_maskz(__gcc_v8si, __gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_vpdpbusds_v4si(__gcc_v4si, __gcc_v4si, __gcc_v4si);
__gcc_v4si __builtin_ia32_vpdpbusds_v4si_mask(__gcc_v4si, __gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v4si __builtin_ia32_vpdpbusds_v4si_maskz(__gcc_v4si, __gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v16si __builtin_ia32_vpdpwssd_v16si(__gcc_v16si, __gcc_v16si, __gcc_v16si);
__gcc_v16si __builtin_ia32_vpdpwssd_v16si_mask(__gcc_v16si, __gcc_v16si, __gcc_v16si, unsigned short);
__gcc_v16si __builtin_ia32_vpdpwssd_v16si_maskz(__gcc_v16si, __gcc_v16si, __gcc_v16si, unsigned short);
__gcc_v8si __builtin_ia32_vpdpwssd_v8si(__gcc_v8si, __gcc_v8si, __gcc_v8si);
__gcc_v8si __builtin_ia32_vpdpwssd_v8si_mask(__gcc_v8si, __gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v8si __builtin_ia32_vpdpwssd_v8si_maskz(__gcc_v8si, __gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_vpdpwssd_v4si(__gcc_v4si, __gcc_v4si, __gcc_v4si);
__gcc_v4si __builtin_ia32_vpdpwssd_v4si_mask(__gcc_v4si, __gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v4si __builtin_ia32_vpdpwssd_v4si_maskz(__gcc_v4si, __gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v16si __builtin_ia32_vpdpwssds_v16si(__gcc_v16si, __gcc_v16si, __gcc_v16si);
__gcc_v16si __builtin_ia32_vpdpwssds_v16si_mask(__gcc_v16si, __gcc_v16si, __gcc_v16si, unsigned short);
__gcc_v16si __builtin_ia32_vpdpwssds_v16si_maskz(__gcc_v16si, __gcc_v16si, __gcc_v16si, unsigned short);
__gcc_v8si __builtin_ia32_vpdpwssds_v8si(__gcc_v8si, __gcc_v8si, __gcc_v8si);
__gcc_v8si __builtin_ia32_vpdpwssds_v8si_mask(__gcc_v8si, __gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v8si __builtin_ia32_vpdpwssds_v8si_maskz(__gcc_v8si, __gcc_v8si, __gcc_v8si, unsigned char);
__gcc_v4si __builtin_ia32_vpdpwssds_v4si(__gcc_v4si, __gcc_v4si, __gcc_v4si);
__gcc_v4si __builtin_ia32_vpdpwssds_v4si_mask(__gcc_v4si, __gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v4si __builtin_ia32_vpdpwssds_v4si_maskz(__gcc_v4si, __gcc_v4si, __gcc_v4si, unsigned char);
__gcc_v2di __builtin_ia32_vpclmulqdq_v2di(__gcc_v2di, __gcc_v2di, int);
__gcc_v4di __builtin_ia32_vpclmulqdq_v4di(__gcc_v4di, __gcc_v4di, int);
__gcc_v8di __builtin_ia32_vpclmulqdq_v8di(__gcc_v8di, __gcc_v8di, int);
__gcc_v4di __builtin_ia32_vpopcountq_v4di(__gcc_v4di);
__gcc_v4di __builtin_ia32_vpopcountq_v4di_mask(__gcc_v4di, __gcc_v4di, unsigned char);
__gcc_v2di __builtin_ia32_vpopcountq_v2di(__gcc_v2di);
__gcc_v2di __builtin_ia32_vpopcountq_v2di_mask(__gcc_v2di, __gcc_v2di, unsigned char);
__gcc_v4si __builtin_ia32_vpopcountd_v4si(__gcc_v4si);
__gcc_v4si __builtin_ia32_vpopcountd_v4si_mask(__gcc_v4si, __gcc_v4si, unsigned short);
__gcc_v8si __builtin_ia32_vpopcountd_v8si(__gcc_v8si);
__gcc_v8si __builtin_ia32_vpopcountd_v8si_mask(__gcc_v8si, __gcc_v8si, unsigned short);
__gcc_v64qi __builtin_ia32_vpopcountb_v64qi(__gcc_v64qi);
__gcc_v64qi __builtin_ia32_vpopcountb_v64qi_mask(__gcc_v64qi, __gcc_v64qi, unsigned long long);
__gcc_v32qi __builtin_ia32_vpopcountb_v32qi(__gcc_v32qi);
__gcc_v32qi __builtin_ia32_vpopcountb_v32qi_mask(__gcc_v32qi, __gcc_v32qi, unsigned);
__gcc_v16qi __builtin_ia32_vpopcountb_v16qi(__gcc_v16qi);
__gcc_v16qi __builtin_ia32_vpopcountb_v16qi_mask(__gcc_v16qi, __gcc_v16qi, unsigned short);
__gcc_v32hi __builtin_ia32_vpopcountw_v32hi(__gcc_v32hi);
__gcc_v32hi __builtin_ia32_vpopcountw_v32hi_mask(__gcc_v32hi, __gcc_v32hi, unsigned);
__gcc_v16hi __builtin_ia32_vpopcountw_v16hi(__gcc_v16hi);
__gcc_v16hi __builtin_ia32_vpopcountw_v16hi_mask(__gcc_v16hi, __gcc_v16hi, unsigned short);
__gcc_v8hi __builtin_ia32_vpopcountw_v8hi(__gcc_v8hi);
__gcc_v8hi __builtin_ia32_vpopcountw_v8hi_mask(__gcc_v8hi, __gcc_v8hi, unsigned char);
unsigned long long __builtin_ia32_vpshufbitqmb512_mask(__gcc_v64qi, __gcc_v64qi, unsigned long long);
unsigned __builtin_ia32_vpshufbitqmb256_mask(__gcc_v32qi, __gcc_v32qi, unsigned);
unsigned short __builtin_ia32_vpshufbitqmb128_mask(__gcc_v16qi, __gcc_v16qi, unsigned short);
__gcc_v16qi __builtin_ia32_vaesdec_v16qi(__gcc_v16qi, __gcc_v16qi);
__gcc_v32qi __builtin_ia32_vaesdec_v32qi(__gcc_v32qi, __gcc_v32qi);
__gcc_v64qi __builtin_ia32_vaesdec_v64qi(__gcc_v64qi, __gcc_v64qi);
__gcc_v16qi __builtin_ia32_vaesdeclast_v16qi(__gcc_v16qi, __gcc_v16qi);
__gcc_v32qi __builtin_ia32_vaesdeclast_v32qi(__gcc_v32qi, __gcc_v32qi);
__gcc_v64qi __builtin_ia32_vaesdeclast_v64qi(__gcc_v64qi, __gcc_v64qi);
__gcc_v16qi __builtin_ia32_vaesenc_v16qi(__gcc_v16qi, __gcc_v16qi);
__gcc_v32qi __builtin_ia32_vaesenc_v32qi(__gcc_v32qi, __gcc_v32qi);
__gcc_v64qi __builtin_ia32_vaesenc_v64qi(__gcc_v64qi, __gcc_v64qi);
__gcc_v16qi __builtin_ia32_vaesenclast_v16qi(__gcc_v16qi, __gcc_v16qi);
__gcc_v32qi __builtin_ia32_vaesenclast_v32qi(__gcc_v32qi, __gcc_v32qi);
__gcc_v64qi __builtin_ia32_vaesenclast_v64qi(__gcc_v64qi, __gcc_v64qi);
__gcc_v32hi __builtin_ia32_cvtne2ps2bf16_v32hi(__gcc_v16sf, __gcc_v16sf);
__gcc_v32hi __builtin_ia32_cvtne2ps2bf16_v32hi_mask(__gcc_v16sf, __gcc_v16sf, __gcc_v32hi, unsigned);
__gcc_v32hi __builtin_ia32_cvtne2ps2bf16_v32hi_maskz(__gcc_v16sf, __gcc_v16sf, unsigned);
__gcc_v16hi __builtin_ia32_cvtne2ps2bf16_v16hi(__gcc_v8sf, __gcc_v8sf);
__gcc_v16hi __builtin_ia32_cvtne2ps2bf16_v16hi_mask(__gcc_v8sf, __gcc_v8sf, __gcc_v16hi, unsigned short);
__gcc_v16hi __builtin_ia32_cvtne2ps2bf16_v16hi_maskz(__gcc_v8sf, __gcc_v8sf, unsigned short);
__gcc_v8hi __builtin_ia32_cvtne2ps2bf16_v8hi(__gcc_v4sf, __gcc_v4sf);
__gcc_v8hi __builtin_ia32_cvtne2ps2bf16_v8hi_mask(__gcc_v4sf, __gcc_v4sf, __gcc_v8hi, unsigned char);
__gcc_v8hi __builtin_ia32_cvtne2ps2bf16_v8hi_maskz(__gcc_v4sf, __gcc_v4sf, unsigned char);
__gcc_v16hi __builtin_ia32_cvtneps2bf16_v16sf(__gcc_v16sf);
__gcc_v16hi __builtin_ia32_cvtneps2bf16_v16sf_mask(__gcc_v16sf, __gcc_v16hi, unsigned short);
__gcc_v16hi __builtin_ia32_cvtneps2bf16_v16sf_maskz(__gcc_v16sf, unsigned short);
__gcc_v8hi __builtin_ia32_cvtneps2bf16_v8sf(__gcc_v8sf);
__gcc_v8hi __builtin_ia32_cvtneps2bf16_v8sf_mask(__gcc_v8sf, __gcc_v8hi, unsigned char);
__gcc_v8hi __builtin_ia32_cvtneps2bf16_v8sf_maskz(__gcc_v8sf, unsigned char);
__gcc_v8hi __builtin_ia32_cvtneps2bf16_v4sf(__gcc_v4sf);
__gcc_v8hi __builtin_ia32_cvtneps2bf16_v4sf_mask(__gcc_v4sf, __gcc_v8hi, unsigned char);
__gcc_v8hi __builtin_ia32_cvtneps2bf16_v4sf_maskz(__gcc_v4sf, unsigned char);
__gcc_v16sf __builtin_ia32_dpbf16ps_v16sf(__gcc_v16sf, __gcc_v32hi, __gcc_v32hi);
__gcc_v16sf __builtin_ia32_dpbf16ps_v16sf_mask(__gcc_v16sf, __gcc_v32hi, __gcc_v32hi, unsigned short);
__gcc_v16sf __builtin_ia32_dpbf16ps_v16sf_maskz(__gcc_v16sf, __gcc_v32hi, __gcc_v32hi, unsigned short);
__gcc_v8sf __builtin_ia32_dpbf16ps_v8sf(__gcc_v8sf, __gcc_v16hi, __gcc_v16hi);
__gcc_v8sf __builtin_ia32_dpbf16ps_v8sf_mask(__gcc_v8sf, __gcc_v16hi, __gcc_v16hi, unsigned char);
__gcc_v8sf __builtin_ia32_dpbf16ps_v8sf_maskz(__gcc_v8sf, __gcc_v16hi, __gcc_v16hi, unsigned char);
__gcc_v4sf __builtin_ia32_dpbf16ps_v4sf(__gcc_v4sf, __gcc_v8hi, __gcc_v8hi);
__gcc_v4sf __builtin_ia32_dpbf16ps_v4sf_mask(__gcc_v4sf, __gcc_v8hi, __gcc_v8hi, unsigned char);
__gcc_v4sf __builtin_ia32_dpbf16ps_v4sf_maskz(__gcc_v4sf, __gcc_v8hi, __gcc_v8hi, unsigned char);
__gcc_v2df __builtin_ia32_addsd_mask_round(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char, int);
__gcc_v4sf __builtin_ia32_addss_mask_round(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char, int);
__gcc_v4sf __builtin_ia32_cvtsd2ss_mask_round(__gcc_v4sf, __gcc_v2df, __gcc_v4sf, unsigned char, int);
__gcc_v2df __builtin_ia32_cvtss2sd_mask_round(__gcc_v2df, __gcc_v4sf, __gcc_v2df, unsigned char, int);
__gcc_v2df __builtin_ia32_divsd_mask_round(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char, int);
__gcc_v4sf __builtin_ia32_divss_mask_round(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char, int);
__gcc_v2df __builtin_ia32_getexpsd_mask_round(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char, int);
__gcc_v4sf __builtin_ia32_getexpss_mask_round(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char, int);
__gcc_v2df __builtin_ia32_getmantsd_mask_round(__gcc_v2df, __gcc_v2df, int, __gcc_v2df, unsigned char, int);
__gcc_v4sf __builtin_ia32_getmantss_mask_round(__gcc_v4sf, __gcc_v4sf, int, __gcc_v4sf, unsigned char, int);
__gcc_v2df __builtin_ia32_maxsd_mask_round(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char, int);
__gcc_v4sf __builtin_ia32_maxss_mask_round(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char, int);
__gcc_v2df __builtin_ia32_minsd_mask_round(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char, int);
__gcc_v4sf __builtin_ia32_minss_mask_round(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char, int);
__gcc_v2df __builtin_ia32_mulsd_mask_round(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char, int);
__gcc_v4sf __builtin_ia32_mulss_mask_round(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char, int);
__gcc_v2df __builtin_ia32_rndscalesd_mask_round(__gcc_v2df, __gcc_v2df, int, __gcc_v2df, unsigned char, int);
__gcc_v4sf __builtin_ia32_rndscaless_mask_round(__gcc_v4sf, __gcc_v4sf, int, __gcc_v4sf, unsigned char, int);
__gcc_v2df __builtin_ia32_scalefsd_mask_round(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char, int);
__gcc_v4sf __builtin_ia32_scalefss_mask_round(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char, int);
__gcc_v2df __builtin_ia32_sqrtsd_mask_round(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char, int);
__gcc_v4sf __builtin_ia32_sqrtss_mask_round(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char, int);
__gcc_v2df __builtin_ia32_subsd_mask_round(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char, int);
__gcc_v4sf __builtin_ia32_subss_mask_round(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char, int);
__gcc_v2df __builtin_ia32_vfmaddsd3_mask(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char, int);
__gcc_v2df __builtin_ia32_vfmaddsd3_mask3(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char, int);
__gcc_v2df __builtin_ia32_vfmaddsd3_maskz(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char, int);
__gcc_v2df __builtin_ia32_vfmsubsd3_mask3(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char, int);
__gcc_v4sf __builtin_ia32_vfmaddss3_mask(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char, int);
__gcc_v4sf __builtin_ia32_vfmaddss3_mask3(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char, int);
__gcc_v4sf __builtin_ia32_vfmaddss3_maskz(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char, int);
__gcc_v4sf __builtin_ia32_vfmsubss3_mask3(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char, int);
__gcc_v8df __builtin_ia32_vfmsubpd512_mask(__gcc_v8df, __gcc_v8df, __gcc_v8df, unsigned char, int);
__gcc_v8df __builtin_ia32_vfmsubpd512_maskz(__gcc_v8df, __gcc_v8df, __gcc_v8df, unsigned char, int);
__gcc_v16sf __builtin_ia32_vfmsubps512_mask(__gcc_v16sf, __gcc_v16sf, __gcc_v16sf, short, int);
__gcc_v16sf __builtin_ia32_vfmsubps512_maskz(__gcc_v16sf, __gcc_v16sf, __gcc_v16sf, short, int);
__gcc_v8df __builtin_ia32_vfnmaddpd512_mask3(__gcc_v8df, __gcc_v8df, __gcc_v8df, unsigned char, int);
__gcc_v8df __builtin_ia32_vfnmaddpd512_maskz(__gcc_v8df, __gcc_v8df, __gcc_v8df, unsigned char, int);
__gcc_v16sf __builtin_ia32_vfnmaddps512_mask3(__gcc_v16sf, __gcc_v16sf, __gcc_v16sf, short, int);
__gcc_v16sf __builtin_ia32_vfnmaddps512_maskz(__gcc_v16sf, __gcc_v16sf, __gcc_v16sf, short, int);
__gcc_v8df __builtin_ia32_vfnmsubpd512_maskz(__gcc_v8df, __gcc_v8df, __gcc_v8df, unsigned char, int);
__gcc_v16sf __builtin_ia32_vfnmsubps512_maskz(__gcc_v16sf, __gcc_v16sf, __gcc_v16sf, short, int);
__gcc_v2df __builtin_ia32_rcp28sd_mask_round(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char, int);
__gcc_v4sf __builtin_ia32_rcp28ss_mask_round(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char, int);
__gcc_v2df __builtin_ia32_rsqrt28sd_mask_round(__gcc_v2df, __gcc_v2df, __gcc_v2df, unsigned char, int);
__gcc_v4sf __builtin_ia32_rsqrt28ss_mask_round(__gcc_v4sf, __gcc_v4sf, __gcc_v4sf, unsigned char, int);
__gcc_v8df __builtin_ia32_reducepd512_mask_round(__gcc_v8df, int, __gcc_v8df, unsigned char, int);
__gcc_v16sf __builtin_ia32_reduceps512_mask_round(__gcc_v16sf, int, __gcc_v16sf, unsigned short, int);
__gcc_v2df __builtin_ia32_reducesd_mask_round(__gcc_v2df, __gcc_v2df, int, __gcc_v2df, unsigned char, int);
__gcc_v4sf __builtin_ia32_reducess_mask_round(__gcc_v4sf, __gcc_v4sf, int, __gcc_v4sf, unsigned char, int);
__gcc_v2df __builtin_ia32_rangesd128_mask_round(__gcc_v2df, __gcc_v2df, int, __gcc_v2df, unsigned char, int);
__gcc_v4sf __builtin_ia32_rangess128_mask_round(__gcc_v4sf, __gcc_v4sf, int, __gcc_v4sf, unsigned char, int);
unsigned __builtin_ia32_rdsspd();
unsigned long long __builtin_ia32_rdsspq();
void __builtin_ia32_incsspd(unsigned);
void __builtin_ia32_incsspq(unsigned long long);
void __builtin_ia32_saveprevssp();
void __builtin_ia32_rstorssp(void*);
void __builtin_ia32_wrssd(unsigned, void*);
void __builtin_ia32_wrssq(unsigned long long, void*);
void __builtin_ia32_wrussd(unsigned, void*);
void __builtin_ia32_wrussq(unsigned long long, void*);
void __builtin_ia32_setssbsy();
void __builtin_ia32_clrssbsy(void*);
// clang-format on
