// clang-format off
__gcc_v8qi __builtin_neon___a32_vcvt_bf16_f32(__gcc_v16qi, int);
__gcc_v8qi __builtin_neon_splat_lane_bf16(__gcc_v8qi, int, int);
__gcc_v8qi __builtin_neon_splat_lane_v(__gcc_v8qi, int, int);
__gcc_v8qi __builtin_neon_splat_laneq_bf16(__gcc_v16qi, int, int);
__gcc_v8qi __builtin_neon_splat_laneq_v(__gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_splatq_lane_bf16(__gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_splatq_lane_v(__gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_splatq_laneq_bf16(__gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_splatq_laneq_v(__gcc_v16qi, int, int);
__gcc_v8qi __builtin_neon_vabd_f16(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vabd_v(__gcc_v8qi, __gcc_v8qi, int);
double __builtin_neon_vabdd_f64(double, double);
__gcc_v16qi __builtin_neon_vabdq_f16(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vabdq_v(__gcc_v16qi, __gcc_v16qi, int);
float __builtin_neon_vabds_f32(float, float);
__gcc_v8qi __builtin_neon_vabs_f16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vabs_v(__gcc_v8qi, int);
long long __builtin_neon_vabsd_s64(long long);
__gcc_v16qi __builtin_neon_vabsq_f16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vabsq_v(__gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vadd_v(__gcc_v8qi, __gcc_v8qi, int);
long long __builtin_neon_vaddd_s64(long long, long long);
unsigned long long __builtin_neon_vaddd_u64(unsigned long long, unsigned long long);
__gcc_v8qi __builtin_neon_vaddhn_v(__gcc_v16qi, __gcc_v16qi, int);
int __builtin_neon_vaddlv_s16(__gcc_v4hi);
long long __builtin_neon_vaddlv_s32(__gcc_v2si);
short __builtin_neon_vaddlv_s8(__gcc_v8qi);
int __builtin_neon_vaddlvq_s16(__gcc_v8hi);
long long __builtin_neon_vaddlvq_s32(__gcc_v4si);
short __builtin_neon_vaddlvq_s8(__gcc_v16qi);
unsigned int __builtin_neon_vaddlvq_u16(__gcc_v8uhi);
unsigned long long __builtin_neon_vaddlvq_u32(__gcc_v4usi);
unsigned __int128 __builtin_neon_vaddq_p128(unsigned __int128, unsigned __int128);
__gcc_v16qi __builtin_neon_vaddq_v(__gcc_v16qi, __gcc_v16qi, int);
float __builtin_neon_vaddv_f32(__gcc_v2sf);
short __builtin_neon_vaddv_s16(__gcc_v4hi);
int __builtin_neon_vaddv_s32(__gcc_v2si);
signed char __builtin_neon_vaddv_s8(__gcc_v8qi);
float __builtin_neon_vaddvq_f32(__gcc_v4sf);
double __builtin_neon_vaddvq_f64(__gcc_v2df);
short __builtin_neon_vaddvq_s16(__gcc_v8hi);
int __builtin_neon_vaddvq_s32(__gcc_v4si);
long long __builtin_neon_vaddvq_s64(__gcc_v2di);
signed char __builtin_neon_vaddvq_s8(__gcc_v16qi);
unsigned short __builtin_neon_vaddvq_u16(__gcc_v8uhi);
unsigned int __builtin_neon_vaddvq_u32(__gcc_v4usi);
unsigned long long __builtin_neon_vaddvq_u64(__gcc_v2udi);
__gcc_v16qi __builtin_neon_vaesdq_u8(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vaeseq_u8(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vaesimcq_u8(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vaesmcq_u8(__gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vamax_f16(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vamax_f32(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vamaxq_f16(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vamaxq_f32(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vamaxq_f64(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vamin_f16(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vamin_f32(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vaminq_f16(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vaminq_f32(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vaminq_f64(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vbcaxq_s16(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vbcaxq_s32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vbcaxq_s64(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vbcaxq_s8(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vbcaxq_u16(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vbcaxq_u32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vbcaxq_u64(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vbcaxq_u8(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vbfdot_f32(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vbfdotq_f32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vbfmlalbq_f32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vbfmlaltq_f32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vbfmmlaq_f32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vbsl_v(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vbslq_v(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vcadd_rot270_f16(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcadd_rot270_f32(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcadd_rot90_f16(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcadd_rot90_f32(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vcaddq_rot270_f16(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcaddq_rot270_f32(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcaddq_rot270_f64(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcaddq_rot90_f16(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcaddq_rot90_f32(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcaddq_rot90_f64(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vcage_f16(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcage_v(__gcc_v8qi, __gcc_v8qi, int);
unsigned long long __builtin_neon_vcaged_f64(double, double);
__gcc_v16qi __builtin_neon_vcageq_f16(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcageq_v(__gcc_v16qi, __gcc_v16qi, int);
unsigned int __builtin_neon_vcages_f32(float, float);
__gcc_v8qi __builtin_neon_vcagt_f16(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcagt_v(__gcc_v8qi, __gcc_v8qi, int);
unsigned long long __builtin_neon_vcagtd_f64(double, double);
__gcc_v16qi __builtin_neon_vcagtq_f16(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcagtq_v(__gcc_v16qi, __gcc_v16qi, int);
unsigned int __builtin_neon_vcagts_f32(float, float);
__gcc_v8qi __builtin_neon_vcale_f16(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcale_v(__gcc_v8qi, __gcc_v8qi, int);
unsigned long long __builtin_neon_vcaled_f64(double, double);
__gcc_v16qi __builtin_neon_vcaleq_f16(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcaleq_v(__gcc_v16qi, __gcc_v16qi, int);
unsigned int __builtin_neon_vcales_f32(float, float);
__gcc_v8qi __builtin_neon_vcalt_f16(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcalt_v(__gcc_v8qi, __gcc_v8qi, int);
unsigned long long __builtin_neon_vcaltd_f64(double, double);
__gcc_v16qi __builtin_neon_vcaltq_f16(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcaltq_v(__gcc_v16qi, __gcc_v16qi, int);
unsigned int __builtin_neon_vcalts_f32(float, float);
unsigned long long __builtin_neon_vceqd_f64(double, double);
unsigned long long __builtin_neon_vceqd_s64(long long, long long);
unsigned long long __builtin_neon_vceqd_u64(unsigned long long, unsigned long long);
unsigned int __builtin_neon_vceqs_f32(float, float);
__gcc_v8qi __builtin_neon_vceqz_f16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vceqz_v(__gcc_v8qi, int);
unsigned long long __builtin_neon_vceqzd_f64(double);
unsigned long long __builtin_neon_vceqzd_s64(long long);
unsigned long long __builtin_neon_vceqzd_u64(unsigned long long);
__gcc_v16qi __builtin_neon_vceqzq_f16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vceqzq_v(__gcc_v16qi, int);
unsigned int __builtin_neon_vceqzs_f32(float);
unsigned long long __builtin_neon_vcged_f64(double, double);
unsigned long long __builtin_neon_vcged_s64(long long, long long);
unsigned long long __builtin_neon_vcged_u64(unsigned long long, unsigned long long);
unsigned int __builtin_neon_vcges_f32(float, float);
__gcc_v8qi __builtin_neon_vcgez_f16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcgez_v(__gcc_v8qi, int);
unsigned long long __builtin_neon_vcgezd_f64(double);
unsigned long long __builtin_neon_vcgezd_s64(long long);
__gcc_v16qi __builtin_neon_vcgezq_f16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcgezq_v(__gcc_v16qi, int);
unsigned int __builtin_neon_vcgezs_f32(float);
unsigned long long __builtin_neon_vcgtd_f64(double, double);
unsigned long long __builtin_neon_vcgtd_s64(long long, long long);
unsigned long long __builtin_neon_vcgtd_u64(unsigned long long, unsigned long long);
unsigned int __builtin_neon_vcgts_f32(float, float);
__gcc_v8qi __builtin_neon_vcgtz_f16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcgtz_v(__gcc_v8qi, int);
unsigned long long __builtin_neon_vcgtzd_f64(double);
unsigned long long __builtin_neon_vcgtzd_s64(long long);
__gcc_v16qi __builtin_neon_vcgtzq_f16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcgtzq_v(__gcc_v16qi, int);
unsigned int __builtin_neon_vcgtzs_f32(float);
unsigned long long __builtin_neon_vcled_f64(double, double);
unsigned long long __builtin_neon_vcled_s64(long long, long long);
unsigned long long __builtin_neon_vcled_u64(unsigned long long, unsigned long long);
unsigned int __builtin_neon_vcles_f32(float, float);
__gcc_v8qi __builtin_neon_vclez_f16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vclez_v(__gcc_v8qi, int);
unsigned long long __builtin_neon_vclezd_f64(double);
unsigned long long __builtin_neon_vclezd_s64(long long);
__gcc_v16qi __builtin_neon_vclezq_f16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vclezq_v(__gcc_v16qi, int);
unsigned int __builtin_neon_vclezs_f32(float);
__gcc_v8qi __builtin_neon_vcls_v(__gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vclsq_v(__gcc_v16qi, int);
unsigned long long __builtin_neon_vcltd_f64(double, double);
unsigned long long __builtin_neon_vcltd_s64(long long, long long);
unsigned long long __builtin_neon_vcltd_u64(unsigned long long, unsigned long long);
unsigned int __builtin_neon_vclts_f32(float, float);
__gcc_v8qi __builtin_neon_vcltz_f16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcltz_v(__gcc_v8qi, int);
unsigned long long __builtin_neon_vcltzd_f64(double);
unsigned long long __builtin_neon_vcltzd_s64(long long);
__gcc_v16qi __builtin_neon_vcltzq_f16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcltzq_v(__gcc_v16qi, int);
unsigned int __builtin_neon_vcltzs_f32(float);
__gcc_v8qi __builtin_neon_vclz_v(__gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vclzq_v(__gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vcmla_f16(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcmla_f32(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcmla_rot180_f16(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcmla_rot180_f32(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcmla_rot270_f16(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcmla_rot270_f32(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcmla_rot90_f16(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcmla_rot90_f32(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vcmlaq_f16(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcmlaq_f32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcmlaq_f64(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcmlaq_rot180_f16(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcmlaq_rot180_f32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcmlaq_rot180_f64(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcmlaq_rot270_f16(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcmlaq_rot270_f32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcmlaq_rot270_f64(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcmlaq_rot90_f16(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcmlaq_rot90_f32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcmlaq_rot90_f64(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vcnt_v(__gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vcntq_v(__gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vcvt_bf16_f32(__gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vcvt_f16_f32(__gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vcvt_f16_s16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvt_f16_u16(__gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vcvt_f32_f16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvt_f32_f64(__gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vcvt_f32_v(__gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vcvt_f64_f32(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvt_f64_v(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvt_n_f16_s16(__gcc_v8qi, int, int);
__gcc_v8qi __builtin_neon_vcvt_n_f16_u16(__gcc_v8qi, int, int);
__gcc_v8qi __builtin_neon_vcvt_n_f32_v(__gcc_v8qi, int, int);
__gcc_v8qi __builtin_neon_vcvt_n_f64_v(__gcc_v8qi, int, int);
__gcc_v8qi __builtin_neon_vcvt_n_s16_f16(__gcc_v8qi, int, int);
__gcc_v8qi __builtin_neon_vcvt_n_s32_v(__gcc_v8qi, int, int);
__gcc_v8qi __builtin_neon_vcvt_n_s64_v(__gcc_v8qi, int, int);
__gcc_v8qi __builtin_neon_vcvt_n_u16_f16(__gcc_v8qi, int, int);
__gcc_v8qi __builtin_neon_vcvt_n_u32_v(__gcc_v8qi, int, int);
__gcc_v8qi __builtin_neon_vcvt_n_u64_v(__gcc_v8qi, int, int);
__gcc_v8qi __builtin_neon_vcvt_s16_f16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvt_s32_v(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvt_s64_v(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvt_u16_f16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvt_u32_v(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvt_u64_v(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvta_s16_f16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvta_s32_v(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvta_s64_v(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvta_u16_f16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvta_u32_v(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvta_u64_v(__gcc_v8qi, int);
int __builtin_neon_vcvtad_s32_f64(double);
long long __builtin_neon_vcvtad_s64_f64(double);
unsigned int __builtin_neon_vcvtad_u32_f64(double);
unsigned long long __builtin_neon_vcvtad_u64_f64(double);
__gcc_v16qi __builtin_neon_vcvtaq_s16_f16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtaq_s32_v(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtaq_s64_v(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtaq_u16_f16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtaq_u32_v(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtaq_u64_v(__gcc_v16qi, int);
int __builtin_neon_vcvtas_s32_f32(float);
long long __builtin_neon_vcvtas_s64_f32(float);
unsigned int __builtin_neon_vcvtas_u32_f32(float);
unsigned long long __builtin_neon_vcvtas_u64_f32(float);
double __builtin_neon_vcvtd_f64_s64(long long);
double __builtin_neon_vcvtd_f64_u64(unsigned long long);
double __builtin_neon_vcvtd_n_f64_s64(long long, int);
double __builtin_neon_vcvtd_n_f64_u64(unsigned long long, int);
long long __builtin_neon_vcvtd_n_s64_f64(double, int);
unsigned long long __builtin_neon_vcvtd_n_u64_f64(double, int);
int __builtin_neon_vcvtd_s32_f64(double);
long long __builtin_neon_vcvtd_s64_f64(double);
unsigned int __builtin_neon_vcvtd_u32_f64(double);
unsigned long long __builtin_neon_vcvtd_u64_f64(double);
__bf16 __builtin_neon_vcvth_bf16_f32(float);
__gcc_v8qi __builtin_neon_vcvtm_s16_f16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvtm_s32_v(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvtm_s64_v(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvtm_u16_f16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvtm_u32_v(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvtm_u64_v(__gcc_v8qi, int);
int __builtin_neon_vcvtmd_s32_f64(double);
long long __builtin_neon_vcvtmd_s64_f64(double);
unsigned int __builtin_neon_vcvtmd_u32_f64(double);
unsigned long long __builtin_neon_vcvtmd_u64_f64(double);
__gcc_v16qi __builtin_neon_vcvtmq_s16_f16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtmq_s32_v(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtmq_s64_v(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtmq_u16_f16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtmq_u32_v(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtmq_u64_v(__gcc_v16qi, int);
int __builtin_neon_vcvtms_s32_f32(float);
long long __builtin_neon_vcvtms_s64_f32(float);
unsigned int __builtin_neon_vcvtms_u32_f32(float);
unsigned long long __builtin_neon_vcvtms_u64_f32(float);
__gcc_v8qi __builtin_neon_vcvtn_s16_f16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvtn_s32_v(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvtn_s64_v(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvtn_u16_f16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvtn_u32_v(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvtn_u64_v(__gcc_v8qi, int);
int __builtin_neon_vcvtnd_s32_f64(double);
long long __builtin_neon_vcvtnd_s64_f64(double);
unsigned int __builtin_neon_vcvtnd_u32_f64(double);
unsigned long long __builtin_neon_vcvtnd_u64_f64(double);
__gcc_v16qi __builtin_neon_vcvtnq_s16_f16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtnq_s32_v(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtnq_s64_v(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtnq_u16_f16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtnq_u32_v(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtnq_u64_v(__gcc_v16qi, int);
int __builtin_neon_vcvtns_s32_f32(float);
long long __builtin_neon_vcvtns_s64_f32(float);
unsigned int __builtin_neon_vcvtns_u32_f32(float);
unsigned long long __builtin_neon_vcvtns_u64_f32(float);
__gcc_v8qi __builtin_neon_vcvtp_s16_f16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvtp_s32_v(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvtp_s64_v(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvtp_u16_f16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvtp_u32_v(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vcvtp_u64_v(__gcc_v8qi, int);
int __builtin_neon_vcvtpd_s32_f64(double);
long long __builtin_neon_vcvtpd_s64_f64(double);
unsigned int __builtin_neon_vcvtpd_u32_f64(double);
unsigned long long __builtin_neon_vcvtpd_u64_f64(double);
__gcc_v16qi __builtin_neon_vcvtpq_s16_f16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtpq_s32_v(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtpq_s64_v(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtpq_u16_f16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtpq_u32_v(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtpq_u64_v(__gcc_v16qi, int);
int __builtin_neon_vcvtps_s32_f32(float);
long long __builtin_neon_vcvtps_s64_f32(float);
unsigned int __builtin_neon_vcvtps_u32_f32(float);
unsigned long long __builtin_neon_vcvtps_u64_f32(float);
__gcc_v16qi __builtin_neon_vcvtq_f16_s16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtq_f16_u16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtq_f32_v(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtq_f64_v(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtq_high_bf16_f32(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtq_low_bf16_f32(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtq_n_f16_s16(__gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vcvtq_n_f16_u16(__gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vcvtq_n_f32_v(__gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vcvtq_n_f64_v(__gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vcvtq_n_s16_f16(__gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vcvtq_n_s32_v(__gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vcvtq_n_s64_v(__gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vcvtq_n_u16_f16(__gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vcvtq_n_u32_v(__gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vcvtq_n_u64_v(__gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vcvtq_s16_f16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtq_s32_v(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtq_s64_v(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtq_u16_f16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtq_u32_v(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vcvtq_u64_v(__gcc_v16qi, int);
float __builtin_neon_vcvts_f32_s32(int);
float __builtin_neon_vcvts_f32_u32(unsigned int);
float __builtin_neon_vcvts_n_f32_s32(int, int);
float __builtin_neon_vcvts_n_f32_u32(unsigned int, int);
int __builtin_neon_vcvts_n_s32_f32(float, int);
unsigned int __builtin_neon_vcvts_n_u32_f32(float, int);
int __builtin_neon_vcvts_s32_f32(float);
long long __builtin_neon_vcvts_s64_f32(float);
unsigned int __builtin_neon_vcvts_u32_f32(float);
unsigned long long __builtin_neon_vcvts_u64_f32(float);
__gcc_v8qi __builtin_neon_vcvtx_f32_v(__gcc_v16qi, int);
float __builtin_neon_vcvtxd_f32_f64(double);
__gcc_v8qi __builtin_neon_vdot_f32_f16(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vdot_lane_f32_f16(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int, int);
__gcc_v8qi __builtin_neon_vdot_laneq_f32_f16(__gcc_v8qi, __gcc_v8qi, __gcc_v16qi, int, int);
__gcc_v8qi __builtin_neon_vdot_s32(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vdot_u32(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vdotq_f32_f16(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vdotq_lane_f32_f16(__gcc_v16qi, __gcc_v16qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vdotq_laneq_f32_f16(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vdotq_s32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vdotq_u32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
unsigned char __builtin_neon_vdupb_lane_i8(__gcc_v8qi, int);
unsigned char __builtin_neon_vdupb_laneq_i8(__gcc_v16qi, int);
unsigned long long __builtin_neon_vdupd_lane_i64(__gcc_v1di, int);
double __builtin_neon_vdupd_laneq_f64(__gcc_v2df, int);
unsigned long long __builtin_neon_vdupd_laneq_i64(__gcc_v2di, int);
unsigned short __builtin_neon_vduph_lane_i16(__gcc_v4hi, int);
__bf16 __builtin_neon_vduph_laneq_bf16(__gcc_v8hf, int);
_Float16 __builtin_neon_vduph_laneq_f16(__gcc_v8hf, int);
unsigned short __builtin_neon_vduph_laneq_i16(__gcc_v8hi, int);
float __builtin_neon_vdups_lane_f32(__gcc_v2sf, int);
unsigned int __builtin_neon_vdups_lane_i32(__gcc_v2si, int);
float __builtin_neon_vdups_laneq_f32(__gcc_v4sf, int);
unsigned int __builtin_neon_vdups_laneq_i32(__gcc_v4si, int);
__gcc_v16qi __builtin_neon_veor3q_s16(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_veor3q_s32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_veor3q_s64(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_veor3q_s8(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_veor3q_u16(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_veor3q_u32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_veor3q_u64(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_veor3q_u8(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vext_v(__gcc_v8qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vextq_v(__gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v8qi __builtin_neon_vfma_f16(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vfma_lane_f16(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int, int);
__gcc_v8qi __builtin_neon_vfma_lane_v(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int, int);
__gcc_v8qi __builtin_neon_vfma_laneq_f16(__gcc_v8qi, __gcc_v8qi, __gcc_v16qi, int, int);
__gcc_v8qi __builtin_neon_vfma_laneq_v(__gcc_v8qi, __gcc_v8qi, __gcc_v16qi, int, int);
__gcc_v8qi __builtin_neon_vfma_v(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
double __builtin_neon_vfmad_laneq_f64(double, double, __gcc_v2df, int);
_Float16 __builtin_neon_vfmah_laneq_f16(_Float16, _Float16, __gcc_v8hf, int);
__gcc_v16qi __builtin_neon_vfmaq_f16(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vfmaq_lane_f16(__gcc_v16qi, __gcc_v16qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vfmaq_lane_v(__gcc_v16qi, __gcc_v16qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vfmaq_laneq_f16(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vfmaq_laneq_v(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vfmaq_v(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
float __builtin_neon_vfmas_lane_f32(float, float, __gcc_v2sf, int);
float __builtin_neon_vfmas_laneq_f32(float, float, __gcc_v4sf, int);
__gcc_v8qi __builtin_neon_vfmlal_high_f16(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vfmlal_low_f16(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vfmlalq_high_f16(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vfmlalq_low_f16(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vfmlsl_high_f16(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vfmlsl_low_f16(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vfmlslq_high_f16(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vfmlslq_low_f16(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
float __builtin_neon_vget_lane_f32(__gcc_v2sf, int);
unsigned short __builtin_neon_vget_lane_i16(__gcc_v4hi, int);
unsigned int __builtin_neon_vget_lane_i32(__gcc_v2si, int);
unsigned long long __builtin_neon_vget_lane_i64(__gcc_v1di, int);
unsigned char __builtin_neon_vget_lane_i8(__gcc_v8qi, int);
__bf16 __builtin_neon_vgetq_lane_bf16(__gcc_v8hf, int);
float __builtin_neon_vgetq_lane_f32(__gcc_v4sf, int);
double __builtin_neon_vgetq_lane_f64(__gcc_v2df, int);
unsigned short __builtin_neon_vgetq_lane_i16(__gcc_v8hi, int);
unsigned int __builtin_neon_vgetq_lane_i32(__gcc_v4si, int);
unsigned long long __builtin_neon_vgetq_lane_i64(__gcc_v2di, int);
unsigned char __builtin_neon_vgetq_lane_i8(__gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vhadd_v(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vhaddq_v(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vhsub_v(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vhsubq_v(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vld1_bf16(const void *, int);
void __builtin_neon_vld1_bf16_x2(void *, const void *, int);
void __builtin_neon_vld1_bf16_x3(void *, const void *, int);
void __builtin_neon_vld1_bf16_x4(void *, const void *, int);
__gcc_v8qi __builtin_neon_vld1_dup_bf16(const void *, int);
__gcc_v8qi __builtin_neon_vld1_dup_v(const void *, int);
__gcc_v8qi __builtin_neon_vld1_lane_bf16(const void *, __gcc_v8qi, int, int);
__gcc_v8qi __builtin_neon_vld1_lane_v(const void *, __gcc_v8qi, int, int);
__gcc_v8qi __builtin_neon_vld1_v(const void *, int);
void __builtin_neon_vld1_x2_v(void *, const void *, int);
void __builtin_neon_vld1_x3_v(void *, const void *, int);
void __builtin_neon_vld1_x4_v(void *, const void *, int);
__gcc_v16qi __builtin_neon_vld1q_bf16(const void *, int);
void __builtin_neon_vld1q_bf16_x2(void *, const void *, int);
void __builtin_neon_vld1q_bf16_x3(void *, const void *, int);
void __builtin_neon_vld1q_bf16_x4(void *, const void *, int);
__gcc_v16qi __builtin_neon_vld1q_dup_bf16(const void *, int);
__gcc_v16qi __builtin_neon_vld1q_dup_v(const void *, int);
__gcc_v16qi __builtin_neon_vld1q_lane_bf16(const void *, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vld1q_lane_v(const void *, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vld1q_v(const void *, int);
void __builtin_neon_vld1q_x2_v(void *, const void *, int);
void __builtin_neon_vld1q_x3_v(void *, const void *, int);
void __builtin_neon_vld1q_x4_v(void *, const void *, int);
void __builtin_neon_vld2_bf16(void *, const void *, int);
void __builtin_neon_vld2_dup_bf16(void *, const void *, int);
void __builtin_neon_vld2_dup_v(void *, const void *, int);
void __builtin_neon_vld2_lane_bf16(void *, const void *, __gcc_v8qi, __gcc_v8qi, int, int);
void __builtin_neon_vld2_lane_v(void *, const void *, __gcc_v8qi, __gcc_v8qi, int, int);
void __builtin_neon_vld2_v(void *, const void *, int);
void __builtin_neon_vld2q_bf16(void *, const void *, int);
void __builtin_neon_vld2q_dup_bf16(void *, const void *, int);
void __builtin_neon_vld2q_dup_v(void *, const void *, int);
void __builtin_neon_vld2q_lane_bf16(void *, const void *, __gcc_v16qi, __gcc_v16qi, int, int);
void __builtin_neon_vld2q_lane_v(void *, const void *, __gcc_v16qi, __gcc_v16qi, int, int);
void __builtin_neon_vld2q_v(void *, const void *, int);
void __builtin_neon_vld3_bf16(void *, const void *, int);
void __builtin_neon_vld3_dup_bf16(void *, const void *, int);
void __builtin_neon_vld3_dup_v(void *, const void *, int);
void __builtin_neon_vld3_lane_bf16(void *, const void *, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int, int);
void __builtin_neon_vld3_lane_v(void *, const void *, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int, int);
void __builtin_neon_vld3_v(void *, const void *, int);
void __builtin_neon_vld3q_bf16(void *, const void *, int);
void __builtin_neon_vld3q_dup_bf16(void *, const void *, int);
void __builtin_neon_vld3q_dup_v(void *, const void *, int);
void __builtin_neon_vld3q_lane_bf16(void *, const void *, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int, int);
void __builtin_neon_vld3q_lane_v(void *, const void *, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int, int);
void __builtin_neon_vld3q_v(void *, const void *, int);
void __builtin_neon_vld4_bf16(void *, const void *, int);
void __builtin_neon_vld4_dup_bf16(void *, const void *, int);
void __builtin_neon_vld4_dup_v(void *, const void *, int);
void __builtin_neon_vld4_lane_bf16(void *, const void *, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int, int);
void __builtin_neon_vld4_lane_v(void *, const void *, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int, int);
void __builtin_neon_vld4_v(void *, const void *, int);
void __builtin_neon_vld4q_bf16(void *, const void *, int);
void __builtin_neon_vld4q_dup_bf16(void *, const void *, int);
void __builtin_neon_vld4q_dup_v(void *, const void *, int);
void __builtin_neon_vld4q_lane_bf16(void *, const void *, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int, int);
void __builtin_neon_vld4q_lane_v(void *, const void *, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int, int);
void __builtin_neon_vld4q_v(void *, const void *, int);
__gcc_v8qi __builtin_neon_vldap1_lane_f64(const void *, __gcc_v8qi, int, int);
__gcc_v8qi __builtin_neon_vldap1_lane_p64(const void *, __gcc_v8qi, int, int);
__gcc_v8qi __builtin_neon_vldap1_lane_s64(const void *, __gcc_v8qi, int, int);
__gcc_v8qi __builtin_neon_vldap1_lane_u64(const void *, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vldap1q_lane_f64(const void *, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vldap1q_lane_p64(const void *, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vldap1q_lane_s64(const void *, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vldap1q_lane_u64(const void *, __gcc_v16qi, int, int);
unsigned __int128 __builtin_neon_vldrq_p128(const void *);
__gcc_v16qi __builtin_neon_vluti2_lane_bf16(__gcc_v8qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vluti2_lane_f16(__gcc_v8qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vluti2_lane_mf8(__gcc_v8qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vluti2_lane_p16(__gcc_v8qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vluti2_lane_p8(__gcc_v8qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vluti2_lane_s16(__gcc_v8qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vluti2_lane_s8(__gcc_v8qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vluti2_lane_u16(__gcc_v8qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vluti2_lane_u8(__gcc_v8qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vluti2_laneq_bf16(__gcc_v8qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vluti2_laneq_f16(__gcc_v8qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vluti2_laneq_mf8(__gcc_v8qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vluti2_laneq_p16(__gcc_v8qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vluti2_laneq_p8(__gcc_v8qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vluti2_laneq_s16(__gcc_v8qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vluti2_laneq_s8(__gcc_v8qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vluti2_laneq_u16(__gcc_v8qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vluti2_laneq_u8(__gcc_v8qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vluti2q_lane_bf16(__gcc_v16qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vluti2q_lane_f16(__gcc_v16qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vluti2q_lane_mf8(__gcc_v16qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vluti2q_lane_p16(__gcc_v16qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vluti2q_lane_p8(__gcc_v16qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vluti2q_lane_s16(__gcc_v16qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vluti2q_lane_s8(__gcc_v16qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vluti2q_lane_u16(__gcc_v16qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vluti2q_lane_u8(__gcc_v16qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vluti2q_laneq_bf16(__gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vluti2q_laneq_f16(__gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vluti2q_laneq_mf8(__gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vluti2q_laneq_p16(__gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vluti2q_laneq_p8(__gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vluti2q_laneq_s16(__gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vluti2q_laneq_s8(__gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vluti2q_laneq_u16(__gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vluti2q_laneq_u8(__gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vluti4q_lane_bf16_x2(__gcc_v16qi, __gcc_v16qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vluti4q_lane_f16_x2(__gcc_v16qi, __gcc_v16qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vluti4q_lane_mf8(__gcc_v16qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vluti4q_lane_p16_x2(__gcc_v16qi, __gcc_v16qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vluti4q_lane_p8(__gcc_v16qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vluti4q_lane_s16_x2(__gcc_v16qi, __gcc_v16qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vluti4q_lane_s8(__gcc_v16qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vluti4q_lane_u16_x2(__gcc_v16qi, __gcc_v16qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vluti4q_lane_u8(__gcc_v16qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vluti4q_laneq_bf16_x2(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vluti4q_laneq_f16_x2(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vluti4q_laneq_mf8(__gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vluti4q_laneq_p16_x2(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vluti4q_laneq_p8(__gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vluti4q_laneq_s16_x2(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vluti4q_laneq_s8(__gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vluti4q_laneq_u16_x2(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vluti4q_laneq_u8(__gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v8qi __builtin_neon_vmax_f16(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vmax_v(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vmaxnm_f16(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vmaxnm_v(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vmaxnmq_f16(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vmaxnmq_v(__gcc_v16qi, __gcc_v16qi, int);
_Float16 __builtin_neon_vmaxnmv_f16(__gcc_v8qi);
float __builtin_neon_vmaxnmv_f32(__gcc_v2sf);
_Float16 __builtin_neon_vmaxnmvq_f16(__gcc_v16qi);
float __builtin_neon_vmaxnmvq_f32(__gcc_v4sf);
double __builtin_neon_vmaxnmvq_f64(__gcc_v2df);
__gcc_v16qi __builtin_neon_vmaxq_f16(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vmaxq_v(__gcc_v16qi, __gcc_v16qi, int);
_Float16 __builtin_neon_vmaxv_f16(__gcc_v8qi);
float __builtin_neon_vmaxv_f32(__gcc_v2sf);
short __builtin_neon_vmaxv_s16(__gcc_v4hi);
int __builtin_neon_vmaxv_s32(__gcc_v2si);
signed char __builtin_neon_vmaxv_s8(__gcc_v8qi);
_Float16 __builtin_neon_vmaxvq_f16(__gcc_v16qi);
float __builtin_neon_vmaxvq_f32(__gcc_v4sf);
double __builtin_neon_vmaxvq_f64(__gcc_v2df);
short __builtin_neon_vmaxvq_s16(__gcc_v8hi);
int __builtin_neon_vmaxvq_s32(__gcc_v4si);
signed char __builtin_neon_vmaxvq_s8(__gcc_v16qi);
unsigned short __builtin_neon_vmaxvq_u16(__gcc_v8uhi);
unsigned int __builtin_neon_vmaxvq_u32(__gcc_v4usi);
__gcc_v8qi __builtin_neon_vmin_f16(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vmin_v(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vminnm_f16(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vminnm_v(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vminnmq_f16(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vminnmq_v(__gcc_v16qi, __gcc_v16qi, int);
_Float16 __builtin_neon_vminnmv_f16(__gcc_v8qi);
float __builtin_neon_vminnmv_f32(__gcc_v2sf);
_Float16 __builtin_neon_vminnmvq_f16(__gcc_v16qi);
float __builtin_neon_vminnmvq_f32(__gcc_v4sf);
double __builtin_neon_vminnmvq_f64(__gcc_v2df);
__gcc_v16qi __builtin_neon_vminq_f16(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vminq_v(__gcc_v16qi, __gcc_v16qi, int);
_Float16 __builtin_neon_vminv_f16(__gcc_v8qi);
float __builtin_neon_vminv_f32(__gcc_v2sf);
short __builtin_neon_vminv_s16(__gcc_v4hi);
int __builtin_neon_vminv_s32(__gcc_v2si);
signed char __builtin_neon_vminv_s8(__gcc_v8qi);
_Float16 __builtin_neon_vminvq_f16(__gcc_v16qi);
float __builtin_neon_vminvq_f32(__gcc_v4sf);
double __builtin_neon_vminvq_f64(__gcc_v2df);
short __builtin_neon_vminvq_s16(__gcc_v8hi);
int __builtin_neon_vminvq_s32(__gcc_v4si);
signed char __builtin_neon_vminvq_s8(__gcc_v16qi);
unsigned short __builtin_neon_vminvq_u16(__gcc_v8uhi);
unsigned int __builtin_neon_vminvq_u32(__gcc_v4usi);
__gcc_v16qi __builtin_neon_vmmlaq_f16_f16(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vmmlaq_f32_f16(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vmmlaq_s32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vmmlaq_u32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vmovl_v(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vmovn_v(__gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vmul_lane_v(__gcc_v8qi, __gcc_v8qi, int, int);
__gcc_v8qi __builtin_neon_vmul_laneq_v(__gcc_v8qi, __gcc_v16qi, int, int);
__gcc_v8qi __builtin_neon_vmul_v(__gcc_v8qi, __gcc_v8qi, int);
unsigned __int128 __builtin_neon_vmull_p64(unsigned long long, unsigned long long);
__gcc_v16qi __builtin_neon_vmull_v(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vmulq_v(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vmulx_f16(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vmulx_v(__gcc_v8qi, __gcc_v8qi, int);
double __builtin_neon_vmulxd_f64(double, double);
_Float16 __builtin_neon_vmulxh_laneq_f16(_Float16, __gcc_v8hf, int);
__gcc_v16qi __builtin_neon_vmulxq_f16(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vmulxq_v(__gcc_v16qi, __gcc_v16qi, int);
float __builtin_neon_vmulxs_f32(float, float);
long long __builtin_neon_vnegd_s64(long long);
__gcc_v8qi __builtin_neon_vpadal_v(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vpadalq_v(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vpadd_f16(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vpadd_v(__gcc_v8qi, __gcc_v8qi, int);
double __builtin_neon_vpaddd_f64(__gcc_v2df);
long long __builtin_neon_vpaddd_s64(__gcc_v2di);
unsigned long long __builtin_neon_vpaddd_u64(__gcc_v2udi);
__gcc_v8qi __builtin_neon_vpaddl_v(__gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vpaddlq_v(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vpaddq_f16(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vpaddq_v(__gcc_v16qi, __gcc_v16qi, int);
float __builtin_neon_vpadds_f32(__gcc_v2sf);
__gcc_v8qi __builtin_neon_vpmax_f16(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vpmax_v(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vpmaxnm_f16(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vpmaxnm_v(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vpmaxnmq_f16(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vpmaxnmq_v(__gcc_v16qi, __gcc_v16qi, int);
double __builtin_neon_vpmaxnmqd_f64(__gcc_v2df);
float __builtin_neon_vpmaxnms_f32(__gcc_v2sf);
__gcc_v16qi __builtin_neon_vpmaxq_f16(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vpmaxq_v(__gcc_v16qi, __gcc_v16qi, int);
double __builtin_neon_vpmaxqd_f64(__gcc_v2df);
float __builtin_neon_vpmaxs_f32(__gcc_v2sf);
__gcc_v8qi __builtin_neon_vpmin_f16(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vpmin_v(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vpminnm_f16(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vpminnm_v(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vpminnmq_f16(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vpminnmq_v(__gcc_v16qi, __gcc_v16qi, int);
double __builtin_neon_vpminnmqd_f64(__gcc_v2df);
float __builtin_neon_vpminnms_f32(__gcc_v2sf);
__gcc_v16qi __builtin_neon_vpminq_f16(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vpminq_v(__gcc_v16qi, __gcc_v16qi, int);
double __builtin_neon_vpminqd_f64(__gcc_v2df);
float __builtin_neon_vpmins_f32(__gcc_v2sf);
__gcc_v8qi __builtin_neon_vqabs_v(__gcc_v8qi, int);
signed char __builtin_neon_vqabsb_s8(signed char);
long long __builtin_neon_vqabsd_s64(long long);
short __builtin_neon_vqabsh_s16(short);
__gcc_v16qi __builtin_neon_vqabsq_v(__gcc_v16qi, int);
int __builtin_neon_vqabss_s32(int);
__gcc_v8qi __builtin_neon_vqadd_v(__gcc_v8qi, __gcc_v8qi, int);
signed char __builtin_neon_vqaddb_s8(signed char, signed char);
unsigned char __builtin_neon_vqaddb_u8(unsigned char, unsigned char);
long long __builtin_neon_vqaddd_s64(long long, long long);
unsigned long long __builtin_neon_vqaddd_u64(unsigned long long, unsigned long long);
short __builtin_neon_vqaddh_s16(short, short);
unsigned short __builtin_neon_vqaddh_u16(unsigned short, unsigned short);
__gcc_v16qi __builtin_neon_vqaddq_v(__gcc_v16qi, __gcc_v16qi, int);
int __builtin_neon_vqadds_s32(int, int);
unsigned int __builtin_neon_vqadds_u32(unsigned int, unsigned int);
__gcc_v16qi __builtin_neon_vqdmlal_v(__gcc_v16qi, __gcc_v8qi, __gcc_v8qi, int);
int __builtin_neon_vqdmlalh_lane_s16(int, short, __gcc_v4hi, int);
int __builtin_neon_vqdmlalh_laneq_s16(int, short, __gcc_v8hi, int);
int __builtin_neon_vqdmlalh_s16(int, short, short);
long long __builtin_neon_vqdmlals_lane_s32(long long, int, __gcc_v2si, int);
long long __builtin_neon_vqdmlals_laneq_s32(long long, int, __gcc_v4si, int);
long long __builtin_neon_vqdmlals_s32(long long, int, int);
__gcc_v16qi __builtin_neon_vqdmlsl_v(__gcc_v16qi, __gcc_v8qi, __gcc_v8qi, int);
int __builtin_neon_vqdmlslh_lane_s16(int, short, __gcc_v4hi, int);
int __builtin_neon_vqdmlslh_laneq_s16(int, short, __gcc_v8hi, int);
int __builtin_neon_vqdmlslh_s16(int, short, short);
long long __builtin_neon_vqdmlsls_lane_s32(long long, int, __gcc_v2si, int);
long long __builtin_neon_vqdmlsls_laneq_s32(long long, int, __gcc_v4si, int);
long long __builtin_neon_vqdmlsls_s32(long long, int, int);
__gcc_v8qi __builtin_neon_vqdmulh_lane_v(__gcc_v8qi, __gcc_v8qi, int, int);
__gcc_v8qi __builtin_neon_vqdmulh_laneq_v(__gcc_v8qi, __gcc_v16qi, int, int);
__gcc_v8qi __builtin_neon_vqdmulh_v(__gcc_v8qi, __gcc_v8qi, int);
short __builtin_neon_vqdmulhh_s16(short, short);
__gcc_v16qi __builtin_neon_vqdmulhq_lane_v(__gcc_v16qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vqdmulhq_laneq_v(__gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vqdmulhq_v(__gcc_v16qi, __gcc_v16qi, int);
int __builtin_neon_vqdmulhs_s32(int, int);
__gcc_v16qi __builtin_neon_vqdmull_v(__gcc_v8qi, __gcc_v8qi, int);
int __builtin_neon_vqdmullh_s16(short, short);
long long __builtin_neon_vqdmulls_s32(int, int);
__gcc_v8qi __builtin_neon_vqmovn_v(__gcc_v16qi, int);
int __builtin_neon_vqmovnd_s64(long long);
unsigned int __builtin_neon_vqmovnd_u64(unsigned long long);
signed char __builtin_neon_vqmovnh_s16(short);
unsigned char __builtin_neon_vqmovnh_u16(unsigned short);
short __builtin_neon_vqmovns_s32(int);
unsigned short __builtin_neon_vqmovns_u32(unsigned int);
__gcc_v8qi __builtin_neon_vqmovun_v(__gcc_v16qi, int);
unsigned int __builtin_neon_vqmovund_s64(long long);
unsigned char __builtin_neon_vqmovunh_s16(short);
unsigned short __builtin_neon_vqmovuns_s32(int);
__gcc_v8qi __builtin_neon_vqneg_v(__gcc_v8qi, int);
signed char __builtin_neon_vqnegb_s8(signed char);
long long __builtin_neon_vqnegd_s64(long long);
short __builtin_neon_vqnegh_s16(short);
__gcc_v16qi __builtin_neon_vqnegq_v(__gcc_v16qi, int);
int __builtin_neon_vqnegs_s32(int);
__gcc_v8qi __builtin_neon_vqrdmlah_s16(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vqrdmlah_s32(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
short __builtin_neon_vqrdmlahh_s16(short, short, short);
__gcc_v16qi __builtin_neon_vqrdmlahq_s16(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vqrdmlahq_s32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
int __builtin_neon_vqrdmlahs_s32(int, int, int);
__gcc_v8qi __builtin_neon_vqrdmlsh_s16(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vqrdmlsh_s32(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
short __builtin_neon_vqrdmlshh_s16(short, short, short);
__gcc_v16qi __builtin_neon_vqrdmlshq_s16(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vqrdmlshq_s32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
int __builtin_neon_vqrdmlshs_s32(int, int, int);
__gcc_v8qi __builtin_neon_vqrdmulh_lane_v(__gcc_v8qi, __gcc_v8qi, int, int);
__gcc_v8qi __builtin_neon_vqrdmulh_laneq_v(__gcc_v8qi, __gcc_v16qi, int, int);
__gcc_v8qi __builtin_neon_vqrdmulh_v(__gcc_v8qi, __gcc_v8qi, int);
short __builtin_neon_vqrdmulhh_s16(short, short);
__gcc_v16qi __builtin_neon_vqrdmulhq_lane_v(__gcc_v16qi, __gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vqrdmulhq_laneq_v(__gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vqrdmulhq_v(__gcc_v16qi, __gcc_v16qi, int);
int __builtin_neon_vqrdmulhs_s32(int, int);
__gcc_v8qi __builtin_neon_vqrshl_v(__gcc_v8qi, __gcc_v8qi, int);
signed char __builtin_neon_vqrshlb_s8(signed char, signed char);
unsigned char __builtin_neon_vqrshlb_u8(unsigned char, signed char);
long long __builtin_neon_vqrshld_s64(long long, long long);
unsigned long long __builtin_neon_vqrshld_u64(unsigned long long, long long);
short __builtin_neon_vqrshlh_s16(short, short);
unsigned short __builtin_neon_vqrshlh_u16(unsigned short, short);
__gcc_v16qi __builtin_neon_vqrshlq_v(__gcc_v16qi, __gcc_v16qi, int);
int __builtin_neon_vqrshls_s32(int, int);
unsigned int __builtin_neon_vqrshls_u32(unsigned int, int);
__gcc_v8qi __builtin_neon_vqrshrn_n_v(__gcc_v16qi, int, int);
int __builtin_neon_vqrshrnd_n_s64(long long, int);
unsigned int __builtin_neon_vqrshrnd_n_u64(unsigned long long, int);
signed char __builtin_neon_vqrshrnh_n_s16(short, int);
unsigned char __builtin_neon_vqrshrnh_n_u16(unsigned short, int);
short __builtin_neon_vqrshrns_n_s32(int, int);
unsigned short __builtin_neon_vqrshrns_n_u32(unsigned int, int);
__gcc_v8qi __builtin_neon_vqrshrun_n_v(__gcc_v16qi, int, int);
unsigned int __builtin_neon_vqrshrund_n_s64(long long, int);
unsigned char __builtin_neon_vqrshrunh_n_s16(short, int);
unsigned short __builtin_neon_vqrshruns_n_s32(int, int);
__gcc_v8qi __builtin_neon_vqshl_n_v(__gcc_v8qi, int, int);
__gcc_v8qi __builtin_neon_vqshl_v(__gcc_v8qi, __gcc_v8qi, int);
signed char __builtin_neon_vqshlb_n_s8(signed char, int);
unsigned char __builtin_neon_vqshlb_n_u8(unsigned char, int);
signed char __builtin_neon_vqshlb_s8(signed char, signed char);
unsigned char __builtin_neon_vqshlb_u8(unsigned char, signed char);
long long __builtin_neon_vqshld_n_s64(long long, int);
unsigned long long __builtin_neon_vqshld_n_u64(unsigned long long, int);
long long __builtin_neon_vqshld_s64(long long, long long);
unsigned long long __builtin_neon_vqshld_u64(unsigned long long, long long);
short __builtin_neon_vqshlh_n_s16(short, int);
unsigned short __builtin_neon_vqshlh_n_u16(unsigned short, int);
short __builtin_neon_vqshlh_s16(short, short);
unsigned short __builtin_neon_vqshlh_u16(unsigned short, short);
__gcc_v16qi __builtin_neon_vqshlq_n_v(__gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vqshlq_v(__gcc_v16qi, __gcc_v16qi, int);
int __builtin_neon_vqshls_n_s32(int, int);
unsigned int __builtin_neon_vqshls_n_u32(unsigned int, int);
int __builtin_neon_vqshls_s32(int, int);
unsigned int __builtin_neon_vqshls_u32(unsigned int, int);
__gcc_v8qi __builtin_neon_vqshlu_n_v(__gcc_v8qi, int, int);
signed char __builtin_neon_vqshlub_n_s8(signed char, int);
long long __builtin_neon_vqshlud_n_s64(long long, int);
short __builtin_neon_vqshluh_n_s16(short, int);
__gcc_v16qi __builtin_neon_vqshluq_n_v(__gcc_v16qi, int, int);
int __builtin_neon_vqshlus_n_s32(int, int);
__gcc_v8qi __builtin_neon_vqshrn_n_v(__gcc_v16qi, int, int);
int __builtin_neon_vqshrnd_n_s64(long long, int);
unsigned int __builtin_neon_vqshrnd_n_u64(unsigned long long, int);
signed char __builtin_neon_vqshrnh_n_s16(short, int);
unsigned char __builtin_neon_vqshrnh_n_u16(unsigned short, int);
short __builtin_neon_vqshrns_n_s32(int, int);
unsigned short __builtin_neon_vqshrns_n_u32(unsigned int, int);
__gcc_v8qi __builtin_neon_vqshrun_n_v(__gcc_v16qi, int, int);
unsigned int __builtin_neon_vqshrund_n_s64(long long, int);
unsigned char __builtin_neon_vqshrunh_n_s16(short, int);
unsigned short __builtin_neon_vqshruns_n_s32(int, int);
__gcc_v8qi __builtin_neon_vqsub_v(__gcc_v8qi, __gcc_v8qi, int);
signed char __builtin_neon_vqsubb_s8(signed char, signed char);
unsigned char __builtin_neon_vqsubb_u8(unsigned char, unsigned char);
long long __builtin_neon_vqsubd_s64(long long, long long);
unsigned long long __builtin_neon_vqsubd_u64(unsigned long long, unsigned long long);
short __builtin_neon_vqsubh_s16(short, short);
unsigned short __builtin_neon_vqsubh_u16(unsigned short, unsigned short);
__gcc_v16qi __builtin_neon_vqsubq_v(__gcc_v16qi, __gcc_v16qi, int);
int __builtin_neon_vqsubs_s32(int, int);
unsigned int __builtin_neon_vqsubs_u32(unsigned int, unsigned int);
__gcc_v8qi __builtin_neon_vqtbl1_v(__gcc_v16qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vqtbl1q_v(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vqtbl2_v(__gcc_v16qi, __gcc_v16qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vqtbl2q_v(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vqtbl3_v(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vqtbl3q_v(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vqtbl4_v(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vqtbl4q_v(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vqtbx1_v(__gcc_v8qi, __gcc_v16qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vqtbx1q_v(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vqtbx2_v(__gcc_v8qi, __gcc_v16qi, __gcc_v16qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vqtbx2q_v(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vqtbx3_v(__gcc_v8qi, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vqtbx3q_v(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vqtbx4_v(__gcc_v8qi, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vqtbx4q_v(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vraddhn_v(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vrax1q_u64(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vrbit_v(__gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vrbitq_v(__gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vrecpe_f16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vrecpe_v(__gcc_v8qi, int);
double __builtin_neon_vrecped_f64(double);
__gcc_v16qi __builtin_neon_vrecpeq_f16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vrecpeq_v(__gcc_v16qi, int);
float __builtin_neon_vrecpes_f32(float);
__gcc_v8qi __builtin_neon_vrecps_f16(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vrecps_v(__gcc_v8qi, __gcc_v8qi, int);
double __builtin_neon_vrecpsd_f64(double, double);
__gcc_v16qi __builtin_neon_vrecpsq_f16(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vrecpsq_v(__gcc_v16qi, __gcc_v16qi, int);
float __builtin_neon_vrecpss_f32(float, float);
double __builtin_neon_vrecpxd_f64(double);
float __builtin_neon_vrecpxs_f32(float);
__gcc_v8qi __builtin_neon_vrhadd_v(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vrhaddq_v(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vrnd32x_f32(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vrnd32x_f64(__gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vrnd32xq_f32(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vrnd32xq_f64(__gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vrnd32z_f32(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vrnd32z_f64(__gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vrnd32zq_f32(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vrnd32zq_f64(__gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vrnd64x_f32(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vrnd64x_f64(__gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vrnd64xq_f32(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vrnd64xq_f64(__gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vrnd64z_f32(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vrnd64z_f64(__gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vrnd64zq_f32(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vrnd64zq_f64(__gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vrnd_f16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vrnd_v(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vrnda_f16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vrnda_v(__gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vrndaq_f16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vrndaq_v(__gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vrndi_f16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vrndi_v(__gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vrndiq_f16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vrndiq_v(__gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vrndm_f16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vrndm_v(__gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vrndmq_f16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vrndmq_v(__gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vrndn_f16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vrndn_v(__gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vrndnq_f16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vrndnq_v(__gcc_v16qi, int);
float __builtin_neon_vrndns_f32(float);
__gcc_v8qi __builtin_neon_vrndp_f16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vrndp_v(__gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vrndpq_f16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vrndpq_v(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vrndq_f16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vrndq_v(__gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vrndx_f16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vrndx_v(__gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vrndxq_f16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vrndxq_v(__gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vrshl_v(__gcc_v8qi, __gcc_v8qi, int);
long long __builtin_neon_vrshld_s64(long long, long long);
unsigned long long __builtin_neon_vrshld_u64(unsigned long long, long long);
__gcc_v16qi __builtin_neon_vrshlq_v(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vrshr_n_v(__gcc_v8qi, int, int);
long long __builtin_neon_vrshrd_n_s64(long long, int);
unsigned long long __builtin_neon_vrshrd_n_u64(unsigned long long, int);
__gcc_v8qi __builtin_neon_vrshrn_n_v(__gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vrshrq_n_v(__gcc_v16qi, int, int);
__gcc_v8qi __builtin_neon_vrsqrte_f16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vrsqrte_v(__gcc_v8qi, int);
double __builtin_neon_vrsqrted_f64(double);
__gcc_v16qi __builtin_neon_vrsqrteq_f16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vrsqrteq_v(__gcc_v16qi, int);
float __builtin_neon_vrsqrtes_f32(float);
__gcc_v8qi __builtin_neon_vrsqrts_f16(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vrsqrts_v(__gcc_v8qi, __gcc_v8qi, int);
double __builtin_neon_vrsqrtsd_f64(double, double);
__gcc_v16qi __builtin_neon_vrsqrtsq_f16(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vrsqrtsq_v(__gcc_v16qi, __gcc_v16qi, int);
float __builtin_neon_vrsqrtss_f32(float, float);
__gcc_v8qi __builtin_neon_vrsra_n_v(__gcc_v8qi, __gcc_v8qi, int, int);
long long __builtin_neon_vrsrad_n_s64(long long, long long, int);
unsigned long long __builtin_neon_vrsrad_n_u64(unsigned long long, unsigned long long, int);
__gcc_v16qi __builtin_neon_vrsraq_n_v(__gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v8qi __builtin_neon_vrsubhn_v(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vscale_f16(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vscale_f32(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vscaleq_f16(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vscaleq_f32(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vscaleq_f64(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v2sf __builtin_neon_vset_lane_f32(float, __gcc_v2sf, int);
__gcc_v4hi __builtin_neon_vset_lane_i16(short, __gcc_v4hi, int);
__gcc_v2si __builtin_neon_vset_lane_i32(int, __gcc_v2si, int);
__gcc_v1di __builtin_neon_vset_lane_i64(long long, __gcc_v1di, int);
__gcc_v8qi __builtin_neon_vset_lane_i8(signed char, __gcc_v8qi, int);
__gcc_v8hf __builtin_neon_vsetq_lane_bf16(__bf16, __gcc_v8hf, int);
__gcc_v4sf __builtin_neon_vsetq_lane_f32(float, __gcc_v4sf, int);
__gcc_v2df __builtin_neon_vsetq_lane_f64(double, __gcc_v2df, int);
__gcc_v8hi __builtin_neon_vsetq_lane_i16(short, __gcc_v8hi, int);
__gcc_v4si __builtin_neon_vsetq_lane_i32(int, __gcc_v4si, int);
__gcc_v2di __builtin_neon_vsetq_lane_i64(long long, __gcc_v2di, int);
__gcc_v16qi __builtin_neon_vsetq_lane_i8(signed char, __gcc_v16qi, int);
__gcc_v4si __builtin_neon_vsha1cq_u32(__gcc_v4usi, unsigned int, __gcc_v4usi);
unsigned int __builtin_neon_vsha1h_u32(unsigned int);
__gcc_v4si __builtin_neon_vsha1mq_u32(__gcc_v4usi, unsigned int, __gcc_v4usi);
__gcc_v4si __builtin_neon_vsha1pq_u32(__gcc_v4usi, unsigned int, __gcc_v4usi);
__gcc_v16qi __builtin_neon_vsha1su0q_u32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vsha1su1q_u32(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vsha256h2q_u32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vsha256hq_u32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vsha256su0q_u32(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vsha256su1q_u32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vsha512h2q_u64(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vsha512hq_u64(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vsha512su0q_u64(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vsha512su1q_u64(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vshl_n_v(__gcc_v8qi, int, int);
__gcc_v8qi __builtin_neon_vshl_v(__gcc_v8qi, __gcc_v8qi, int);
long long __builtin_neon_vshld_n_s64(long long, int);
unsigned long long __builtin_neon_vshld_n_u64(unsigned long long, int);
long long __builtin_neon_vshld_s64(long long, long long);
unsigned long long __builtin_neon_vshld_u64(unsigned long long, long long);
__gcc_v16qi __builtin_neon_vshll_n_v(__gcc_v8qi, int, int);
__gcc_v16qi __builtin_neon_vshlq_n_v(__gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vshlq_v(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vshr_n_v(__gcc_v8qi, int, int);
long long __builtin_neon_vshrd_n_s64(long long, int);
unsigned long long __builtin_neon_vshrd_n_u64(unsigned long long, int);
__gcc_v8qi __builtin_neon_vshrn_n_v(__gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vshrq_n_v(__gcc_v16qi, int, int);
__gcc_v8qi __builtin_neon_vsli_n_v(__gcc_v8qi, __gcc_v8qi, int, int);
long long __builtin_neon_vslid_n_s64(long long, long long, int);
unsigned long long __builtin_neon_vslid_n_u64(unsigned long long, unsigned long long, int);
__gcc_v16qi __builtin_neon_vsliq_n_v(__gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vsm3partw1q_u32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vsm3partw2q_u32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vsm3ss1q_u32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vsm3tt1aq_u32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vsm3tt1bq_u32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vsm3tt2aq_u32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vsm3tt2bq_u32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v16qi __builtin_neon_vsm4ekeyq_u32(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vsm4eq_u32(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vsqadd_v(__gcc_v8qi, __gcc_v8qi, int);
unsigned char __builtin_neon_vsqaddb_u8(unsigned char, signed char);
unsigned long long __builtin_neon_vsqaddd_u64(unsigned long long, long long);
unsigned short __builtin_neon_vsqaddh_u16(unsigned short, short);
__gcc_v16qi __builtin_neon_vsqaddq_v(__gcc_v16qi, __gcc_v16qi, int);
unsigned int __builtin_neon_vsqadds_u32(unsigned int, int);
__gcc_v8qi __builtin_neon_vsqrt_f16(__gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vsqrt_v(__gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vsqrtq_f16(__gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vsqrtq_v(__gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vsra_n_v(__gcc_v8qi, __gcc_v8qi, int, int);
long long __builtin_neon_vsrad_n_s64(long long, long long, int);
unsigned long long __builtin_neon_vsrad_n_u64(unsigned long long, unsigned long long, int);
__gcc_v16qi __builtin_neon_vsraq_n_v(__gcc_v16qi, __gcc_v16qi, int, int);
__gcc_v8qi __builtin_neon_vsri_n_v(__gcc_v8qi, __gcc_v8qi, int, int);
long long __builtin_neon_vsrid_n_s64(long long, long long, int);
unsigned long long __builtin_neon_vsrid_n_u64(unsigned long long, unsigned long long, int);
__gcc_v16qi __builtin_neon_vsriq_n_v(__gcc_v16qi, __gcc_v16qi, int, int);
void __builtin_neon_vst1_bf16(void *, __gcc_v8qi, int);
void __builtin_neon_vst1_bf16_x2(void *, __gcc_v8qi, __gcc_v8qi, int);
void __builtin_neon_vst1_bf16_x3(void *, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
void __builtin_neon_vst1_bf16_x4(void *, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
void __builtin_neon_vst1_lane_bf16(void *, __gcc_v8qi, int, int);
void __builtin_neon_vst1_lane_v(void *, __gcc_v8qi, int, int);
void __builtin_neon_vst1_v(void *, __gcc_v8qi, int);
void __builtin_neon_vst1_x2_v(void *, __gcc_v8qi, __gcc_v8qi, int);
void __builtin_neon_vst1_x3_v(void *, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
void __builtin_neon_vst1_x4_v(void *, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
void __builtin_neon_vst1q_bf16(void *, __gcc_v16qi, int);
void __builtin_neon_vst1q_bf16_x2(void *, __gcc_v16qi, __gcc_v16qi, int);
void __builtin_neon_vst1q_bf16_x3(void *, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
void __builtin_neon_vst1q_bf16_x4(void *, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
void __builtin_neon_vst1q_lane_bf16(void *, __gcc_v16qi, int, int);
void __builtin_neon_vst1q_lane_v(void *, __gcc_v16qi, int, int);
void __builtin_neon_vst1q_v(void *, __gcc_v16qi, int);
void __builtin_neon_vst1q_x2_v(void *, __gcc_v16qi, __gcc_v16qi, int);
void __builtin_neon_vst1q_x3_v(void *, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
void __builtin_neon_vst1q_x4_v(void *, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
void __builtin_neon_vst2_bf16(void *, __gcc_v8qi, __gcc_v8qi, int);
void __builtin_neon_vst2_lane_bf16(void *, __gcc_v8qi, __gcc_v8qi, int, int);
void __builtin_neon_vst2_lane_v(void *, __gcc_v8qi, __gcc_v8qi, int, int);
void __builtin_neon_vst2_v(void *, __gcc_v8qi, __gcc_v8qi, int);
void __builtin_neon_vst2q_bf16(void *, __gcc_v16qi, __gcc_v16qi, int);
void __builtin_neon_vst2q_lane_bf16(void *, __gcc_v16qi, __gcc_v16qi, int, int);
void __builtin_neon_vst2q_lane_v(void *, __gcc_v16qi, __gcc_v16qi, int, int);
void __builtin_neon_vst2q_v(void *, __gcc_v16qi, __gcc_v16qi, int);
void __builtin_neon_vst3_bf16(void *, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
void __builtin_neon_vst3_lane_bf16(void *, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int, int);
void __builtin_neon_vst3_lane_v(void *, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int, int);
void __builtin_neon_vst3_v(void *, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
void __builtin_neon_vst3q_bf16(void *, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
void __builtin_neon_vst3q_lane_bf16(void *, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int, int);
void __builtin_neon_vst3q_lane_v(void *, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int, int);
void __builtin_neon_vst3q_v(void *, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
void __builtin_neon_vst4_bf16(void *, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
void __builtin_neon_vst4_lane_bf16(void *, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int, int);
void __builtin_neon_vst4_lane_v(void *, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int, int);
void __builtin_neon_vst4_v(void *, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
void __builtin_neon_vst4q_bf16(void *, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
void __builtin_neon_vst4q_lane_bf16(void *, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int, int);
void __builtin_neon_vst4q_lane_v(void *, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int, int);
void __builtin_neon_vst4q_v(void *, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
void __builtin_neon_vstl1_lane_f64(void *, __gcc_v8qi, int, int);
void __builtin_neon_vstl1_lane_p64(void *, __gcc_v8qi, int, int);
void __builtin_neon_vstl1_lane_s64(void *, __gcc_v8qi, int, int);
void __builtin_neon_vstl1_lane_u64(void *, __gcc_v8qi, int, int);
void __builtin_neon_vstl1q_lane_f64(void *, __gcc_v16qi, int, int);
void __builtin_neon_vstl1q_lane_p64(void *, __gcc_v16qi, int, int);
void __builtin_neon_vstl1q_lane_s64(void *, __gcc_v16qi, int, int);
void __builtin_neon_vstl1q_lane_u64(void *, __gcc_v16qi, int, int);
void __builtin_neon_vstrq_p128(void *, unsigned __int128);
long long __builtin_neon_vsubd_s64(long long, long long);
unsigned long long __builtin_neon_vsubd_u64(unsigned long long, unsigned long long);
__gcc_v8qi __builtin_neon_vsubhn_v(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vtbl1_v(__gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vtbl2_v(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vtbl3_v(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vtbl4_v(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vtbx1_v(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vtbx2_v(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vtbx3_v(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
__gcc_v8qi __builtin_neon_vtbx4_v(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
void __builtin_neon_vtrn_v(void *, __gcc_v8qi, __gcc_v8qi, int);
void __builtin_neon_vtrnq_v(void *, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vtst_v(__gcc_v8qi, __gcc_v8qi, int);
unsigned long long __builtin_neon_vtstd_s64(long long, long long);
unsigned long long __builtin_neon_vtstd_u64(unsigned long long, unsigned long long);
__gcc_v16qi __builtin_neon_vtstq_v(__gcc_v16qi, __gcc_v16qi, int);
__gcc_v8qi __builtin_neon_vuqadd_v(__gcc_v8qi, __gcc_v8qi, int);
signed char __builtin_neon_vuqaddb_s8(signed char, unsigned char);
long long __builtin_neon_vuqaddd_s64(long long, unsigned long long);
short __builtin_neon_vuqaddh_s16(short, unsigned short);
__gcc_v16qi __builtin_neon_vuqaddq_v(__gcc_v16qi, __gcc_v16qi, int);
int __builtin_neon_vuqadds_s32(int, unsigned int);
__gcc_v8qi __builtin_neon_vusdot_s32(__gcc_v8qi, __gcc_v8qi, __gcc_v8qi, int);
__gcc_v16qi __builtin_neon_vusdotq_s32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vusmmlaq_s32(__gcc_v16qi, __gcc_v16qi, __gcc_v16qi, int);
void __builtin_neon_vuzp_v(void *, __gcc_v8qi, __gcc_v8qi, int);
void __builtin_neon_vuzpq_v(void *, __gcc_v16qi, __gcc_v16qi, int);
__gcc_v16qi __builtin_neon_vxarq_u64(__gcc_v16qi, __gcc_v16qi, int, int);
void __builtin_neon_vzip_v(void *, __gcc_v8qi, __gcc_v8qi, int);
void __builtin_neon_vzipq_v(void *, __gcc_v16qi, __gcc_v16qi, int);
// clang-format on
