<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.cprover.regression</groupId>
    <artifactId>regression.jbmc</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <parent>
        <groupId>org.cprover.regression</groupId>
        <artifactId>regression</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <modules>
        <module>aastore_aaload1</module>
        <module>address_space_size_limit1</module>
        <module>address_space_size_limit2</module>
        <module>annotations1</module>
        <module>annotations2</module>
        <module>ArithmeticException1</module>
        <module>ArithmeticException2</module>
        <module>ArithmeticException3</module>
        <module>ArithmeticException4</module>
        <module>ArithmeticException5</module>
        <module>ArithmeticException6</module>
        <module>ArithmeticException7</module>
        <module>array1</module>
        <module>array2</module>
        <module>array-cell-sensitivity1</module>
        <module>array-cell-sensitivity2</module>
        <module>array-cell-sensitivity-negative-size</module>
        <module>array-cell-sensitivity-static-fields</module>
        <module>array-clone</module>
        <module>array_nonconstsize_nonconstaccess</module>
        <module>ArrayIndexOutOfBoundsException1</module>
        <module>ArrayIndexOutOfBoundsException2</module>
        <module>ArrayIndexOutOfBoundsException3</module>
        <module>arraylength1</module>
        <module>arrayread1</module>
        <module>assert1</module>
        <module>assert2</module>
        <module>assert3</module>
        <module>assert4</module>
        <module>assert5</module>
        <module>assert6</module>
        <module>assert7</module>
        <module>assert-no-exceptions-thrown</module>
        <module>assertion_error_constructors</module>
        <module>assume1</module>
        <module>assume2</module>
        <module>assume3</module>
        <module>assume-inputs-integral</module>
        <module>assume-inputs-interval</module>
        <module>assume-inputs-non-null</module>
        <module>astore_aload1</module>
        <module>athrow1</module>
        <module>basic1</module>
        <module>basic2</module>
        <module>bitwise1</module>
        <module>boolean1</module>
        <module>boolean2</module>
        <module>cast1</module>
        <module>cast_null1</module>
        <module>cast_null2</module>
        <module>catch1</module>
        <module>char1</module>
        <module>class-fields</module>
        <module>class-literals</module>
        <module>class-loading-annotations</module>
        <module>class_hierarchy</module>
        <module>Class_method1</module>
        <module>ClassCastException1</module>
        <module>ClassCastException2</module>
        <module>ClassCastException3</module>
        <module>ClassCastException4</module>
        <module>classIdentifier</module>
        <module>classpath-class-incorrect-package</module>
        <module>classpath-class-with-jar</module>
        <module>classpath-class-with-one-dir</module>
        <module>classpath-class-with-two-dirs</module>
        <module>classpath-invalid</module>
        <module>classpath-jar</module>
        <module>classpath-jar-entry-method</module>
        <module>classpath-jar-incorrect-package</module>
        <module>classpath-jar-load-whole-jar</module>
        <module>classpath-jar-main-class</module>
        <module>classpath-jar-with-two-jars</module>
        <module>classpath-two-classes</module>
        <module>classpath-two-jars</module>
        <module>classtest1</module>
        <module>clean_derefs</module>
        <module>clinit-lifting1</module>
        <module>clinit-lifting2</module>
        <module>clinit-lifting3</module>
        <module>const1</module>
        <module>constructor1</module>
        <module>constructor2</module>
        <module>context-include-exclude</module>
        <module>core-models-required</module>
        <module>coreModels</module>
        <module>cp-include-path</module>
        <module>cp-include-path-json</module>
        <module>cprover-always-load-nondet-initialize</module>
        <module>create-array-with-type-1</module>
        <module>create-array-with-type-2</module>
        <module>create-array-with-type-3</module>
        <module>default-methods</module>
        <module>dereference-virtual-call</module>
        <module>destructor1</module>
        <module>destructors</module>
        <module>deterministic_assignments_json</module>
        <module>divide_by_zero</module>
        <module>double1</module>
        <module>dynamic-multi-dimensional-array</module>
        <module>enum</module>
        <module>environment1</module>
        <module>exception-cleanup</module>
        <module>exceptions1</module>
        <module>exceptions10</module>
        <module>exceptions11</module>
        <module>exceptions12</module>
        <module>exceptions13</module>
        <module>exceptions14</module>
        <module>exceptions15</module>
        <module>exceptions16</module>
        <module>exceptions18</module>
        <module>exceptions19</module>
        <module>exceptions2</module>
        <module>exceptions20</module>
        <module>exceptions21</module>
        <module>exceptions22</module>
        <module>exceptions23</module>
        <module>exceptions24</module>
        <module>exceptions26</module>
        <module>exceptions27</module>
        <module>exceptions28</module>
        <module>exceptions29</module>
        <module>exceptions3</module>
        <module>exceptions4</module>
        <module>exceptions5</module>
        <module>exceptions6</module>
        <module>exceptions7</module>
        <module>exceptions8</module>
        <module>exceptions9</module>
        <module>external_getstatic1</module>
        <module>fake_stubs</module>
        <module>farith1</module>
        <module>fcmpx_dcmpx1</module>
        <module>finally1</module>
        <module>finally2</module>
        <module>finally3</module>
        <module>finally4</module>
        <module>finally5</module>
        <module>finally6</module>
        <module>finally7</module>
        <module>float1</module>
        <module>FloatToIntConversion</module>
        <module>function1</module>
        <module>function2</module>
        <module>function3</module>
        <module>function4</module>
        <module>generic_base_type</module>
        <module>generic_class_bound1</module>
        <module>generic_function_parameter</module>
        <module>generic_static_field</module>
        <module>generic_virtual_function</module>
        <module>generics</module>
        <module>generics_recursive_parameters</module>
        <module>generics_type_param</module>
        <module>i2x_argument_double_cast</module>
        <module>iarith1</module>
        <module>iarith2</module>
        <module>if_acmp1</module>
        <module>if_expr1</module>
        <module>if_icmp1</module>
        <module>ifxx1</module>
        <module>inferlexicalscope1</module>
        <module>Inheritance1</module>
        <module>inherited_static_field1</module>
        <module>inherited_static_field10</module>
        <module>inherited_static_field2</module>
        <module>inherited_static_field3</module>
        <module>inherited_static_field4</module>
        <module>inherited_static_field5</module>
        <module>inherited_static_field6</module>
        <module>inherited_static_field7</module>
        <module>inherited_static_field8</module>
        <module>inherited_static_field9</module>
        <module>instanceof1</module>
        <module>instanceof10</module>
        <module>instanceof11</module>
        <module>instanceof12</module>
        <module>instanceof13</module>
        <module>instanceof14</module>
        <module>instanceof15</module>
        <module>instanceof16</module>
        <module>instanceof2</module>
        <module>instanceof3</module>
        <module>instanceof4</module>
        <module>instanceof5</module>
        <module>instanceof6</module>
        <module>instanceof7</module>
        <module>instanceof8</module>
        <module>instanceof9</module>
        <module>integer_without_simplify1</module>
        <module>interface1</module>
        <module>internal1</module>
        <module>isnan1</module>
        <module>iterator1</module>
        <module>iterator2</module>
        <module>json_trace1</module>
        <module>json_trace3</module>
        <module>jsr2</module>
        <module>JumpSimplification</module>
        <module>lambda-boxing</module>
        <module>lambda-defined-on-string-type</module>
        <module>lambda-generic-boxing</module>
        <module>lambda-inherited-interface</module>
        <module>lambda-interface-declaring-equals</module>
        <module>lambda-interface-declaring-hashcode</module>
        <module>lambda-interface-with-defaults</module>
        <module>lambda-making-functional-interface-by-defining-methods</module>
        <module>lambda-multiple-inheritence</module>
        <module>lambda-reference-kinds</module>
        <module>lambda-unhandled-types</module>
        <module>lambda-void-return-type</module>
        <module>lambda-widening-conversions</module>
        <module>lambda1</module>
        <module>lambda2</module>
        <module>lambda3</module>
        <module>lambda4</module>
        <module>lazyloading1</module>
        <module>lazyloading10</module>
        <module>lazyloading11</module>
        <module>lazyloading2</module>
        <module>lazyloading3</module>
        <module>lazyloading4</module>
        <module>lazyloading5</module>
        <module>lazyloading6</module>
        <module>lazyloading7</module>
        <module>lazyloading8</module>
        <module>lazyloading9</module>
        <module>lazyloading_array_parameter</module>
        <module>lazyloading_cyclic_class</module>
        <module>lazyloading_indirect_array_parameter</module>
        <module>lazyloading_indirect_generic_array_parameter</module>
        <module>lazyloading_inheritance</module>
        <module>lazyloading_inheritance_field</module>
        <module>lazyloading_multiple_array_types</module>
        <module>lazyloading_multiple_generic_parameters</module>
        <module>lazyloading_nested_generic_parameters</module>
        <module>lazyloading_no_candidates</module>
        <module>lazyloading_opaquereturn</module>
        <module>lazyloading_recursive_class</module>
        <module>lazyloading_synthetic_method_cleanup1</module>
        <module>lazyloading_synthetic_method_cleanup2</module>
        <module>lazyloading_synthetic_method_cleanup3</module>
        <module>list-symbols</module>
        <module>list1</module>
        <module>LocalVarTable1</module>
        <module>LocalVarTable2</module>
        <module>LocalVarTable3</module>
        <module>LocalVarTable4</module>
        <module>LocalVarTable5</module>
        <module>long1</module>
        <module>lookupswitch1</module>
        <module>loop1</module>
        <module>lots_local_variables_manual</module>
        <module>lots_of_local_variables</module>
        <module>lvt-unexpected</module>
        <module>main-args-elements-non-null1</module>
        <module>main-args-elements-non-null2</module>
        <module>main-args-non-null-with-function1</module>
        <module>main-args-non-null1</module>
        <module>main-class-from-function</module>
        <module>main-inner-class</module>
        <module>method_parameters1</module>
        <module>method_parameters2</module>
        <module>monitorenter1</module>
        <module>multidimensional-array-char</module>
        <module>multidimensional-array-object-factory</module>
        <module>multinewarray</module>
        <module>must-not-throw-annotation</module>
        <module>NegativeArraySizeException1</module>
        <module>NegativeArraySizeException2</module>
        <module>nil-names</module>
        <module>no-main-args-elements-maybe-null1</module>
        <module>no-main-args-elements-maybe-null2</module>
        <module>no-main-args-maybe-null1</module>
        <module>no-main-args-maybe-null2</module>
        <module>no-main-int-array-maybe-null1</module>
        <module>no-main-multi-array-maybe-null1</module>
        <module>no-main-multi-array-maybe-null2</module>
        <module>no-main-object-array-elements-maybe-null1</module>
        <module>no-main-object-array-elements-maybe-null2</module>
        <module>no-main-object-array-maybe-null1</module>
        <module>no-main-object-array-maybe-null2</module>
        <module>nondet-array-size</module>
        <module>nondet-static</module>
        <module>nondet_initialize_exception_handler</module>
        <module>nondet_propagation1</module>
        <module>NondetArray</module>
        <module>NondetArray2</module>
        <module>NondetArray3</module>
        <module>NondetArray4</module>
        <module>NondetArrayPrimitive</module>
        <module>NondetAssume1</module>
        <module>NondetAssume2</module>
        <module>NondetBoolean</module>
        <module>NondetByte</module>
        <module>NondetCastToObject</module>
        <module>NondetChar</module>
        <module>NondetCharSequence</module>
        <module>NondetDirectFromMethod</module>
        <module>NondetDouble</module>
        <module>NondetEnumArg</module>
        <module>NondetEnumArgField</module>
        <module>NondetEnumOpaqueReturn</module>
        <module>NondetFloat</module>
        <module>NondetGenericArray</module>
        <module>NondetGenericRecursive</module>
        <module>NondetGenericRecursive2</module>
        <module>NondetGenericWithNull</module>
        <module>NondetGenericWithoutNull</module>
        <module>NondetInit</module>
        <module>NondetInit2</module>
        <module>NondetInit3</module>
        <module>NondetInt</module>
        <module>NondetLong</module>
        <module>NondetShort</module>
        <module>NondetString</module>
        <module>NondetStringBuffer</module>
        <module>NondetStringBuilder</module>
        <module>NullPointer1</module>
        <module>NullPointer2</module>
        <module>NullPointer3</module>
        <module>NullPointer4</module>
        <module>NullPointerException1</module>
        <module>NullPointerException2</module>
        <module>NullPointerException3</module>
        <module>NullPointerException4</module>
        <module>output-options</module>
        <module>overlay-class</module>
        <module>overloading1</module>
        <module>package1</module>
        <module>package_friendly1</module>
        <module>parameter-annotation-not-null</module>
        <module>phi-merge_uninitialized_values</module>
        <module>pointer_check1</module>
        <module>provide_object_implementation</module>
        <module>putfield_getfield1</module>
        <module>putstatic_getstatic1</module>
        <module>putstatic_source_location</module>
        <module>reachability-slice</module>
        <module>recursion1</module>
        <module>recursion2</module>
        <module>remove_virtual_function_typecast</module>
        <module>removed_virtual_functions</module>
        <module>repeated_guards</module>
        <module>return-generic-member</module>
        <module>return1</module>
        <module>return2</module>
        <module>shift1</module>
        <module>short1</module>
        <module>short2</module>
        <module>siblingobjects1</module>
        <module>siblingobjects2</module>
        <module>simplify-classid-of-interface</module>
        <module>simplify_expr_termination</module>
        <module>stack_var1</module>
        <module>stack_var10</module>
        <module>stack_var11</module>
        <module>stack_var12</module>
        <module>stack_var2</module>
        <module>stack_var3</module>
        <module>stack_var4</module>
        <module>stack_var5</module>
        <module>stack_var6</module>
        <module>stack_var7</module>
        <module>stack_var8</module>
        <module>stack_var9</module>
        <module>static_init1</module>
        <module>static_init2</module>
        <module>static_init_order</module>
        <module>static_method1</module>
        <module>store_load1</module>
        <module>string_field_aliasing</module>
        <module>string_literal1</module>
        <module>stub_identifiers</module>
        <module>swap1</module>
        <module>swap2</module>
        <module>symex_can_track_when_clinits_have_definitely_been_run</module>
        <module>symex_complexity</module>
        <module>symex_should_exclude_null_pointers</module>
        <module>symex_should_resolve_class_identifiers</module>
        <module>tableswitch1</module>
        <module>tableswitch2</module>
        <module>temp_stack_variable_packing</module>
        <module>throwing-function-return-value</module>
        <module>too-many-args</module>
        <module>trace_class_identifier</module>
        <module>trace_options_json_extended</module>
        <module>trace_types</module>
        <module>uninitialised1</module>
        <module>validate-trace</module>
        <module>VarLengthArrayTrace1</module>
        <module>very-long-jumps</module>
        <module>virtual1</module>
        <module>virtual10</module>
        <module>virtual2</module>
        <module>virtual4</module>
        <module>virtual5</module>
        <module>virtual6</module>
        <module>virtual7</module>
        <module>virtual8</module>
        <module>virtual9</module>
        <module>virtual_filter_value_sets</module>
        <module>virtual_function_unwinding</module>
        <module>virtual_temp_var_for_this_argument</module>
    </modules>

</project>
