name: Build and Test Xen

on: [push]

jobs:
  Linux:

    runs-on: ubuntu-18.04

    steps:
    - name: Install Packages
      run: sudo apt-get install coreutils \
        build-essential gcc git make flex bison \
        software-properties-common libwww-perl python \
        bin86 gdb bcc liblzma-dev python-dev gettext iasl \
        uuid-dev libncurses5-dev libncursesw5-dev pkg-config \
        libgtk2.0-dev libyajl-dev sudo time

    - uses: actions/checkout@v1

    - name: build CBMC tools
      run: make -C src minisat2-download
      run: make -C src cbmc.dir goto-cc.dir goto-diff.dir

    - name: get Xen 4.13
      run: git clone git://xenbits.xen.org/xen.git xen_4_13 && cd xen_4_13 && git reset --hard RELEASE-4.13.0
