name: CBMC Packages

on:
  # Build packages when new commits are pushed to develop
  push:
    branches:
      - develop

jobs:
  Tags:
    #
    # Generate a set of values (like a single timestamp and package name)
    # that can be used consistently by the subsequent jobs building
    # the packages.
    #
    name: Generate package tag
    runs-on: ubuntu-latest
    outputs:
      time: ${{ steps.time.outputs.time }}
      sha: ${{ steps.sha.outputs.sha }}
      runid: ${{ steps.runid.outputs.runid }}
      runnum: ${{ steps.runnum.outputs.runnum }}
      cbmc_version: ${{ steps.version.outputs.cbmc_version }}
      pkg_version: ${{ steps.version.outputs.pkg_version }}
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v2

      - id: time
        run: |
          TIME=$(date --utc +%Y%m%dT%H%M%SZ)
          echo "::set-output name=time::${TIME}"

      - id: sha
        run: |
          SHA=${{ github.sha }}
          echo "::set-output name=sha::${SHA:0:8}"

      - id: runid
        run: |
          ID=${{ github.run_id }}
          echo "::set-output name=runid::${ID}"

      - id: runnum
        run: |
          NUM=${{ github.run_number }}
          echo "::set-output name=runnum::${NUM}"

      - id: version
        run: |
          CBMC_VERSION=$(grep CBMC_VERSION src/config.inc | sed 's/.*= *//')
          PKG_VERSION=$(echo ${CBMC_VERSION}-${{ github.run_number }})
          echo "::set-output name=cbmc_version::${CBMC_VERSION}"
          echo "::set-output name=pkg_version::${PKG_VERSION}"

      - name: echo
        run: |
          echo TIME = ${{ steps.time.outputs.time }}
          echo SHA = ${{ steps.sha.outputs.sha }}
          echo RUN ID = ${{ steps.runid.outputs.runid }}
          echo RUN NUMBER = ${{ steps.runnum.outputs.runnum }}
          echo CBMC_VERSION = ${{ steps.version.outputs.cbmc_version }}
          echo PKG_VERSION = ${{ steps.version.outputs.pkg_version }}

  Ubuntu16:
    name: Ubuntu 16 cbmc package
    runs-on: ubuntu-16.04
    needs: Tags
    env:
      PKG_VERSION: ${{needs.Tags.outputs.pkg_version}}
      CBMC_VERSION: ${{needs.Tags.outputs.cbmc_version}}
      PACKAGE_NAME: cbmc_${{needs.Tags.outputs.pkg_version}}~xenial_amd64.deb
      ARTIFACT_NAME: Ubuntu16 cbmc ${{needs.Tags.outputs.pkg_version}} xenial ${{needs.Tags.outputs.time}} ${{needs.Tags.outputs.sha}} ${{needs.Tags.outputs.runid}}
      SCRIPT_DIR: .github/workflows/debian

    steps:

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Update the submodules
        run: git submodule update --init

      - name: Create the package
        run: |
          cp -r . /tmp/cbmc-${CBMC_VERSION}
          cp ${SCRIPT_DIR}/Makefile ${SCRIPT_DIR}/changelog ${SCRIPT_DIR}/surefire ${SCRIPT_DIR}/64bit_regression_tests.patch /tmp
          make -C /tmp GITHUB=1 STABLE=1 CBMC_VERSION=${CBMC_VERSION} PKG_VERSION=${PKG_VERSION}
          mv /tmp/*.deb ${PACKAGE_NAME}

      - name: Upload the package
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.PACKAGE_NAME }}

  Ubuntu18:
    name: Ubuntu 18 cbmc package
    runs-on: ubuntu-18.04
    needs: Tags
    env:
      PKG_VERSION: ${{needs.Tags.outputs.pkg_version}}
      CBMC_VERSION: ${{needs.Tags.outputs.cbmc_version}}
      PACKAGE_NAME: cbmc_${{needs.Tags.outputs.pkg_version}}~bionic_amd64.deb
      ARTIFACT_NAME: Ubuntu18 cbmc ${{needs.Tags.outputs.pkg_version}} bionic ${{needs.Tags.outputs.time}} ${{needs.Tags.outputs.sha}} ${{needs.Tags.outputs.runid}}
      SCRIPT_DIR: .github/workflows/debian

    steps:

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Update the submodules
        run: git submodule update --init

      - name: Create the package
        run: |
          cp -r . /tmp/cbmc-${CBMC_VERSION}
          cp ${SCRIPT_DIR}/Makefile ${SCRIPT_DIR}/changelog ${SCRIPT_DIR}/surefire ${SCRIPT_DIR}/64bit_regression_tests.patch /tmp
          make -C /tmp GITHUB=1 STABLE=1 CBMC_VERSION=${CBMC_VERSION} PKG_VERSION=${PKG_VERSION}
          mv /tmp/*.deb ${PACKAGE_NAME}

      - name: Upload the package
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.PACKAGE_NAME }}

  MacOS:
    name: MacOS tarball
    runs-on: macos-10.15
    needs: Tags
    env:
      VERSION: ${{needs.Tags.outputs.pkg_version}}
      PACKAGE_NAME: cbmc_${{needs.Tags.outputs.pkg_version}}~catalina.tar.gz
      ARTIFACT_NAME: MacOS cbmc ${{needs.Tags.outputs.pkg_version}} catalina ${{needs.Tags.outputs.time}} ${{needs.Tags.outputs.sha}} ${{needs.Tags.outputs.runid}}
      SCRIPT_DIR: .github/workflows/macos15

    steps:

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Update the submodules
        run: git submodule update --init

      - name: Build the package
        run: |
          make -f ${SCRIPT_DIR}/Makefile
          mv cbmc.tar.gz ${PACKAGE_NAME}

      - name: Upload the package
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: ${{env.PACKAGE_NAME}}

  VS2019:
    name: Windows VS2019 installer
    runs-on: windows-2019
    needs: Tags
    env:
      VERSION: ${{needs.Tags.outputs.pkg_version}}
      PACKAGE_NAME: cbmc_${{needs.Tags.outputs.pkg_version}}~vs2019.msi
      ARTIFACT_NAME: Windows cbmc ${{needs.Tags.outputs.pkg_version}} vs2019 ${{needs.Tags.outputs.time}} ${{needs.Tags.outputs.sha}} ${{needs.Tags.outputs.runid}}
      SCRIPT_DIR: .github\workflows\vs2019

    defaults:
      run:
         shell: cmd
    steps:

      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Update the submodules
        run: git submodule update --init

      - name: Install bison and flex
        run: ${{env.SCRIPT_DIR}}\install-bison.bat

      - name: Patch cbmc
        run: ${{env.SCRIPT_DIR}}\patch-cbmc.bat

      - name: Build cbmc
        run: ${{env.SCRIPT_DIR}}\build-cbmc.bat

      - name: Build the installer
        run: |
           ${{env.SCRIPT_DIR}}\build-installer.bat cbmc && move cbmc.msi ${{env.PACKAGE_NAME}}

      - name: Upload the installer
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.ARTIFACT_NAME}}
          path: ${{env.PACKAGE_NAME}}
