name: pull-request-linting
on:
  pull_request:
    branches: [ develop ]

jobs:
  clang-tidy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Check out branches so they’re local
        run: |
          git checkout -b ${{ github.ref }}
          git checkout ${{ github.base_ref }}
          git checkout ${{ github.ref }}

      - name: Fetch dependencies
        env:
          DEBIAN_FRONTENT: noninteractive
        run: |
          sudo apt-get install -yq clang-tidy cmake python3 python3-pip parallel
          pip3 install --user PyYaml unidiff
      - name: Run clang-tidy linter
        id: linter
        env:
          BASE_BRANCH: ${{ github.base_ref }}
          MERGE_BRANCH: ${{ github.ref }}
        run: scripts/ci_get_clang_tidy_annotations
      - name: Push annotations
        run: |
          curl -X POST \
               -H "Accept: application/vnd.github.antiope-preview+json" \
               "https://api.github.com/repos/diffblue/cbmc/check-runs?access_token=$TOKEN" \
               -d "$(scripts/ci-get-github-check-annotation-payload)"
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANNOTATIONS: $ {{ steps.linter.outputs.annotations }}
          HEAD_SHA: ${{ github.sha }}
          CHECK_NAME: clang-tidy
